### ISSUE TITLE
There are files with a lot of unsummarized ops

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#10063]
https://portal.microsoftgeneva.com/s/A756A09F

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/46826984/165408095-e6649e16-1bb2-4ca5-a839-4e6614efcebd.png">

This data tracks number of unsummarized ops in a file after collab session is closed in ODSP.
Spiked about 1K are very concerning. 

Here is my attempt to capture it on client side - with assumption that such ops would eventually get summarized, and thus we should see a summary with a lot of ops:

> union Office_Fluid_FluidRuntime_*
| where Data_eventName == "fluid:telemetry:Summarizer:Running:Summarize_generate"
| where Event_Time > ago(7d)
| where Data_opsSinceLastSummary > 2000
| summarize count() by reason = Data_summarizeReason

reason | count_
-- | --
maxOps | 45
maxTime | 16
idle | 1

This seems to actually capture the problem. Looking at Data_opsSinceLastSummary > 4000, I see 8 hits as well.
This is all Chapter 1 (Data_hostName == "Microsoft Teams Web")

Note that maxOps being at 1000 should suggest we should have summarized earlier, that's the place I'd start looking first as it seems like an easier target.

We need to understand better why we get into these states, and how to address them.

Some useful tools:
1. Many events have Data_sequenceNumber property, so looking at it can help us better understand when file grows.
2. We can adjust maxOpsSinceLastSummary to be lower than 7K if it helps us to see problems faster.
3. That said, I see 219 fluid:telemetry:SummaryStatus:Behind events! There is probably a lot of overlap, as only 50 docs hit it, and maybe a lot of clients issued same event at the same time.

**Comment by NicholasCouri** [comment]
One of the documents had a client that processed a huge amount of ops, 6000,  in only 20 secs ( 28k in 4 mins). 

union Office_Fluid_FluidRuntime_*
 | where Data_docId == "wbsuZYjqBjBQcgHGTAg1Qxhcb%2B0b%2BUSIswMorZfxIGM%3D"
| where Data_containerId == "010ce3e6-567c-43e3-a74f-5ad96595b5d9"
| where Event_Time > datetime(2022-04-28 09:14:47.2930000)  and Event_Time <datetime(2022-04-28 09:22:09.4370000)
| project Event_Sequence, Event_Time, Data_eventName, Data_sequenceNumber

<HTML>
		

Event_Sequence | Event_Time | Data_eventName | Data_sequenceNumber
-- | -- | -- | --
134 | 2022-04-28 09:17:31.3170000 | fluid:telemetry:Batching:Length |  
136 | 2022-04-28 09:19:25.0820000 | fluid:telemetry:OpPerf:MsnStatistics | 2000
137 | 2022-04-28 09:19:31.6530000 | fluid:telemetry:OpPerf:MsnStatistics | 3000
138 | 2022-04-28 09:19:31.6660000 | fluid:telemetry:Batching:LengthTooBig |  
140 | 2022-04-28 09:19:34.7540000 | fluid:telemetry:OpPerf:MsnStatistics | 4000
141 | 2022-04-28 09:19:34.8930000 | fluid:telemetry:Batching:LengthTooBig |  
142 | 2022-04-28 09:19:37.1460000 | fluid:telemetry:OdspDriver:CacheOpsLimitHit |  
143 | 2022-04-28 09:19:37.2040000 | fluid:telemetry:OpPerf:MsnStatistics | 5000
144 | 2022-04-28 09:19:37.3410000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  
145 | 2022-04-28 09:19:38.4140000 | fluid:telemetry:OpPerf:MsnStatistics | 6000
146 | 2022-04-28 09:19:38.5830000 | fluid:telemetry:Batching:LengthTooBig |  
147 | 2022-04-28 09:19:44.7700000 | fluid:telemetry:OpPerf:MsnStatistics | 7000
148 | 2022-04-28 09:19:47.8600000 | fluid:telemetry:OpPerf:MsnStatistics | 8000
149 | 2022-04-28 09:19:49.8450000 | fluid:telemetry:Batching:LengthTooBig |  
150 | 2022-04-28 09:19:50.6410000 | fluid:telemetry:OrderedClientElection:ElectedClientNotSummarizing |  
151 | 2022-04-28 09:19:50.6430000 | fluid:telemetry:SummaryStatus:Behind |  
152 | 2022-04-28 09:19:50.8190000 | fluid:telemetry:SummaryStatus:CaughtUp |  
153 | 2022-04-28 09:19:50.8930000 | fluid:telemetry:OpPerf:MsnStatistics | 9000
154 | 2022-04-28 09:19:51.0470000 | fluid:telemetry:Batching:LengthTooBig |  
155 | 2022-04-28 09:19:51.4280000 | fluid:telemetry:Batching:LengthTooBig |  
156 | 2022-04-28 09:19:52.4040000 | fluid:telemetry:OpPerf:MsnStatistics | 10000
157 | 2022-04-28 09:19:53.5330000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  
158 | 2022-04-28 09:19:55.7580000 | fluid:telemetry:OpPerf:MsnStatistics | 11000
159 | 2022-04-28 09:19:56.5510000 | fluid:telemetry:Batching:LengthTooBig |  
160 | 2022-04-28 09:19:56.5520000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  
161 | 2022-04-28 09:20:07.0450000 | fluid:telemetry:OpPerf:MsnStatistics | 12000
162 | 2022-04-28 09:20:14.1800000 | fluid:telemetry:SummaryManager:CreatingSummarizer |  
187 | 2022-04-28 09:20:18.2350000 | fluid:telemetry:Batching:LengthTooBig |  
188 | 2022-04-28 09:20:18.2350000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  
198 | 2022-04-28 09:20:19.0740000 | fluid:telemetry:OpPerf:MsnStatistics | 13000
199 | 2022-04-28 09:20:19.2570000 | fluid:telemetry:Batching:LengthTooBig |  
200 | 2022-04-28 09:20:19.2580000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  
218 | 2022-04-28 09:20:20.8090000 | fluid:telemetry:Batching:LengthTooBig |  
219 | 2022-04-28 09:20:20.8100000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  
220 | 2022-04-28 09:20:21.5030000 | fluid:telemetry:OpPerf:MsnStatistics | 14000
221 | 2022-04-28 09:20:22.2050000 | fluid:telemetry:Batching:LengthTooBig |  
249 | 2022-04-28 09:20:24.8290000 | fluid:telemetry:Batching:LengthTooBig |  
250 | 2022-04-28 09:20:24.8290000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  
294 | 2022-04-28 09:20:30.9390000 | fluid:telemetry:OpPerf:MsnStatistics | 15000
295 | 2022-04-28 09:20:32.7340000 | fluid:telemetry:Batching:LengthTooBig |  
296 | 2022-04-28 09:20:32.7350000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  
297 | 2022-04-28 09:20:33.6410000 | fluid:telemetry:Batching:LengthTooBig |  
317 | 2022-04-28 09:20:36.2260000 | fluid:telemetry:SummaryStatus:Behind |  
318 | 2022-04-28 09:20:36.8020000 | fluid:telemetry:OpPerf:MsnStatistics | 16000
319 | 2022-04-28 09:20:38.2300000 | fluid:telemetry:Batching:LengthTooBig |  
324 | 2022-04-28 09:20:41.9010000 | fluid:telemetry:Batching:LengthTooBig |  
328 | 2022-04-28 09:20:42.4750000 | fluid:telemetry:SummaryStatus:CaughtUp |  
329 | 2022-04-28 09:20:42.9120000 | fluid:telemetry:OpPerf:MsnStatistics | 17000
330 | 2022-04-28 09:20:45.3720000 | fluid:telemetry:Batching:LengthTooBig |  
331 | 2022-04-28 09:20:45.3720000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  
333 | 2022-04-28 09:20:48.4280000 | fluid:telemetry:OpPerf:MsnStatistics | 18000
334 | 2022-04-28 09:20:48.8440000 | fluid:telemetry:Batching:LengthTooBig |  
339 | 2022-04-28 09:20:53.1770000 | fluid:telemetry:Batching:LengthTooBig |  
369 | 2022-04-28 09:21:00.3530000 | fluid:telemetry:OpPerf:MsnStatistics | 19000
370 | 2022-04-28 09:21:00.8250000 | fluid:telemetry:Batching:LengthTooBig |  
385 | 2022-04-28 09:21:02.3100000 | fluid:telemetry:Batching:LengthTooBig |  
404 | 2022-04-28 09:21:04.7100000 | fluid:telemetry:OpPerf:MsnStatistics | 20000
405 | 2022-04-28 09:21:05.7890000 | fluid:telemetry:Batching:LengthTooBig |  
720 | 2022-04-28 09:21:16.2810000 | fluid:telemetry:OpPerf:MsnStatistics | 21000
729 | 2022-04-28 09:21:18.5490000 | fluid:telemetry:Batching:Length |  
730 | 2022-04-28 09:21:27.3220000 | fluid:telemetry:Batching:LengthTooBig |  
731 | 2022-04-28 09:21:29.5530000 | fluid:telemetry:OpPerf:MsnStatistics | 22000
732 | 2022-04-28 09:21:34.4770000 | fluid:telemetry:Batching:LengthTooBig |  
737 | 2022-04-28 09:21:37.3000000 | fluid:telemetry:Batching:LengthTooBig |  
740 | 2022-04-28 09:21:42.1220000 | fluid:telemetry:OpPerf:MsnStatistics | 23000
741 | 2022-04-28 09:21:44.7460000 | fluid:telemetry:Batching:LengthTooBig |  
745 | 2022-04-28 09:21:46.7980000 | fluid:telemetry:Batching:LengthTooBig |  
749 | 2022-04-28 09:21:47.4830000 | fluid:telemetry:OpPerf:MsnStatistics | 24000
750 | 2022-04-28 09:21:47.6390000 | fluid:telemetry:Batching:LengthTooBig |  
751 | 2022-04-28 09:21:47.8600000 | fluid:telemetry:Batching:LengthTooBig |  
853 | 2022-04-28 09:21:48.5410000 | fluid:telemetry:OpPerf:MsnStatistics | 25000
854 | 2022-04-28 09:21:49.0330000 | fluid:telemetry:Batching:LengthTooBig |  
855 | 2022-04-28 09:21:49.0340000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  
872 | 2022-04-28 09:21:50.5380000 | fluid:telemetry:OpPerf:MsnStatistics | 26000
873 | 2022-04-28 09:21:50.6140000 | fluid:telemetry:Batching:LengthTooBig |  
874 | 2022-04-28 09:21:50.6150000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  
881 | 2022-04-28 09:21:51.7790000 | fluid:telemetry:Batching:LengthTooBig |  
882 | 2022-04-28 09:21:51.7800000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  
898 | 2022-04-28 09:21:55.3860000 | fluid:telemetry:OpPerf:MsnStatistics | 27000
899 | 2022-04-28 09:21:56.0320000 | fluid:telemetry:Batching:LengthTooBig |  
900 | 2022-04-28 09:21:56.0320000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  
923 | 2022-04-28 09:22:02.4430000 | fluid:telemetry:Batching:LengthTooBig |  
924 | 2022-04-28 09:22:02.4430000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  
934 | 2022-04-28 09:22:06.5350000 | fluid:telemetry:OpPerf:MsnStatistics | 28000
935 | 2022-04-28 09:22:07.0340000 | fluid:telemetry:Batching:LengthTooBig |  
936 | 2022-04-28 09:22:07.0340000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |  


		</HTML>

**Comment by vladsud** [comment]
We might be loading from old snapshot that is too behind.
Or it's possible file was not summarized for long time.
So I'd not look at how many ops clients process. I'd look at opsSinceLastSummary property on summary events (I think I got name right). And if it's high - at this summarizer session and at previous summarizer sessions to figure out why summaries were not posted frequently enough.

**Comment by NicholasCouri** [comment]
We should log the OpPerf:OpRoundTripTime more often (1000 ops seems too high). 

We were not summarizing often enough and always due to maxTime, so we were gradually having more ops to be processed, until the number became too high. 

The fact is that we should have started the summarizer with MaxOps when we got 4000 ops within 11 seconds  but it seems the **summarizer spent 1 min doing the summary + garbage collection.**    It was also getting/processing 1000 ops at the same time. 

@agarwal-navin   check it out this container "3ca1cec4-e9e8-41f6-bdd6-fd89a1990266"  between **2022-04-28 09:18:32  and 2022-04-28 09:19:36** 

union Office_Fluid_FluidRuntime_*
 | where Data_docId == "wbsuZYjqBjBQcgHGTAg1Qxhcb%2B0b%2BUSIswMorZfxIGM%3D"
| where Event_Time >= datetime(2022-04-28 09:17:24.2110000)  and Event_Time < datetime(2022-04-28 09:20:19.0740000)
| project Event_Sequence, Event_Time, Data_eventName, Data_containerId, Data_reason, Data_containerConnectionState, Data_clientType,Data_opsSinceLastSummary,
Data_opsSinceLastAck, Data_sequenceNumber, Data_from, Data_to, Data_length,  Data_samplingRate, Data_batchEndSequenceNumber, Data_lastFetch

<HTML>
		

Event_Sequence | Event_Time | Data_eventName | Data_containerId | Data_reason | Data_containerConnectionState | Data_clientType | Data_opsSinceLastSummary | Data_opsSinceLastAck | Data_sequenceNumber | Data_from | Data_to | Data_length | Data_samplingRate | Data_batchEndSequenceNumber | Data_lastFetch
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
217 | 2022-04-28 09:17:24.2110000 | fluid:telemetry:OpPerf:OpRoundtripTime | 0d3b5ad3-b710-46a3-aba5-4998bd2812fb |   | Connected | interactive |   |   | 359 |   |   |   |   |   |  
122 | 2022-04-28 09:17:25.3670000 | fluid:telemetry:Summarizer:Running:GarbageCollection_end | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer |   |   |   |   |   |   |   |   |  
123 | 2022-04-28 09:17:25.4940000 | fluid:telemetry:OdspDriver:WriteSummaryTree_GetToken_end | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer |   |   |   |   |   |   |   |   |  
124 | 2022-04-28 09:17:27.8300000 | fluid:telemetry:OdspDriver:uploadSummary_end | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer |   |   |   |   |   |   |   |   |  
125 | 2022-04-28 09:17:27.8380000 | fluid:telemetry:Summarizer:Running:Summarize_generate | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer | 359 |   |   |   |   |   |   |   |  
126 | 2022-04-28 09:17:28.0670000 | fluid:telemetry:Summarizer:Running:Summarize_Op | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer |   |   |   |   |   |   |   |   |  
127 | 2022-04-28 09:17:28.6780000 | fluid:telemetry:Summarizer:Running:Summarize_end | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer | 359 |   |   |   |   |   |   |   |  
134 | 2022-04-28 09:17:31.3170000 | fluid:telemetry:Batching:Length | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   | 3 | 1000 | 1369 |  
165 | 2022-04-28 09:18:27.9010000 | fluid:telemetry:Summarizer:Running:GarbageCollection_end | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer |   |   |   |   |   |   |   |   |  
168 | 2022-04-28 09:18:32.7650000 | fluid:telemetry:OdspDriver:uploadSummary_end | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer |   |   |   |   |   |   |   |   |  
169 | 2022-04-28 09:18:32.7910000 | fluid:telemetry:Summarizer:Running:Summarize_generate | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer | 466 |   |   |   |   |   |   |   |  
170 | 2022-04-28 09:18:33.2480000 | fluid:telemetry:Summarizer:Running:Summarize_Op | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer |   |   |   |   |   |   |   |   |  
171 | 2022-04-28 09:18:34.2250000 | fluid:telemetry:Summarizer:Running:Summarize_end | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer | 466 |   |   |   |   |   |   |   |  
228 | 2022-04-28 09:19:19.5100000 | fluid:telemetry:Batching:Length | 0d3b5ad3-b710-46a3-aba5-4998bd2812fb |   | Connected | interactive |   |   |   |   |   | 3 | 1000 | 1369 |  
167 | 2022-04-28 09:19:19.5900000 | fluid:telemetry:Batching:Length | ce6fb873-efba-4a3a-9f77-bca64b539657 |   | Connected | interactive |   |   |   |   |   | 3 | 1000 | 1369 |  
168 | 2022-04-28 09:19:20.2270000 | fluid:telemetry:OpPerf:OpRoundtripTime | ce6fb873-efba-4a3a-9f77-bca64b539657 |   | Connected | interactive |   |   | 1382 |   |   |   |   |   |  
172 | 2022-04-28 09:19:20.4510000 | fluid:telemetry:Batching:Length | ff44a850-5579-448f-a1a7-2bbe03a0ace6 |   | Connected | interactive |   |   |   |   |   | 3 | 1000 | 1369 |  
173 | 2022-04-28 09:19:20.4550000 | fluid:telemetry:Batching:Length | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer |   |   |   |   |   | 3 | 1000 | 1369 |  
136 | 2022-04-28 09:19:25.0820000 | fluid:telemetry:OpPerf:MsnStatistics | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   | 2000 |   |   |   |   |   |  
137 | 2022-04-28 09:19:31.6530000 | fluid:telemetry:OpPerf:MsnStatistics | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   | 3000 |   |   |   |   |   |  
138 | 2022-04-28 09:19:31.6660000 | fluid:telemetry:Batching:LengthTooBig | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   | 397 |   | 3003 |  
140 | 2022-04-28 09:19:34.7540000 | fluid:telemetry:OpPerf:MsnStatistics | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   | 4000 |   |   |   |   |   |  
141 | 2022-04-28 09:19:34.8930000 | fluid:telemetry:Batching:LengthTooBig | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   | 308 |   | 4163 |  
174 | 2022-04-28 09:19:35.0390000 | fluid:telemetry:Summarizer:Running:GarbageCollection_end | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer |   |   |   |   |   |   |   |   |  
175 | 2022-04-28 09:19:35.1030000 | fluid:telemetry:OdspDriver:WriteSummaryTree_GetToken_end | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer |   |   |   |   |   |   |   |   |  
176 | 2022-04-28 09:19:36.5120000 | fluid:telemetry:OdspDriver:uploadSummary_end | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer |   |   |   |   |   |   |   |   |  
177 | 2022-04-28 09:19:36.5210000 | fluid:telemetry:Summarizer:Running:Summarize_generate | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer | 752 |   |   |   |   |   |   |   |  
178 | 2022-04-28 09:19:36.7480000 | fluid:telemetry:Summarizer:Running:Summarize_Op | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer |   |   |   |   |   |   |   |   |  
142 | 2022-04-28 09:19:37.1460000 | fluid:telemetry:OdspDriver:CacheOpsLimitHit | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   |   |   |   |  
143 | 2022-04-28 09:19:37.2040000 | fluid:telemetry:OpPerf:MsnStatistics | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   | 5000 |   |   |   |   |   |  
144 | 2022-04-28 09:19:37.3410000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   |   |   |   |  
179 | 2022-04-28 09:19:37.4630000 | fluid:telemetry:Summarizer:Running:Summarize_end | 3ca1cec4-e9e8-41f6-bdd6-fd89a1990266 |   | Connected | noninteractive/summarizer | 752 |   |   |   |   |   |   |   |  
145 | 2022-04-28 09:19:38.4140000 | fluid:telemetry:OpPerf:MsnStatistics | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   | 6000 |   |   |   |   |   |  
146 | 2022-04-28 09:19:38.5830000 | fluid:telemetry:Batching:LengthTooBig | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   | 1045 |   | 6250 |  
147 | 2022-04-28 09:19:44.7700000 | fluid:telemetry:OpPerf:MsnStatistics | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   | 7000 |   |   |   |   |   |  
148 | 2022-04-28 09:19:47.8600000 | fluid:telemetry:OpPerf:MsnStatistics | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   | 8000 |   |   |   |   |   |  
149 | 2022-04-28 09:19:49.8450000 | fluid:telemetry:Batching:LengthTooBig | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   | 1352 |   | 8677 |  
150 | 2022-04-28 09:19:50.6410000 | fluid:telemetry:OrderedClientElection:ElectedClientNotSummarizing | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   |   |   |   |  
151 | 2022-04-28 09:19:50.6430000 | fluid:telemetry:SummaryStatus:Behind | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   |   |   |   |  
152 | 2022-04-28 09:19:50.8190000 | fluid:telemetry:SummaryStatus:CaughtUp | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   |   |   |   |  
153 | 2022-04-28 09:19:50.8930000 | fluid:telemetry:OpPerf:MsnStatistics | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   | 9000 |   |   |   |   |   |  
154 | 2022-04-28 09:19:51.0470000 | fluid:telemetry:Batching:LengthTooBig | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   | 451 |   | 9308 |  
155 | 2022-04-28 09:19:51.4280000 | fluid:telemetry:Batching:LengthTooBig | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   | 307 |   | 9695 |  
156 | 2022-04-28 09:19:52.4040000 | fluid:telemetry:OpPerf:MsnStatistics | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   | 10000 |   |   |   |   |   |  
157 | 2022-04-28 09:19:53.5330000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   |   |   |   |  
158 | 2022-04-28 09:19:55.7580000 | fluid:telemetry:OpPerf:MsnStatistics | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   | 11000 |   |   |   |   |   |  
159 | 2022-04-28 09:19:56.5510000 | fluid:telemetry:Batching:LengthTooBig | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   | 217 |   | 11344 |  
160 | 2022-04-28 09:19:56.5520000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   |   |   |   |  
161 | 2022-04-28 09:20:07.0450000 | fluid:telemetry:OpPerf:MsnStatistics | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   | 12000 |   |   |   |   |   |  
162 | 2022-04-28 09:20:14.1800000 | fluid:telemetry:SummaryManager:CreatingSummarizer | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   | 3148 |   |   |   |   |   |   |  
187 | 2022-04-28 09:20:18.2350000 | fluid:telemetry:Batching:LengthTooBig | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   | 485 |   | 12525 |  
188 | 2022-04-28 09:20:18.2350000 | fluid:telemetry:OpPerf:GetDeltas_OpProcessing | 010ce3e6-567c-43e3-a74f-5ad96595b5d9 |   | Connected | interactive |   |   |   |   |   |   |   |   |  


		</HTML>



Note: We should definetely log the current value of maxOps once we move it down to 100 and the other config settings.

**Comment by NicholasCouri** [comment]
@agarwal-navin @vladsud  - it ends up the scriptor is actually generating 6000 ops in less than 1 min.  Here is the threads: 
[Teams Thread 6000 ops in less than 1 min](https://teams.microsoft.com/l/message/19:2659233c259b4ce38a069bd017e71e8c@thread.skype/1651701755349?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=422665a0-7ad3-4d0d-9171-e8881d0397d9&parentMessageId=1651701755349&teamName=FFX%20(Fluid%20Framework%20and%20Experiences)&channelName=Scriptor%20%E2%9C%8F&createdTime=1651701755349)
[There is also this thread with Tony where the correlation Id is the interesting piece to find it out.](https://teams.microsoft.com/l/message/19:50292e8934024fc19d6ca2080dd7681e@thread.skype/1651698088632?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=9ce27575-2f82-4689-abdb-bcff07e8063b&parentMessageId=1651698088632&teamName=Fluid%20Framework%20(Prague)&channelName=Dev&createdTime=1651698088632) 

I will investigate other documents from this list now and will try to reproduce it according to the suggestion I got on the thread.

**Comment by NicholasCouri** [comment]
@vladsud @agarwal-navin   same goes for this other document: 
/////////    Data_docId == "6C1zgr1R5wSOJuzU%2FF9lPUrxuH6%2Fnmcr0WMR9MlzyiE%3D"
// notice Event_Sequence 436 and 760  // datetime(2022-04-29 07:35:07.6570000)  and  datetime(2022-04-29 07:36:16.1740000)
// notice Event_sequence 822 and 1134 // datetime(2022-04-29 07:36:35.7470000) , datetime(2022-04-29 07:37:47.1960000)
union Office_Fluid_*
  | where Data_hostCorrelationId == "2364ac1f-c736-4310-a310-a6798ff81aa3"
| project-reorder Event_Sequence, Event_Time, Data_eventName, Data_containerId, Data_duration,  Data_reason, Data_error, Data_containerConnectionState, Data_clientType,Data_opsSinceLastSummary,
Data_opsSinceLastAck, Data_sequenceNumber, Data_length,  Data_samplingRate, Data_batchEndSequenceNumber, Data_lastFetch 

First interval (Sequence 437- 760 - 1 min and 9 secs): 
1x TableCellToCellPaste
104x CreateComponent
1x GetTableData
100x ScriptorLoadModelString
100x ScriptorComponentLoadRender

Second interval (Sequence 823 - 1132 - 1 min and 12 secs)
1xAttributionFloatie
1xTableCellToCellPaste
104x CreateComponent
1x GetTableData
100x ScriptorLoadModelString
100x ScriptorComponentLoadRender

According to the scriptor dev, we could easily repro it copying and paste a table with 100 items. 

</BODY></HTML>

**Comment by NicholasCouri** [comment]
I just did a small test with the table and I could easily reach 1000 ops. 
union Office_Fluid_FluidRuntime_*
| where Data_eventName == "fluid:telemetry:Summarizer:Running:Summarize_generate"
| where Event_Time > ago(7d)
| where Data_opsSinceLastSummary > 800
| where Data_docId == "nMoTKbpNjMldtbPjryPbv6q2g4ZwwMbXecTmVmA%2FKYI%3D"
| project Data_docId, Data_opsSinceLastSummary

If there are 2+ people editing a file, it should be easy to reach 2000+

I believe dropping the MaxOps down to 100 would help it - unless All the ops are launched at once, which I don't think it is. 
Another problem is due to the fact that 1000 ops is also the limit on the ODSP side to cancel the connection (socket.io (disconnect): transport close) - I will confirm with Vlad.  
So either way, my instinct with these active problems would be to ask Marcelo to drop the default Max ops from 1000 to 100 to see if it would still happen. 

Note that I plan on doing a test using one of the end-to-end tests in such a way that will allow me to automatically add 1000 ops to see if I can easily repro it locally.

**Comment by NicholasCouri** [comment]
We'll keep on tracking [here](https://dev.azure.com/fluidframework/internal/_workitems/edit/218)

**Comment by vladsud** [comment]
I'd suggest to splitting issue (if required) and tracking different problems in different bugs.
Changing maxOps from 1000 to 100 will only help in scenarios where we already observer summaries to have that many ops (100...1000). Any case where we have over 1K ops suggest one of the multiple things
1. A batch contains that many ops. Unlikely, as at 2K ops at 500 bytes /op, we are hitting 1Mb limit, so we should not see 5K ops in a batch (graph above suggests we sometimes have that many ops in a summary)
2. We have a bug and not starting to summarize sooner
3. It's possible that previous summary took so long, that we accumulated a lot of ops. We should investigate why summary generation takes so long (and track it as separate bug).

maxTime should not impact it - once we hit a limit, we should start summary either way.


We should track separately why FFX generates that many ops.

OpRoundTripTime is tracking latencies, we should not use it to track number of ops (at least not directly). I think once in 1K ops is fine for that (at least we get enough data for what it's for).
