### ISSUE TITLE
False member size

### ISSUE THREAD

**Issue by zubeirtech** [microsoft/FluidFramework#11304]
## Describe the bug
When getting the member size using services 'memberChanged' listener and getMembers() it always returns the wrong audience size. For example, when opening a new session, it will return member size of 1 but when refreshing the page the member size changes to 2.

Here is a video that briefly shows the issue.
https://user-images.githubusercontent.com/38444073/181252875-309c5722-932a-46a9-81d0-ce2a0e22d0bf.mp4

This also occurs when opening new tabs to introduce more audience members.

Fluid Framework 1.2.2
Fluid Framework Tinylicious 1.2.2

I am using react 18.2.0 with CRA

### To Reproduce
1.  Setup membersChanged listener
2.  Render or log the current member size
3.  Reload the page or create more tabs to increase member size. 

### Expected behavior
If there is only 1 connected client/audience member then the getMembers() should only return 1 even when reloading the page and when opening more tabs then the getMembers() should return the amount of actual audience members

**Comment by zubeirtech** [comment]
Closing this issue, after debugging and researching I found out that the useEffect hook was called twice instead of once. That was caused because React.StrictMode was enabled. It works now after disabling StrictMode

**Comment by rsommerfeld** [comment]
I had basically the same problem, but found another solution that fixes it. Since this was pretty far up the google search results, I'm appending the solution here:

The issue seems to be, that sometimes during reload (or in my case, during react hot reload) a new container connection is opened. However, the old container connection is never ended. Thus, two active connections. The solution I found, is to return a dismounting function that disconnects the client.


```
  React.useEffect(() => {
    let container, services;
    (async () => {
      const out = await getContainerAndServices();
      container = out[0];
      services = out[1];
      console.log("Found " + services.audience.getMembers().size+ " connections");

      // other code, such as using the data from the container
    })();

    return () => {
      if (container != null) container.disconnect();
    };
  }, []);
```

React hot reloading (changing relevant code in the useEffect hook) now works without accumulating additional connections. I never had issues with doing a full page reload though.
