### ISSUE TITLE
understand and rationalize com link usage

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#1332]

**Comment by heliocliu** [comment]
I took a look at what Bohemia was doing here and they're just setting properties on the IFrame window directly instead of using a postMessage wrapper.  Some quick experimentation suggests this would work for us as well (and I think is a bit easier to conceptualize over something like comlink assuming we expose methods on the window at epected points along iframe creation/init)

**Comment by anthony-murphy** [comment]
agreed. like i've mentioned before i'd like to see this generalized so that it's not couples to browser and post message and we can use it for cross process in node, etc.
