### ISSUE TITLE
SharedTree: API discussion

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#13331]
GH issue for discussing possible refinements of the SharedTree API.

**Comment by CraigMacomber** [comment]
# Parent/Path Access
Would be nice to be able to get the parent field from an EditableTree node, and to get parent node from a field (undefined if a detached field)

# API control via schema metadata

Allow setting primary fields and primitive nodes via metadata in the schema instead of inferring it from the lack of other fields/values.

In the future this could also be extended to also an optional factory function for an alternative type which could get instantiated instead of editable tree nodes and put in the tree if accessed using the unwrapping API.
