### ISSUE TITLE
Support upload of any binary content of the blob during the initial summary upload at routerlicious driver.

### ISSUE THREAD

**Issue by milanro** [microsoft/FluidFramework#15969]
### Description 

The standard way of uploading summary object at the client is passing through the method `ISummaryUploadManager.writeSummaryTree` which receives the `ISummaryTree` summary object. There are two implementations of the upload manager, `SummaryTreeUploadManager` and `WholeSummaryUploadManager` which convert the `ISummaryTree` object into the transferable summary data. 

We will focus on  `WholeSummaryUploadManager` processing:

- The complete processing described bellow is performed on client
- `ISummaryTree` is converted into `IWholeSummaryPayload` object
- `ISummaryBlob`  subnodes are converted to `IWholeSummaryBlob` nodes of `IWholeSummaryPayload` 
- `ISummaryBlob` does not contain encoding attribute because it is not relevant, it is obvious whether content is the string or binary
- `IWholeSummaryBlob` ontains the string content and the encoding
-  If it is converted from the binary content, the encoding is `base64`, if it comes from string, the encoding is `utf-8`
- After the conversion, the `IWholeSummaryPayload`  is uploaded to `/git/summaries` via `GitManager` and `Historian` call.

There is one exception to this processing. The initial summary, when the container is created, is not following the path through the upload manager / `GitManager` / `Historian`. It is processed directly at the `RouterliciousDocumentServiceFactory` of the routerlicious driver.

- The processing is partially done on the client and on the service
- `RouterliciousDocumentServiceFactory.createContainer` method receives via argument the `ISummaryTree` object
- It extracts the appSummary which is `ISummaryTree` object
- `ISummaryTree` object contains `ISummaryBlob` subnodes
- `ISummaryBlob`  contains content which can be either string or binary
- Binary content cannot be uploaded to the service, the conversion is needed.
- Function `convertSummaryToCreateNewSummary` traverses the `ISummaryTree`  and encodes the `ISummaryBlob`  binary content into string using 'utf-8' encoding. **This is wrong because it works only in case, the original binary content is utf-8 compatible.**
- The ISummaryTree with converted blob contents is uploaded to `/documents/${tenantId}` endpoint (which is different from standard summary upload).
- The service code at that endpoint calls `ISummaryUploadManager.writeSummaryTree`  and converts the `ISummaryTree` to the transferable summary data, this conversion in case of initial summary is performed on the service side (comparing to standard upload which is performed at client side).

We want to introduce compression of the summaries. Compression produces the non-utf-8 compatible binary code in place of `ISummaryBlob` content. The initial summary upload produces invalid string from the binary content.

We need to be able to preserve the encoding information when we upload `ISummaryTree` of the initial summary and the service code needs to work with that information. One possibility is

- Convert the appSummary at the `RouterliciousDocumentServiceFactory` into the transfer summary object where the blob will contain encoding beside the string content (where the content will be base64 encoded string in case the original content was binary)
- Reconstruct the appSummary ISummaryTree object at the `/documents/${tenantId}` service endpoint so that it will contain binary content if the original content was binary. The current code of `/documents/${tenantId}` should then be able to work with that ISummaryTree

### Recapitulation

- Standard summary upload converts the `ISummaryTree` / `ISummaryBlob` objects into transferable data (binary content converted to base-64 encoded string and attributed by encoding) on the client side within the routerlicious driver.
- Initial summary upload does not perform conversion on the client side but on the service side at `/documents/${tenantId} ` endpoint
- The transfer to `/documents/${tenantId}` endpoint does not accept binary content at the ISummaryBlob objects
- The binary content of `ISummaryBlob` is converted prior uploading at `convertSummaryToCreateNewSummary` located at `createNewUtils.ts`
- **The conversion of binary content is done by utf-8 encoding. The non-utf-8 binary content produces erroneous output.**
- There is a need to support encoding of the binary content by base64 , upload that encoding information together with the blob content and reconstruct the original content on the service side.

#### Initial Summary Upload
- packages/drivers/routerlicious-driver/src/documentServiceFactory.ts (RouterliciousDocumentServiceFactory)
- packages/drivers/routerlicious-driver/src/createNewUtils.ts

#### Initial summary endpoint and service code
- server/routerlicious/packages/services-shared/src/storage.ts (DocumentStorage)
- server/routerlicious/packages/routerlicious-base/src/alfred/routes/api/documents.ts

 
@vladsud @DLehenbauer @dstanesc  This is the initial issue for fixing the Initial Summary upload at the routerlicious driver so that it will support the binary content.

**Comment by DLehenbauer** [comment]
Here are the options we've considered so far:

* Adding an encoding field to ISummaryTree/ISummaryBlob.
* Changing the document creation endpoint to use whole document summaries.
* Using an empty initial document on creation (like ODSP).

**Option 1: ISummaryBlob.encoding**
The smallest change would be to add an optional encoding field to ISummaryBlob to differentiate between a utf-8 encoded string and a base64 encoded Uint8Array.

However, the root cause of this bug is arguably that it is incorrect to uses ISummaryTree as a wire format.  When support for Uint8Array blobs was introduced, ISummaryTree began requiring an encoding step prior to serialization.  It is dubious that encoding an ISummaryTree yields an ISummaryTree (see convertSummaryToCreateNewSummary).

The technically correct fix is to use distinct formats for decoded summaries and encoded summaries, which brings us to the next option:

**Option 2: IWholeSummaryTree**
FRS's historian endpoint already uses a distinct format for encoded summaries, which does correctly preserve encodings (see convertSummaryTreeToWholeSummaryTree).  Ideally, we would use the same format for document creation as well.  This however is likely to be nuanced and requires more design/investigation.

One reason is that the Routerlicious driver/Historian service communicated via GitHub's public REST API, which made it possible to use GitHub as a storage service (either directly or via Historian) using "shredded summaries".  To improve efficiency, FRS later introduced the "whole summary" protocol, which extends the GitHub public REST API with the new '/summaries/' route for bulk operations (see 'enableWholeSummaryUpload').

One complication is that Tinylicious and the default configuration of Routerlicious continue to use shredded summaries.  Research is needed to understand if these would also need to be converted to use whole summary uploads.

** Option 3: Empty document**
This option would modify the creation flow to first initialize storage with an empty document, followed by an upload using the normal (whole document summary) path.  It's non-ideal in that it introduces an extra round-trip through the service but is nice in that it unifies the document creation and summary upload paths.  Possibly the impact is negligible, given that it's used by the ODSP driver.

**Comment by DLehenbauer** [comment]
Note: There is pending work to investigate combining monorepos, which would make it easier to share the "whole summaries" implementation between Historian, GitRest, and Tinylicious without duplication.

**Comment by dstanesc** [comment]
Option 3 appears natural as simplifies summary transmission. Conceptually `createContainer` covers the need of acquiring/generating the unique container identity (which in theory could be accomplished in different ways, hence optimizable in the future). In any case in the container lifecycle the referred extra round-trip is a one-time penalty not larger than the network latency. Supporting this proposal.

**Comment by NicholasCouri** [comment]
@jatgarg, can you confirm impact of #3? Does ODSP still make use of the extra round-trip? I might be missing something bug

**Comment by jatgarg** [comment]
Currently odsp only uses single round trip to create container on attach and upload the summary in same network call. Only in case of attachment blobs, it first creates an empty file and then upload the summary in a separate call. Double network call could impact perf in this case. Just handling the blob conversion properly which is specified as Option 1 could serve our purpose with lesser changes?

**Comment by DLehenbauer** [comment]
Confirm fixed.  Tinylicious tracked by #17438.
