### ISSUE TITLE
Promote dirty document signal to loader/runtime

### ISSUE THREAD

**Issue by ruchika-m** [microsoft/FluidFramework#1876]
## Feature
With the recent data loss issues we observed, there was an ask to make use of the dirtyDocument signal that exists today in runtime to prompt users when exiting a page that has changes that haven't been pushed through. However the signal isn't a high level property that everybody can access. The Preview app does some hacky stuff like so,

> (container as any).context.runtime.dirtyDocument

**Describe the solution you'd like**
Instead of trying to access the signal as the app does today(which is also not suitable for other UI hosts when they plan to implement similar behavior) on the container.context.runtime, can we promote the signal to a layer that the host apps have direct access to?

**Comment by leeviana** [comment]
I really think we need to reevalute this request. We're getting requests from partner container experiences/hosts to read this flag in a generic way and I don't think it's sustainable - or a good contract - to tell everyone they need to architect their containers in such a way to always return a container API with a manually implemented dirty contract (which is difficult because components don't have access to the containerRuntime) on '/' and that all hosts have to request both the component and the separate top level container API component to use alongside ExternalContainer.ts in order to do a dirty feature detection on '/'. And if it doesn't exist then user's lose ops. 

@vladsud when you mention different scenarios/needs for this API, I think it's a _host_ decision what to do with documentDirty, not a container/component decision. And hosts fully expect this on top level container API. Whether they use the flag or not is up to them but having every container try to manually manage this containerRuntime relationship is a nightmare so far.
