### ISSUE TITLE
Issue at container connection : Provided user was not an "AzureUser"

### ISSUE THREAD

**Issue by erbox02000** [microsoft/FluidFramework#20159]
## Describe the bug

We have integrated fluid framework into our platform, as soon as 2 different users try to connect the same container id, we get an error at the getContainer level : Provided user was not an "AzureUser". 

We are using an Azure Fluid Relay and the InsecureTokenProvider.

Our front-end is based on Angular v16 and we are using :
- fluid-framework: 2.0.0-rc.1.0.3
- fluid-experimental/data-objects: 2.0.0-rc.1.0.3
- fluidframework/azure-client: 2.0.0-rc.1.0.3
- fluidframework/test-runtime-utils: 2.0.0-rc.1.0.3

![image](https://github.com/microsoft/FluidFramework/assets/148437970/5d212352-7f63-46b2-9c21-e90e4fad9087)

![image](https://github.com/microsoft/FluidFramework/assets/148437970/1e75d591-6c26-4d8e-ac86-2d7b02a49917)

![image](https://github.com/microsoft/FluidFramework/assets/148437970/3c5ab29a-4f59-44b9-b7e3-2c171e038b0e)

### To Reproduce

To reproduce this issue, we only have to connect the same container with 2 different accounts and sometimes with the same account on different chrome tabs.

### Expected behavior

It's obvious, but be able to have multiple users connected to the same container.

**Comment by pk-pranshu** [comment]
A recent change in FRS caused the id and name fields of the IUser to be removed from the quorumMembers snapshot. 
1.x clients are generally unaffected, since the Audience was always completely recreated from initialClients. This meant the faulty quorumMembers were never seen by the ServiceAudience. In 2.x the Audience now retains the quorumMembers (as of [#12094](https://github.com/microsoft/FluidFramework/pull/12094)), so the ServiceAudience does see these faulty members and hits these asserts.
We have made changes [#20131](https://github.com/microsoft/FluidFramework/pull/20131) as a minimal mitigation to unblock load on 2.x clients while the service-side fix is made. Once the fix is in, we'll restore these checks to their stronger form.

Please try the release [Fluid Framework v2.0.0-rc.2.0.0](https://github.com/microsoft/FluidFramework/releases/tag/client_v2.0.0-rc.2.0.0) and let us know if you see any issues.
