### ISSUE TITLE
Determine which container a data store belongs too

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#2200]
## Feature
When loading a data store by url in the context of a container the loading container wants to know if that loaded data store belongs to it's container, or another container in order to influence thing like copy-paste, and display

**Comment by danielroney** [comment]
Per discussion at milestone planning, moving un-projected issues to Next.

**Comment by vladsud** [comment]
Pretty old item, would be great to at least move forward with full proposal, or punt.

I believe the problem is about how to deal with references (URIs) on clipboard and similar scenarios, where there is a need to encode reference to an object and resolve it in some container.

Can there be extra info on the clipboard to answer this question? Like document ID?
That said, does docId reflect ODSP versions / preservation files? I.e. does it change to reflect unique "file"? If not, that's a but on its own that needs to be fixed.
