### ISSUE TITLE
Avoid multiple dirty->clean->dirty transition event sent on processing ops after reconnection

### ISSUE THREAD

**Issue by sumedhb1995** [microsoft/FluidFramework#2724]
Currently, when we reconnect and we have pending ops, we clean the dirty flags (in case we don't need to resend anything) causing extra transitions.  We should avoid those event since logically, the document didn't really get saved in between.

**Comment by curtisman** [comment]
This is because of this [line](https://github.com/microsoft/FluidFramework/blob/996ca43d1ed0938022903f3eed1fff18afda37e8/packages/runtime/container-runtime/src/containerRuntime.ts#L1125)

There are test that asserts this behavior. 
@agarwal-navin  Is this by design?
@sumedhb1995 In what context is this raise?  Trying to understand why we need to fix this.

**Comment by agarwal-navin** [comment]
This is by design, yes. When the Container is reconnected, there may be some unack'd ops. The container runtime asks the DDSes to resubmit these ops. However, it has no idea what the DDSes are going to do so it marks the document as clean. If the DDSes resubmits ops, the document will be set back to dirty.

If we don't set the document dirty to false in the mentioned line, then consider this scenario: Before container got disconnected, there were some unack'd ops - the document is dirty. After the container reconnects, only one op is left unack'd - document is still dirty. Container runtime asks DDS to resubmit this op but the DDS decides that its not valid anymore, so it does not submit it again. The document will be left in a dirty state now even though all ops have been ack'd.

**Comment by curtisman** [comment]
Sure. But the question is more about what the user see and can we change that (where it only emit one state change from "dirty" -> "clean" in your scenario) and it doesn't emit anything if it is from "dirty" -> "dirty" on reconnect which logically matches what it means, where it was dirty before and and it is still dirty after reconnect (instead of dirty -> clean-> dirty).  It feels like the intermediary "clean" are internal only, and the document didn't really get to a clean state at that moment.

**Comment by agarwal-navin** [comment]
I agree. The intermediary state can be removed. I am sure we can come up with a solution.
Should we change this issue to track that? Or file a separate one?
