### ISSUE TITLE
Implement "safe" summary mode for DDSs

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3331]
If DDS factory registration is removed from data store, then DDS will fail to summarize, causing "safe" summary at data store level.
We can do better and push safe summary down to DDS level in such cases, improving perf. Without that, failure at that level will result in data store to always using safe summaries, and very quickly - very slow perf.

**Comment by arinwt** [comment]
Created a branch with the core work done: `dds-failure-summary` as a baseline in the future when we want to implement this.

It takes care of the following:
- Enable failure summaries in SummarizerNodes at DDS level
- Call loadBaseSummary when loading base snapshots at DDS level
- Change DDS op handling from `invalidate` to `recordChange` to track ops

Holding off for now, since the work to consolidate op storage is not done and is nontrivial.
- perf: move op storage to leaf SummarizerNodes or to root node with readdressing to prevent duplicating op tracking

**Comment by vladsud** [comment]
I believe this is a punt. Mostly because we learned the hard way that going too far with this approach makes things worse - system limps along, but perf starts going down quickly, and complexity is too high, making more room for errors.
@arinwt - please reactivate if you disagree.
