### ISSUE TITLE
Fluidframework.com/playground double scroll bar

### ISSUE THREAD

**Issue by curtisman** [microsoft/FluidFramework#3589]
The Fluid playground canvas has scroll bar and then the footer for the web forces the browser to have a scroll bar too.

**Comment by micahgodbolt** [comment]
This appears to be caused by the overflow-y: scroll on the html tag

![image](https://user-images.githubusercontent.com/1434956/92758297-6a4cd500-f343-11ea-8cc9-e2a31de7f82e.png)


and the lack of fixed height on the overflow body tag

![image](https://user-images.githubusercontent.com/1434956/92758402-894b6700-f343-11ea-8358-259ae8add7ac.png)

Change those 2 things and you've got scrolling only on the inner canvas. 

Followup item: add scrolling to left navigation to ensure that it can also scroll if window is less than ~700px tall

**Comment by tylerbutler** [comment]
Triage: post launch "cleanup" bucket? Within the next week.

**Comment by tylerbutler** [comment]
@micahgodbolt This was resolved already, right?

**Comment by micahgodbolt** [comment]
Yes, sorry. It got moved to the storybook code. So this issue is resolved.
