### ISSUE TITLE
Scenarios to use DDSes aren't documented

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#3711]
### Issue Category
- Can't find an answer to a specific question

One of the first questions often field from partners working with FluidObjects is which DDS is appropriate for their scenario, what are the pros/cons merge strategies, how to use them... etc.

I see there are equivalent documentation issues opened for specific DDSes that I've noticed are not documented well but I think there's also a strong need for a high level "which DDS should I pick" scenario page with some of this information.

**Comment by vladsud** [comment]
@tylerbutler , I believe one of your latest PRs did an overview of DDS and might be good way to resolve it.
@leeviana - if I step back, the question is similar to "what JS object I can use for my scenario?" And I think there is no way to write a doc like that :) I feel like we need all the primitives, grouped by types (i.e. one type - DDS), and maybe some samples / educational articles?

**Comment by leeviana** [comment]
Yeah, that would be a good start, at least a place someone can go to for a list of primitives would be a good starting point for pointing people towards.

**Comment by vladsud** [comment]
https://github.com/microsoft/FluidFramework/blob/main/docs/content/docs/advanced/dds-anatomy.md
https://github.com/microsoft/FluidFramework/blob/main/docs/content/docs/data-structures/overview.md
https://github.com/microsoft/FluidFramework/blob/main/docs/content/docs/concepts/dds.md

I even found "Picking the right data structure" title in last doc!

@tylerbutler , content looks broken at end of dds.ms.

Should we close this issue? We should continue to improve docs (thanks Tyler!), but this issue seems like addressed.

**Comment by leeviana** [comment]
Yes this looks good to me! It's a little weird to me that there is an "introducing DDS" page in the "concepts" bucket (but not in the DDS bucket) here: https://fluidframework.com/docs/concepts/dds/ and then an "overview of DDSes" here: https://fluidframework.com/docs/data-structures/overview/

Maybe some restructuring or at least linking between the pages would be beneficial?

**Comment by vladsud** [comment]
@tylerbutler - would appreciate if you can follow up here and we can resolve it

**Comment by tylerbutler** [comment]
> Maybe some restructuring or at least linking between the pages would be beneficial?

Agreed. We'll track that cleanup separately, so I'll go ahead and close this.
