### ISSUE TITLE
NullRuntime should be removed from repo

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3738]
And all workflows that rely on it should be fixed (likely by forking new work items).
In particular, Replay tool does not work properly - it should not support running from ops, and should always start with snapshot (--from argument).

Would appreciate help here with cleanup!

**Comment by curtisman** [comment]
This means deprecating the old code proposal flow, and only used detached container flow, which make sense.
I think @tanviraumi had some objection to this before?

**Comment by tanviraumi** [comment]
My main motivation was testing the service. Because we create a snapshot first, the ordering service becomes secondary. So if creation of snapshot fails, I have no easy way to test the container + driver + service.

I remember @vladsud mentioned faking the snapshot creation inside a test driver? That flow will actually be sufficient for my specific use case.
