### ISSUE TITLE
Replay tool should not require hardcoded list of data store factory keys.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3739]
~~At minimum, this list needs to be updated:
https://github.com/microsoft/FluidFramework/blob/main/packages/tools/replay-tool/src/replayMessages.ts#L312~~
^^ _This is fixed by PR https://github.com/microsoft/FluidFramework/pull/4161_

better - we figure out the plan that allows us to stop adding type IDs  for Fluid Preview app.

**Comment by markfields** [comment]
The problem here is that as-is in [replayMessages.ts](https://github.com/microsoft/FluidFramework/blob/main/packages/tools/replay-tool/src/replayMessages.ts#L312) you need to fake the DataStore registry with keys matching all the DataStores you may find in the files we are debugging.

Curtis says: "it doesn't need to be a map, just maplike"

So that's promising...
