### ISSUE TITLE
Summarizer may be processing ops while summarizing

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3797]
Investigate potential issue with ops being processed while summarizing:

We found the summary at sequence `n` contained a DDS that was attached at sequence `n + k` where `k > 0`. It shouldn't be possible for the summary to contain the DDS before it is attached. Already verified that the summarizer client was not the client which attached the DDS.

Can we add telemetry and fail-fast to make sure if it were to happen, we just fail summary, report it, but do not commit it?

**Comment by arinwt** [comment]
Further research shows that this is likely an issue with "failure" summary.

Found that the DDS in question was in the nested `_baseSummary` tree, but also the attach op for it was in the `_outstandingOps` blob, _and_ the outer `_outstandingOps` blob.

Because both outstanding ops blobs had the same 2 ops in them, it indicates a problem with the op tracking and SummarizerNode. It could also be a problem with the outstanding ops blobs content being overwritten.

**Comment by vladsud** [comment]
Should it be back ported to earlier versions?
The only reason I'm asking is that in 0.26 integration branch I saw some code that provided empty data store factories for old components that in practice would not work (as their were not registering DDS factories). So I see two ways out of it - either create proper "empty-shell" factory, or just remove it and rely on "safe" summary. But later likely needs this fix.

**Comment by arinwt** [comment]
I was thinking to at least back-port to at least 0.27.  I guess if missing factories are there, it should go to 0.26.
