### ISSUE TITLE
DataObject: Deprecate Container Services

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#3799]
The `ContainerServices` code in Aqueduct that is no longer being consumed and has been replaced by the Providers pattern.

This code needs to be removed.

**Comment by danielroney** [comment]
Per discussion at October milestone planning, I'm moving un-projected issues out to Next. This should get picked up in a Refactor effort in the near future.

**Comment by leeviana** [comment]
Was about to create an issue to start this conversation, good timing. I believe the last time I talked with Vlad he told me that we can't switch over to the provider pattern just yet because the current pattern expects injections from the scope level only and there's more work required before we can migrate. Can we get clarity on this and the timeline here? :)

**Comment by skylerjokiel** [comment]
@leeviana , Coming in later here but I don't fully get your question. Seems like Justin has taken point on starting the Providers integration. Is there something clearly blocking here?

**Comment by leeviana** [comment]
I just talked with justin and noticed that the "scope" object dependency Vlad was talking about really is just for getting the dependency global but any level can register things. Based on the code I saw, I believe we're unblocked, hopefully for some good progress here soon! :D
