### ISSUE TITLE
"msn moves backwards" error after resuming from laptop sleep

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#3840]
Dan is observing that when opening his laptop in the morning he's getting an error banner, Ruchika has noted that there are several errors including an "msn moves backwards" error.  It does not appear that the document becomes corrupt after the issue occurs though (document works fine after a page refresh), so perhaps the issue lies in pulling down ops on reconnect instead.

**Comment by tylerbutler** [comment]
@agarwal-navin Can you investigate this high pri bug further please?

**Comment by agarwal-navin** [comment]
There is not much information in the bug to debug this. I am trying to repro this locally and there is a teams thread for this that I am following.

**Comment by agarwal-navin** [comment]
I looked at the telemetry and the op stream in Dan's document. Nothing there seems out of place. All the sequenceNumbers and minimumSequenNumbers are in order and as expected. I tried taking a look at the snapshot in the document but unfortunately sharepoint only saves the last 10 snapshots so I could not get the relevant snapshot around the time the issue was happening.

I looked at the code too but couldn't see any changes of a bug or a race that can cause this.

I suggest that we add some more telemetry when this situation happens. Particularly, the MSN / sequence# we have last seen and the MSN / sequence# in the message which is causing the assert. It might be worth including the clientId as well so we can filter out telemetry logs better.

Also, I would like to swap the order of the following asserts in DeltaManager::processInboundMessage:
```
assert(this.minSequenceNumber <= message.minimumSequenceNumber, "msn moves backwards");
assert.equal(message.sequenceNumber, this.lastProcessedSequenceNumber + 1, "non-seq seq#");
```

We should assert the sequenceNumber is sequential before asserting the MSN. Also, it is possible that the first assert is masking the second one in this bug.

**Comment by vladsud** [comment]
Please take a look at quorum assert I mentioned. That's very big red flag that in the past pointed to data corruptions on server side. That, combined with msn assert suggests me that PUSH screwed up. We need to find clientId for these cases and get Gary on the line to look into what happened on ordering server (PUSH) side. It's very likely they lost ops. I.e. they were re transmitted on the wire, but eventually doc session was closed without ops being pushed to storage, and some new clients that would join would see only past, but existing clients on the wire would freak out.

Duplicate ops is also very big red flag here, potentially indicating that ops were not actually duplicated, these are new ops using old sequence numbers. We need to think on how to detect that case on the client. I.e. save enough traits about the past such that client can immediately recognize that server was rolled back and current session is a lie.

**Comment by markfields** [comment]
> swap the order of the following asserts

Even better, compute both checks before asserting, and log both results in the assert.

**Comment by agarwal-navin** [comment]
Kutso web query I ran to get the list of documents with this issue and the list of docIds:
union withsource=Office_Fluid_FluidRuntime*
| where Data_error == "msn moves backwards"
| summarize count() by Data_eventName, Data_docId, Data_error, Data_clientId

RWE9CUiRVJ6b0yrWRf%2BkZN4py6Q%2F5wDRK5YrMpin130%3D
6XsM25vSUA92gqH1Sil8WeEtmA9VtlDmTtvuW5IwAsk%3D
PoQskiQVQa0p%2BT%2B9Avs64NHoRmwjpRVjkc9CsrtWZ4Q%3D
VN7xOIyKF%2FyyK%2BKoFjLU8cwHuMf6yVoLYpYruPBf8so%3D
EhLYedIsaPtbilvhb4ug60xvfqnilysZfH53MxwAp1I%3D
LFVS5Q6Zfs5Oct6ZvCaxwM23SA3vkBvmKgAf9e69kV0%3D

**Comment by vladsud** [comment]
Errors for Dan's docID = "6XsM25vSUA92gqH1Sil8WeEtmA9VtlDmTtvuW5IwAsk%3D"
fluid:telemetry:Container:ContainerClose    this.members.has(ab80f2d7-ee86-40d0-b052-d12e59921200)
fluid:telemetry:Container:ContainerClose    msn moves backwards
 
@GaryWilber , can you please take a look at telemetry on your end? Both of these point to data loss and reversal of seq number.
Especially first one - we hit it in the past and on couple occasions it was just that - either lost ops or two parallel PUSH sessions for same doc.

Office_Fluid_FluidRuntime_Error
| where Data_docId == "6XsM25vSUA92gqH1Sil8WeEtmA9VtlDmTtvuW5IwAsk%3D"
| where Data_eventName == "fluid:telemetry:Container:ContainerClose"
| project Event_Time, Event_Sequence, Data_error, Session_Id

2020-10-02T12:45:09.899Z	663	msn moves backwards	d7e49389-55c2-45dd-aa09-bcff773a8753
2020-10-02T16:13:27.103Z	5339	this.members.has(ab80f2d7-ee86-40d0-b052-d12e59921200)	798f86c5-5797-4188-adea-2f9c31e5161d
2020-10-02T16:47:30.907Z	1772	this.members.has(ab80f2d7-ee86-40d0-b052-d12e59921200)	0ec9c8ce-da62-492c-849c-5ad89c20c0ba

ClientIDs of active connection at the time of failure:
First case - d7e49389-55c2-45dd-aa09-bcff773a8753
Second case - 798f86c5-5797-4188-adea-2f9c31e5161d
3rd case - 0ec9c8ce-da62-492c-849c-5ad89c20c0ba

**Comment by GaryWilber** [comment]
I checked the logs for that session. The session was on push v2, which helps make sense of what happened here.

This is related to what [Tanvir mentioned here](https://github.com/microsoft/FluidFramework/pull/3900#issuecomment-706711276). An ordering service that uses kafka may rebroadcast the same messages again. This never happens in push v1, so it's likely the client never saw this case before. This case can also occur when clients are using routerlicious, but I don't think that's a very well monitored scenario compared to this so it's possible we never noticed before.

Do you know if the client is equipped to handle this case? Briefly looking at the "[msn moves backwards](https://github.com/microsoft/FluidFramework/blob/16f58fc65c8b6693a04a75e2b9554656a3a47f5c/packages/loader/container-loader/src/deltaManager.ts#L1233)" code, it looks like retransmission of ops will always cause issues in the client. Tanvir mentioned the client could discard duplicate ops based on the sequence number to fix it.

Tagging @tanviraumi for visibility.

**Comment by agarwal-navin** [comment]
We already handle this in the client. DeltaManager will discard ops with duplicate sequence numbers and log a telemetry. Also, if there are gaps, it will fetch the missing ops from storage.

From the quorum logs that Vlad pointed out, it looks like the client for a client "leave" message for a client that does not exist in the quorum. This looks problematic and should not happen right.

**Comment by vladsud** [comment]
Correct, the question here - why runtime sees ops that do not make sense? They violate assumptions (quorum, or MSN moving backwards), and coupled with a lot of duplicate ops suggest that ops were actually lost and session reverted back.

**Comment by GaryWilber** [comment]
Thanks for confirming @agarwal-navin 

@vladsud Can you share the op sequence numbers that caused `msn moves backwards` and the `this.members.has` errors to occur?

In the meantime I will add additional logging on my end to log the client id for all join/leave ops.

**Comment by tanviraumi** [comment]
This is interesting. So a "leave" without a "join" is definitely a service bug which we need to fix. MSN moving backwards also falls in the same category. But how does runtime see duplicate ops? This for loop is supposed to prevent that right? (https://github.com/microsoft/FluidFramework/blob/main/packages/loader/container-loader/src/deltaManager.ts#L1150)

**Comment by vladsud** [comment]
@GaryWilber, here is an example:

Office_Fluid_FluidRuntime_Performance
| where Data_docId == "6XsM25vSUA92gqH1Sil8WeEtmA9VtlDmTtvuW5IwAsk%3D"
| where Session_Id == "798f86c5-5797-4188-adea-2f9c31e5161d"
| where Event_Sequence  >= 5320
| project Event_Time, Event_Sequence, Data_eventName, Data_reason, Data_from, Data_to, Data_sequenceNumber, Data_clientId
| order by Event_Sequence asc

Last processed seq number: 27232, suggesting that failing one is 27233.
That said, I do not think this will give us anything, as assert is based on what client believed to be wrong, the file (as it exists today) will be consistent even if ops were lost (if it happened at PUSH session granularity).

I think the most interesting thing here is to see if we telemetry on your side suggest we did not commit ops to storage and lost them somehow. In the past that happened either because there were two V1 PUSH sessions for same document, or because PUSH failed to commit ops in some window (24 hours?) and they were discarded.

Note that there are 3 sessions for this file that asserted with similar issues - this is one of them.

**Comment by GaryWilber** [comment]
There were no errors for that session. I constructed this timeline from the logs:

10-02-2020 04:22:56 - client ab80f2d7-ee86-40d0-b052-d12e59921200 joined as write
10-02-2020 04:22:57 - client d9941f3b-cefa-49e9-897b-f1d3bc6db40b joined as write (probably summary writer)
10-02-2020 04:22:57 - 27079 - join
10-02-2020 04:22:57 - 27082 - join
10-02-2020 04:24:23 - last submitted op by d9941f3b-cefa-49e9-897b-f1d3bc6db40b
10-02-2020 04:29:26 - 27230 - leave
10-02-2020 04:29:28 - last submitted op by ab80f2d7-ee86-40d0-b052-d12e59921200
10-02-2020 04:34:31 - 27232 - leave
10-02-2020 04:34:31 - 27233 - noClient - this implies no clients were left in the document after that previous leave op, which matches the join / leave count
10-02-2020 04:34:32 - client d9941f3b-cefa-49e9-897b-f1d3bc6db40b disconnected from the orderer - this was from the odsp driver sending a disconnect_document message
10-02-2020 05:15:25 - client ab80f2d7-ee86-40d0-b052-d12e59921200 disconnected from the orderer - looks like this was from the websocket being closed

Since the leave ops show up 5 minutes after the clients last submitted op, they may have been sent by deli. Deli has an idle client timer that will insert a leave message for clients that are idle for more than 5 minutes.

Could you share info about the other sessions & last processed seq numbers for this file. I'm curious if they all look similar.

**Comment by markfields** [comment]
@agarwal-navin - Is there anything more actionable in the client/runtime side here? I want to make sure this issue is tracking something meaningful in here, since it's got the OCE tag and October milestone.

**Comment by agarwal-navin** [comment]
I don't think so. I would like to add some more telemetry and logs but I think we are already tracking those separately.

**Comment by agarwal-navin** [comment]
Closing this issue.
