### ISSUE TITLE
Summaries fail when not run under https/localhost origins

### ISSUE THREAD

**Issue by kurtb** [microsoft/FluidFramework#3869]
## Describe the bug
crypto.subtle, used by hashFileBrowser.ts, is only available under secure origins (localhost is considered secure).

When running a service (r11s/tinylicious) on a local network, and connecting to a service from a secondary device, all summaries fail due to missing support.

### To Reproduce
1. start tinylicious
2. start a service pointing at gateway
3. Load a document from my-machine.local/docid?chaincode=
4. wait for summary

### Expected behavior
Lack of subtle support is detected and summaries continue to work.

### Logs
```
hashFileBrowser.js:15 Uncaught (in promise) TypeError: Cannot read property 'digest' of undefined
    at hashFile (hashFileBrowser.js:15)
    at gitHashFile (hashFileBrowser.js:34)
    at flattenCore (buildSnapshotTree.js:16)
    at flatten (buildSnapshotTree.js:65)
    at buildSnapshotTree (buildSnapshotTree.js:81)
    at ContainerRuntime.processAttachMessage (containerRuntime.js:969)
    at ContainerRuntime.process (containerRuntime.js:708)
    at ContainerContext.process (containerContext.js:155)
    at Container.processRemoteMessage (container.js:1037)
    at Object.process (container.js:919)
```

This can of course be worked around by using a reverse proxy like ngrok but this also adds quite a bit of steps to the process...

**Comment by christiango** [comment]
Ah, that's tricky. We should have a way for the consumer to decide between the bundle size penalty of a crypto library and supporting these local host scenarios.

For solutions that are on a secure context, I think leveraging the native browser APIs here would be preferable. But for Kurt's scenario, pulling down a crypto library might be ok.

**Comment by heliocliu** [comment]
Looking to dynamically load the other crypto libs when the native ones aren't available.  Looks like we already have an example of that in socketio.

**Comment by heliocliu** [comment]
So I added a way to use a hash function override in insecure contexts, so this can be set to the node implementation of our hashing function when an insecure context is detected, e.g.
```
if (crypto.subtle === undefined) {
    setInsecureContextHashFn(async (file) => {
        const engine = new shajs.sha1();
        return engine.update(file).digest("hex");
    });
}
```
This doesn't happen automatically because we didn't want to include the dependent libraries by default due to bundle size considerations.  That said, I don't know that this is something that can be set generically for the situation described here?  Setting from tinylicious wouldn't work because tinylicious isn't doing the summarization, and setting from webpack-fluid-loader doesn't work because that's a different instance of common-utils... leaving the data object/app itself?  I'll add more details to the code comments; if there's somewhere more permanent this should go I can add it there too
