### ISSUE TITLE
Remove waits from getRootDataStore / ContainerRuntime.request() APIs

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3875]
These waits are very dangerous, as they deadlock if you got URI wrong, or it's stale URI.
Instead we should use results of https://github.com/microsoft/FluidFramework/pull/3830 (once it's tested and confirmed) as a way for hosts to do initial request, and if it fails, repeat it after calling (and waiting) for this API,

**Comment by skylerjokiel** [comment]
Just want to clarify this issue here. This is to remove the ability to optimistically get a ContainerRuntime object. Not to make the call not async.

Ie. you can't request something that you think might appear. I recall this was there originally because the first few DataStore gets might require waiting for the ops to be there.

Seems like there needs to be a larger design around this and there are some related issues:

#3085
#2859
#1192
#1193

**Comment by vladsud** [comment]
Consolidating tracking of the work related to waits in #4508. Closing this issue.
