### ISSUE TITLE
Investigate removing lodash so it doesn't get downloaded by the livesite

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#3925]
Successor of #2185 

`npm run bundle-analysis:collect` will put the bundle size analysis into the artifacts folder.  lodash represents 19.39K of parsed size there.

We should:
-Investigate how much of this library is actually used within the codebase
-In the case that only a small proportion is used, we should abstract the used APIs into our own implementation into common-utils and remove our dependency on this library to reduce the bundle size.  #2450 tracked how this was done for another library.

**Comment by christiango** [comment]
+1 on this. One thing I'd like to call out is that lodash also is expensive to evaluate. 

I did a local profile of officeContainer.js's evaluation time (the code that executes right after the container is compiled + evaluated). Overall it takes about 90ms to evaluate all the modules in office container, this is mostly fluid framework code, but there is some office specific code in here. In particular, lodash clonedeep takes 13ms to evaluate

**Comment by Vivihung** [comment]
While the JavaScript standard has evolved, one could argue you don't really need lodash today.
However, before evaluating removing/replacing the entire lodash, please also spend time in checking how you import the library. By searching the code base, I found many places import the entire lodash library
```TypeScript
import _ from "lodash";
// or
import * as _ from "lodash";
```

Comparing just import the module you need.
```TypeScript
import cloneDeep from "lodash/cloneDeep";
```

The 2nd approach is better because it supports tree shaking.
Because one bad import will dramatically increase the bundle size, it is worthwhile to setup dev rules (TSLint or similar) to avoid importing the entire lodash in your source code.

To learn more details about how to correctly import lodash, here are some example posts:
e.g.
- https://dev.to/icokie/lodash-import-done-right-290n
- https://www.blazemeter.com/blog/the-correct-way-to-import-lodash-libraries-a-benchmark

**Comment by curtisman** [comment]
Currently, only `experimental/PropertyDDS` has this problem.  There are import whole of `lodash` in server only packages, which shouldn't impact client side webpack.

**Comment by christiango** [comment]
Do not deactive this issue until someone on the FF side confirms we no longer use lodash
