### ISSUE TITLE
TypedEventEmitter allows registering for non-existing events

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3930]
For example, before https://github.com/microsoft/FluidFramework/pull/3904, "error" was not described on IDocumentDeltaConnectionEvents, yet, DeltaManager was just fine registering for "error"

**Comment by anthony-murphy** [comment]
This is by design for compatibility with event emitter. If you access via the interface, IEventProvider<T> the string overload is removed for additional type safety. There is no runtime safety provided.

**Comment by vladsud** [comment]
+@ChumpChief 
I'm not sure I follow compatibility or interface parts.
If I have IDocumentDeltaConnectionEvents object at hands, what do I need to do to make sure I can't do connection.on("random stuff", listener)?
Compat across layers (loader & runtime) matters, but that seems like completely orthogonal thing (i.e. applies to any changes on interface, we can figure out how to stage changes if there is a risk of breaking existing contracts).

**Comment by ChumpChief** [comment]
You don't need to block the `.on()` call - it's ok to call `ee.on("foobar", ...)` on any event emitter.  But the emitter doesn't have to care because it knows it doesn't emit an event called "foobar".

For example, consider three classes `Emitter`, `Forwarder`, and `Consumer` where `Forwarder` listens to events from `Emitter` and rebroadcasts them to `Consumer` as we currently have with socket.io, `DocumentDeltaConnection`, and `DeltaConnection`.  Suppose `Emitter` adds a new event in an update, meaning:

1. `Forwarder` is unaware of the new event but it still becomes visible to `Consumer`, who may start taking dependencies on its behavior, effectively expanding the `Forwarder`'s public API surface without it being aware.
2. The worse scenario is if the event has name collision with the `Forwarder`'s own events, causing consumers of the normal `Forwarder` events to break when they start seeing the forwarded events with different semantics and signature.

Rather, `Forwarder` should only register for explicit, known, expected events on `Emitter` and only emit explicit, known, expected events for `Consumer` to observe.

**Comment by vladsud** [comment]
I personally care much more about simple straight Emitter case. With one of the scenarios being:
1. there is consumer & producer (emitter) that are correct at the moment.
2. Producer removes one of the events
3. I want consumer to stop compiling, to know interface has been changed and it needs to do something about it, similar as if method was removed from producer. Today that does not happen - there is neither compile time nor runtime error, which adds bugs.
   - same for users subscribing to events, but misspelling name of existing event - nothing bad happens.

**Comment by ChumpChief** [comment]
Sorry, I thought this was related to this conversation so I prob just misinterpreted the question: https://github.com/microsoft/FluidFramework/pull/3904#discussion_r504391755

IMO there should definitely not be a runtime error, this would be very atypical for event registration.  I'm in favor of compile-time errors but the `newListener` pattern implicitly expands the potential event surface to be anything at all as I mention above - I don't know how you type that for a compile-time error.

**Comment by anthony-murphy** [comment]
The typing on the interface is the strictest. The typing on the class is optional for compatibility reasons, and due to the fact, it was hard to do, so it seemed ok the give consumers strong typing via the interface and leave the class more flexible for implementors. So we currently don't do typing on newListener, and we only expose it on the class, not the interface.
