### ISSUE TITLE
MergeTree: Known weaknesses w/MergeTree undo

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#3964]
Issue tracking known weaknesses of the current undo/redo support for MergeTree (and by extension, SharedSequence subclasses and SparseMatrix).

### Item reordering when remove/undo races with insertion
```
client1:
    inserts "zz"
client2:
    observes "zz"
    inserts 'y' at pos 1 -> "zyz"
client1:  (without observing insertion of 'y')
    undo (removes range 0,2) -> "" 
    redo (reinserts "zz" at position 0)
```
After processing remote ops, client2 will observe 'zyz' become 'zzy'.

### Extraneous insertions when clients race to remove/undo overlapping ranges
```
both clients start with 'abc':

client1:
    removes "ab" -> "c"
    undo (inserts "ab" at pos 0) -> "abc"
client2: (without observing ops from client 1)
    removes "bc" -> "a"
    undo (inserts "bc" at pos 1) -> "abc"
```
After processing remote ops, both clients will observe "abc" become "abbc"

**Comment by anthony-murphy** [comment]
For the current implementation of undo redo these are by design, as the current implementation is local only, and only takes local operations into account. I don't think it is possible to solve either of these from a local only perspective. To truly solve these we would need to assign a fixed identity to all content rather than just cp. this is possible, but a significant change to existing structure.
