### ISSUE TITLE
runtime-definitions 0.27.1 isn't compatible with 0.27.0

### ISSUE THREAD

**Issue by mattdmorgan** [microsoft/FluidFramework#3992]
The addition of `request` to IContainerRuntime in 0.27.1 breaks compatibility with 0.27.0. This showed up when doing a lockfile update: I was specifying 0.27.0 for the Fluid packages I directly depend on, but the intra-Fluid dependencies, being looser (^), picked up several 0.27.1 packages and caused a build break. 

I was able to fix this case in my own project by upgrading across the board to 0.27.1. But I wonder about next time, as I can't always count on an upgrade being straightforward, and I _really_ don't want to block lockfile updates as I'm working in a large monorepo.

(Opening this to track per @tylerbutler's request.)

**Comment by curtisman** [comment]
Thank you for reporting the issue.  This is definitively an oversight on our part.  

While our framework is still in preview stage and we are still working on the shape o the API. The intention is that our patch releases are compatible with each other, so that user can automatic get hot fixes automatically.  In this case, we restored an old API and causing the issue.

In this case, since you already work around the issue, (by update everything to 0.27.1), we are not going to go back and fix it this time.   We are going to look into using tooling to catch this kind of changes in the future.
