### ISSUE TITLE
Provide more actionable data to engineers when data store fails to summarize

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3996]
Specifically, there is a search contract between O365 eco-system and SPO that requires data stores to write out specific blobs for search that storage understands.
We are fine In situation where safe summary is invoked due to data store factory missing, or some other critical error that results in data store not loading, because this content is not visible to user, to excluding it from other contracts is Ok.

The problem that I observer right now is that at-mention component collection in Fluid preview app is summarized using safe summary, but it does not fail to load - all at-mentions are find, I can keep adding them, etc.
This combination breaks contracts (including search, eDiscovery).

Also I do not see any logging in telemetry indicating errors.

docId = “VnVb9gEDvKmlBWgp8Zep6n48jmXTzbNDehAD71FBAIA%3D”

Summary payload:
{"id":"bHwMAAAAAAAAAAQAAAAYAAAA=","sha":"bHwMAAAAAAAAAAQAAAAYAAAA=","path":"atMentions","type":"tree"},
{"id":"bHwUAAAAAAAAAAQAAAAYAAAA=","sha":"bHwUAAAAAAAAAAQAAAAYAAAA=","path":"atMentions/_baseSummary","type":"tree"},
{"id":"bHwcAAAAAAAAAAQAAAAYAAAA=","sha":"bHwcAAAAAAAAAAQAAAAYAAAA=","path":"atMentions/_baseSummary/.component","type":"blob"},
{"id":"bHwYAAAAAAAAAAQAAAAYAAAA=","sha":"bHwYAAAAAAAAAAQAAAAYAAAA=","path":"atMentions/_baseSummary/instances","type":"tree"},
{"id":"bOxEAAAABAAAABwAAAA==","sha":"bOxEAAAABAAAABwAAAA==","path":"atMentions/_baseSummary/instances/.attributes","type":"blob"},
{"id":"bOyAAAAABAAAABwAAAA==","sha":"bOyAAAAABAAAABwAAAA==","path":"atMentions/_baseSummary/instances/header","type":"blob"},
{"id":"bHwQAAAAAAAAAAQAAAAYAAAA=","sha":"bHwQAAAAAAAAAAQAAAAYAAAA=","path":"atMentions/_outstandingOps","type":"blob"},

[Sample file](https://microsoft-my.sharepoint-df.com/:u:/p/vladsud/EZjxRE0HbXJErSxJrkGJA0IBMWkgiNfG6ILWIQ-bPhnJkQ?e=qbdoRX)
[Dev preview link](https://fluidpreview.office.net/p/c3BvOmh0dHBzOi8vbWljcm9zb2Z0LW15LnNoYXJlcG9pbnQtZGYuY29tL3BlcnNvbmFsL3ZsYWRzdWRfbWljcm9zb2Z0X2NvbQ%3D%3D/b!GH1UYt1nmkGpueRYHOn6pCeB9bfvwtBCrkPzGh6Sp4TIDZdc1fC4Qo0mv_K0xCO7/01OOTU2R4Y6FCE2B3NOJCK2LCJVZAYSA2C/test-1)

**Comment by curtisman** [comment]
In general, I'd consider safe summary to be an error that the app developer will need to resolve as soon as possible (as most likely reason is some problem there).   While the runtime helps the document limb along so that if the developer deploy a newer version to fix the issue, we should have a path way for the app to respond to it and prevent further degradation of the situation, and have default policy to stop adding more edits until a good summary can be generated.

That goes for the same for code that generates addition blob that dev add into the summary.  We can separate the protection here, but at the end of the day, if this code path has error, we are not in a good state.

**Comment by arinwt** [comment]
I understand the issue, but I'm not sure what the alternative is.

If summarize process is failing for a component but it still loads and is visible on the screen, then we are in an error state for that document until the underlying summarize bug is resolved. So in this interim time, I see 2 choices:
1. Fail summary entirely: eventually document will end up with too many ops since last summary, etc.
2. Current method: we lose searchability of failing components until component summary succeeds, but doc remains mostly stable otherwise.

Problem with switching from (1) to (2) is that even with (1), I believe we do not guarantee visible components will be searchable. Newly added components will not be included in the summary, because they are still in the form of attach ops since the last good summary. So in summary:
1. Will cause all components added since the last good summary to not be searchable, but existing visible components remain searchable (as of their state at time of summary).
2. Will cause components that were previously visible and searchable to no longer be searchable only if they are failing to summarize. All newly added components that successfully summarize are searchable.

It seems like a trade-off to decide between which components are searchable in the interim while resolving summarize fix.

One additional problem with both (1) and (2) is that once components become unsearchable because of "safe"/"failure" summary, they will never be searchable again until the components are changed (new op) or a "full" summary takes place. This could happen after bug is resolved allowing those components to be visible. That might be an area we can improve.

**Comment by vladsud** [comment]
Yes, I do not know what's the best outcome here. I'm big proponent of fail-fast approach, and from this perspective I'd favor generating critical error for document (main container) and stopping after second failed summary for component.

That said, I think it's fine to start with just adding telemetry. Tony added starting one, but I think we are missing a ton of things in this department:
1. We need some kind of summary instance ID to be able to answer questions like - how many errors like that are in single summary? Tony opened an issue on that based on my comment.
2. For each safe summary, we need to log depth level, such that it's immediately clear from telemetry things are not working as expected.

Once we have these, we can tune the rest of the logic....
It can be as simple as - this component summary is too big (has too many ops), stop failing once it goes above X size.
Or something else.

Note that we also added notion of "warning" on container in addition to errors.
That might be great signal to bring to hosting app - it does not stop the train at the moment, but it's something that we need to raise to the user as "there are some issues with this document..."

**Comment by vladsud** [comment]
Maybe this is already fixed?

The problem that we observed with failed summaries is that on each iteration "safe" summary would upload all the ops from last successful full summary of component. This means it will keep growing over time.

I've opened separate issue (https://github.com/microsoft/FluidFramework/issues/3996) suggesting that we should fail full summary after some attempts to stop the bleeding.
But if we go other way around, I think we need to change design for each safe summary to upload only blobs from last summary, whether it was safe or not. While this will create a ton of blobs that client need to load, it will ensure that summary payload keeps small.
Otherwise we are quickly running into https://github.com/microsoft/FluidFramework/issues/4069 where summarizer looses ability to send summary due to large payload and whole document gets stuck.

All that said, no matter we upload all ops from last full summary, or small deltas from previous safe summary, sooner or later that process dies due to either super-expensive cost of loading, or super-expensive cost of summaries. We need to have some explicit end to that process

**Comment by vladsud** [comment]
I believe as long as we generate an error telemetry event every time we can't generate real summary, we are find.
We need to log package path and given that I can find only one reference where we use TelemetryDataTag.PackageData in telemetry (unrelated), I guess we do not have right telemetry in place to help developers address the issue.

@arinwt - could you please add instructions on where is the best place to add such telemetry?
Is FluidDataStoreContext.summarizeInternal() the right place?
It has access to factory package (pkg) - that's what I'd record by changing execution order (moving up getting it above summarize() call) and wrapping the rest with try / finally / logging.

Putting it into June (can move out to July if needed) and assigning to Kabir.

Changing title as well to better reflect the work.

**Comment by markfields** [comment]
Removing design required label since the PR implementing Vlad's suggestion is moving along.  If there's additional ambiguity here let's discuss here.

**Comment by vladsud** [comment]
@anthony-murphy , you have assigned it to August, it's not assigned to a person, I assume we are Ok to move out?
It has been a while since I looked at this issue, but glancing it's summary related, so assigning to Paul to consider.

**Comment by pleath** [comment]
There have been telemetry improvements on Summarizer error paths. Is this still something we need to consider?

**Comment by vladsud** [comment]
I believe there is nothing to do here - we removed safe summaries.
