### ISSUE TITLE
Write a few basic Differential Summary tests

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#4019]
It is also fairly easy to repro the bug on old code, so you could create a bad doc using clicker and then open it with your changes and verify things worked as expected on load. (That was how I initially tested the fix)

Otherwise you may want to do a more explicit remove duplicates fix. Or like Vlad said find slice point, but In reality, given how the bug works, the slice point is just remove all the ops from `newOutstandingOps`.

_Originally posted by @arinwt in https://github.com/microsoft/FluidFramework/pull/4016#discussion_r509657824_

**Comment by markfields** [comment]
The goal here is to make it easier to write the next test - So keep some light infrastructure in mind to facilitate testing summary/safe summary.

**Comment by anthony-murphy** [comment]
we don't have the infrastructure to write something like this currently. #4810 would be a good start for this kind of test, so we should re-evaluate on that is done

**Comment by ksbrar** [comment]
@anthony-murphy should this be closed?

**Comment by markfields** [comment]
Kabir and I thought it probably could be closed, since @agarwal-navin and @arinwt have done a lot of work here in the... 9 months since this was opened, both in the code and the tests.

**Comment by agarwal-navin** [comment]
I don't think we have any tests specific to safe summaries. @arinwt might know for sure. We are working on writing summary tests easier. So, I would keep this around to track actually writing the tests once we have the capability to write them.

**Comment by arinwt** [comment]
It's a bit of a misnomer, because "safe summary" actually refers to something different. This issue is talking about "differential summary", which is when we submit a handle to the previous datastore + a blob of outstanding ops for a specific subtree in the summary.

This was enabled only at the datastore level, but then we disabled the code for 2 reasons: (1) tricky bugs in the logic, and (2) it hides other issues for too long, though this can be mitigated with better logging, alerts, etc.

To answer the question, there are no explicit tests around this functionality that I know of. The code for reading/writing differential summaries is contained within SummarizerNode, so this issue is related: #4459.

**Comment by agarwal-navin** [comment]
I don't think we need tests for differential summaries since its disabled and I doubt we will turn it on again. Do we need tests for the real "safe summaries" though? Basically, validating we do generate safe summaries when required.

**Comment by markfields** [comment]
@arinwt - If the original comment was about differential summaries, then please close.  Thanks!

**Comment by curtisman** [comment]
The feature no longer exist.

**Comment by agarwal-navin** [comment]
We should create an issue to remove the code from `summarizerNode` which is unused and makes it unncessarily complex.
