### ISSUE TITLE
Improve stress testing of critical limits

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4084]
This week we have a set of cascading failures that caused a lot of pain to our users.
We should learn from them and see if we can build end-to-end test coverage (involving SPO driver).

Key areas where we failed:
1. Too many blobs in snapshot. We added a fix that would download only skeleton of snapshot without blobs. We failed because browser has some limit to number of outstanding http requests, and with SPO being on http 1.2 (not 2.0) we issued hundreds of http requests and somewhere that failed. We brought this payload to Bohemia before realizing damage.
   - that same changed caused other regressions, we can drill into it.
2. If file has 10K unsummarized ops, and all clients are gone, we can't summarize file. New client would not attempt to spawn summarizer due to default "read" connection mode, and failing on NACK when sending op, never having a chance to establish "write" connection.
3. We run out of memory with payloads that are substantially smaller than what fits in memory, due to having too many copies of same data (too many caching layers).
4. Safe summaries (summaries of data stores using ops when regular summary fails) causes exponential growth over time (as data store is changed) in terms of payload in summary.
5. If delta between two summaries is large (in terms of payload), we see summarizer loosing connection and bailing out, thus not being able to summaries.

It would be great to start adding end-to-end stress tests

**Comment by vladsud** [comment]
@skylerjokiel - FYI, please feel free to add / comment

**Comment by markfields** [comment]
Plan for November is to break this out into a stack-ranked list of specific failure modes to cover, and commit to implementing at least one during the month.

The emphasis at first will be on exercising our codepaths by mocking out errors in our end-to-end tests (or Unit Tests!), rather than "Real Service" tests that actually hit ODSP service. Some of this will be mocking out driver, some will be using ODSP driver and mocking out Axios (HTTP client library).

Obviously this doesn't cover everything above (e.g. (1) above is about browser/HTTP implementation)

But in general there are two aspects to good test coverage here:
1. Exercising our code via fault injection, to ensure we're being defensive in how our code is written, and have a good shot of surviving whatever comes at us over the wire.
2. Exercising end-to-end scenario with ODSP service (what I call a "Real Service" test), to flush out edge cases before dogfooders do, and make sure we (A) know what they are and (B) confirm that we handle these particular errors well

And we can add specific test cases to fault injection tests as we find gaps, whether via "Real Service" tests or livesite issues.

**Comment by markfields** [comment]
We've got a full sprint of work for November, so bumping this to December.  During planning we'll break it out to specific things to implement

**Comment by markfields** [comment]
https://github.com/microsoft/FluidFramework/issues/4423 covers this kind of effort now.
