### ISSUE TITLE
Need a public tool to share anonymized files with us for debugging

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4141]
Scenario:
- Vikas hit a bug that is reproducible (i.e. happens on every open) that he reported
- Log inspection was not enough to quickly pin-point to a problem, we need more state

Would be nice to:
- Point users to easy to use tool that 
   - download s file
   - anonymizes it
   - gives a chance for user to inspect content before sharing it with us.

Today, this can be done as combination if fetch tool, replay tool and anonymization tool.
It's too many steps to get to final result, it's very unlikely user can follow all the steps with good success rate.

Ideal tool:
- A script that does all the right steps
   - possible: leaves machine clean of any packages, i.e. leaves machine in exactly same state. Or maybe uses user's temp / AppData folder or something of that nature for caching
  - gives user back a single file (format of replay tool snapshot) that user can inspect in reasonable amount of time.

**Comment by vladsud** [comment]
Even better, can we build it as separate tool, but also build it into Fluid Debugger?
The latter should probably take higher priority!
Kyle added recently ability to download ops into it, I believe, so we keep building workflows there.
That said, if we can build it as stand-alone utility, and then use Fluid Debugger as a place to just host it (i.e. button only), that would be ideal flow, as we can add same workflow into other places, including Feedback workflow in shipping product.

**Comment by skylerjokiel** [comment]
This seems like a bigger issue that requires a bit more design. @heliocliu is gonna tackle outlining a plan for December.

**Comment by heliocliu** [comment]
I missed that Kyle had already added the functionality to download ops through the debugger so this item probably doesn't need much design... The linked PR adds the anonymization step, so all that's missing is allowing the user to preview the file.  This should require only using the replay-tool to generate a snapshot for the messages.json file, then leveraging the existing debugger functionality to load a snapshot file.  The problem is that this is blocked on #4703 and #4704
