### ISSUE TITLE
IFluidLoadable  or IProvideFluidHandle ?

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4165]
I see two possible paths:

1. Get rid of IFluidLoadable in favor of IProvideFluidHandle:
   - IFluidLoadable.handle -> IFluidLoadable.IFluidHandle
   - IFluidLoadable -> IProvideFluidHandle, remove IFluidLoadable 
   - Remove IProvideFluidLoadable: implementers of this interface should instead implement only IProvideFluidHandle
2. Get rid of IProvideFluidHandle in favor of IFluidLoadable:
   - Replace all usage of IProvideFluidHandle to FluidLoadable (implementers and consumers).

I think the picture at the end of # 2 is not nice: we would have
IProvideFluidLoadable -> IFluidLoadable -> IFluidHandle.
That's 3 levels deep, and naming is not consistent.

So I vote to implement # 1.

**Comment by vladsud** [comment]
@wes-carlson, assigning to you for consideration if you do not have any other work or blocked and waiting for something. In such case, please take a look. Otherwise this is low-priority item, feel free to keep it on backlog for as long as needed :)

**Comment by anthony-murphy** [comment]
related to #8169

**Comment by anthony-murphy** [comment]
I've been poking around in this area, and while i initially agreed that normalizing on IFluidHandle was the right approach, i know come around to using IFluidLoadable. The reason is more around the usage ergonomics, and the point of the delegation pattern. 

If we look at it from a non-anonymous perspective, it looks like as follows
``` typescript
1) obj.handle.get()
2) obj.IFluidHandle.get()
```
in this case, which seems to be the more common case, i prefer option 1. I also think this furthers the goal of reducing usage of the provider pattern, which i feel is currently overused in non-anonymous use cases throughout our code.

**Comment by vladsud** [comment]
I'm find with trying to get rid of both IFluidLoadable & IProvideFluidLoadable :)
But I have a feeling that there will be places where someone needs to do QI to interrogate object if it supports handles.
And if so, "handle" keyword is too short and generic so interrogating object for implementing handle property is likely not great.

**Comment by anthony-murphy** [comment]
In general i'd really like to minimize our dependence on and kind of QI within the fluid framework itself. As it feel like an application concern we unnecessarily take on. I actually think this is achievable especially if we do something like #8169

In the non-QI case i think the right path is just `.handle` and i'm not sure we really need any enforcement of even that.
