### ISSUE TITLE
Improve logging for remove/addMember

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/FluidFramework#4283]
## Describe the bug
https://github.com/microsoft/FluidFramework/blob/770967e30be07ded290c88f9e1168fe3a26a96e1/server/routerlicious/packages/protocol-base/src/quorum.ts#L158-L171

IcM ticket 213183647

**Comment by anthony-murphy** [comment]
these should crash. i was thinking this was audience, which can be less strict

**Comment by anthony-murphy** [comment]
but we should probably close the container, rather than assert, which doesn't capture in our logs well

**Comment by micahgodbolt** [comment]
@anthony-murphy do you have an example of a place where we do that?

**Comment by anthony-murphy** [comment]
there is a Container.close function, i don't think the quorum can access that directly though. might still need to throw here, and close the container in the Container's protocol handler or something

**Comment by SamBroner** [comment]
Do we have an investigation going on what situatoin leads to out of sync quorum? Seems like an issue.

**Comment by SamBroner** [comment]
Can we update this bug to being an investigation of that situation, with a container.close as a possible outcome?

**Comment by curtisman** [comment]
One consideration is that if we always do Container.close, we might never able to open the file to recover.

**Comment by micahgodbolt** [comment]
@curtisman any thoughts on someone to assign this to? Or is this a OCE concern?

**Comment by curtisman** [comment]
@micahgodbolt  I assume this it not urgent, so it is set into Dec milestone for now and we will prioritize and assign as we get closer.

**Comment by anthony-murphy** [comment]
This is a live document corruption issue. we've engaged ODSP, but we may need a more urgent fix to mitigate

**Comment by curtisman** [comment]
@anthony-murphy Is this just for adding logging when there is error?  Do we stop asserting?

**Comment by anthony-murphy** [comment]
I don't know the implication of two leaves. seems like it could cause problems elsewhere in the stack. i want to keep the assert and at least log (currently we don't capture the asser). i'm still open to closing the container we well.

**Comment by vladsud** [comment]
All of the exceptions that happen during op processing eventually reach DeltaManager handler that closes container with that error - that's how we see these asserts from quorum in the first place (asserts are exceptions).

Quorum should not have direct access to Container. We could propagate an interface / callback, but that seems unnecessary to me. I'd rather standardize on signature / type of exception (including any extended properties we want to get to telemetry) instead of leveraging asserts (and do it on as needed bases). There is always a case that we drop exception on the floor, but it's true in general (consider runtime exceptions, like dereferencing undefined) - I'd rather see us invest in testing, then into more complex error paths.

So I'd propose we close it.
@anthony-murphy , @micahgodbolt , any push back?

P.S.: would appreciate a link to ICM, not an ID.

**Comment by micahgodbolt** [comment]
ICM link https://portal.microsofticm.com/imp/v3/incidents/details/213183647/home
