### ISSUE TITLE
PrefetchDocumentStorageService does not correctly handle ".blobs" tree from BlobManager in snapshot

### ISSUE THREAD

**Issue by wes-carlson** [microsoft/FluidFramework#4401]
## Describe the bug
When `PrefetchDocumentStorageService` gets a snapshot tree from SPO containing a `".blobs"` tree, it attempts to prefetch the blobs inside using the snapshot blob API (opStream/snapshots), resulting in an error response:
```
{"error":{"code":"invalidRequest","message":"node must be streamed."}}
```
followed by an unhandled promise rejection:
```
12:48:59.973 logger.ts:444 Uncaught (in promise) Error: Error 400 from the server, msg = , type = cors
    at createOdspNetworkError (odspErrorUtils.ts:93)
    at throwOdspNetworkError (odspError.ts:20)
    at odspUtils.ts:77
    at async fetchAndParseAsJSONHelper (odspUtils.ts:109)
    at async EpochTracker.fetchAndParseAsJSON (epochTracker.ts:72)
    at async Function.timedExecAsync (logger.ts:355)
    at async OdspDocumentStorageService.read (odspDocumentStorageManager.ts:230)
```

### To Reproduce
1. Upload a blob
2. Wait for snapshot
3. Reload

### Expected behavior
We probably do not want to be attempting to prefetch these blobs at all.

**Comment by curtisman** [comment]
do we want to prefetch blobs?

**Comment by vladsud** [comment]
The prefetching logic IMHO should either go away, or substantially change. It's goes against pay-per-play rule  - if file is 1Tb, it will attempt to fetch all 1Tb. If we want to keep it, we want to make it similar to how SPO storage makes decisions about what to pre-cache (in case of SPO - via snapshot call). That said, it may not have enough data to work on, like size of blobs, to make decisions on whether to prefetch or not.

I believe long term, FRS will not be able to avoid optimizing boot in the same way as SPO. Even with http 2.0 support, it's expensive (COGS) to fetch items individually, as well as you can't fetch thousands of blobs efficiently (there is a limit of 6 sockets, and I think 100 parallel request per socket or so).

The analogy to Git is valid here - while Git does have "dump" protocol (that's equivalent to current R11S protocol), it's not used widely, not recommended to use, and quite often is disabled. "smart" protocol operates with packs:
https://git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols

But if we are talking about details of fetching single blob, then it fails because driver's read() can't be used for binary blobs, at least today with SPO driver. In other words, readBlob() & writeBlob() need to be paired. I believe @wes-carlson switched all blob writing/ reading to new SPO API, so maybe this bug is already addressed?

**Comment by vladsud** [comment]
Oh, one note - prefetcher is not used with SPO any more - it gets instantiated only with R11S. So the bug (as it was originally reported) is no longer possible to repo. And with Wes' work, I think it will not even be there (if we used prefetcher for SPO).
But the core of the problem (of dump prefetch logic) is still there for FRS to sort out.

**Comment by vladsud** [comment]
This issue is not affecting shipping scenarios, as ODSP does not use prefetcher.
Once FRS strategy around perf formalizes,  we may either need to fix it, or delete prefetcher (i.e. follow ODSP model)

**Comment by vladsud** [comment]
@tanviraumi , assigning for you for triaging, as it affects only FRS.
The original issue is no longer an issue I believe, at least in ODSP world, where both summary and attachment blobs are now accessed using single API. Same was true for r11s from start.

However other considerations raised in this issue are valid, including not prefetching attachment blobs (/.blobs/ subtree) and in general being more pay-per-play. For reference - ODSP does not include such blobs in snapshot payload (they base it on type of blob, not particular path, as they differentiate in storage between attachment blobs and summary blobs).

**Comment by tanviraumi** [comment]
Thanks!!! Adding Zach to follow up more on this
