### ISSUE TITLE
Data_errorType is empty in Kusto

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4514]
That's one key property that we use to differentiate errors across all layers.
Not clear why it's missing in telemetry, would be great to fix it!

**Comment by tylerbutler** [comment]
Could be related to #4495.

**Comment by curtisman** [comment]
I looked at the code, and the errorType should be logged already.

I believe the problem is that this field used to be a number (in a enum), and we changed it to a string at some point.
I am not sure what behavior for the telemetry pipeline when they have conflicting data type for a data field is.

I have seen that if they are from different tables, they will get auto renamed when you union them.  But it might just stop saving it if it is the same table.

It there anyway to change the data schema in the telemetry data base?

**Comment by markfields** [comment]
I had looked at this code the other day too, I wasn't convinced it's logged, since I don't think it's passed into the constructor for CustomErrorWithProps.  But also yeah it seems to have changed from numerical type to string at some point.

**Comment by curtisman** [comment]
getCustomProperties() should enumerate all the properties on the object, whether it is passed to constructor of CustomErrorWithProps or not.

**Comment by curtisman** [comment]
@anthony-murphy  do you know of any way to purge old data?

**Comment by anthony-murphy** [comment]
Not off hand. It seems like we need to add some test to ensure the properties are even attempted to be logged, as mark mentions above.

**Comment by markfields** [comment]
FYI - The issue was with Kusto as @curtisman suggested.  For future reference, go here to edit data types of fields in our tables: https://portal.aria.ms/kusto/6a8929bcfc6d44e9b13fee392ada9cf0/tables?table=Office_Fluid_FluidRuntime_Error

It updates immediately (purging existing data of the old type), as you can see already:
![image](https://user-images.githubusercontent.com/12305068/107590819-fba7c800-6bbd-11eb-8352-f614860bf7eb.png)

_Now_ this issue is closed :)

**Comment by vladsud** [comment]
@markfields , it would be great to add this info in out OneNote!
