### ISSUE TITLE
Optimizing ODSP snapshots

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4589]
Please note that discussion here centers around optimizing snapshots, but it is likely as applicable (i.e. format of data representation) for following two APIs we need to add:
1. Batched download of multiple blobs
2. Fetching sub-tree (for cases where not all trees are represented in snapshot, including marked for deletion by GC sub-trees).
Having one unified download format will ensure sharing of code and optimizations applied to all 3 cases.
To some extent, we can see all three as a single API, where API allows different queries (asking for snapshot, asking for blobs, etc.). And can support in the future such things as fetching trees and blobs for a component only (not whole file).

SPO snapshots are too big. This item tracks finding much more compact representation for the same data.

Here is an example of one of the sub-trees.
It takes 1020 bytes:

```
{"id":"bHwoAAAAjAAAAAQAAAAYAAAA=","path":"11863e07-96e4-4624-ad31-3c1e54aba66e","type":"tree"},
{"id":"bHxEAAAAjAAAAAQAAAAYAAAA=","path":"11863e07-96e4-4624-ad31-3c1e54aba66e/.component","type":"blob"},
{"id":"bHxIAAAADAAAAAQAAAAYAAAA=","path":"11863e07-96e4-4624-ad31-3c1e54aba66e/664f35ed-cf9d-4bc6-a957-ee93bbd1690b","type":"tree"},
{"id":"bHxQAAAADAAAAAQAAAAYAAAA=","path":"11863e07-96e4-4624-ad31-3c1e54aba66e/664f35ed-cf9d-4bc6-a957-ee93bbd1690b/.attributes","type":"blob"},
{"id":"bHxMAAAADAAAAAQAAAAYAAAA=","path":"11863e07-96e4-4624-ad31-3c1e54aba66e/664f35ed-cf9d-4bc6-a957-ee93bbd1690b/header","type":"blob"},
{"id":"bOx8AAAABAAAABwAAAA==","path":"11863e07-96e4-4624-ad31-3c1e54aba66e/803f0d71-58dd-46a2-9ef9-bf002e97061d","type":"tree"},
{"id":"bOyEAAAABAAAABwAAAA==","path":"11863e07-96e4-4624-ad31-3c1e54aba66e/803f0d71-58dd-46a2-9ef9-bf002e97061d/.attributes","type":"blob"},
{"id":"bOyAAAAABAAAABwAAAA==","path":"11863e07-96e4-4624-ad31-3c1e54aba66e/803f0d71-58dd-46a2-9ef9-bf002e97061d/header","type":"blob"},
```
Some obvious problems with this representation:
- same path is repeated many times - each child repeats base path of its parent
- there is no way to reuse same sub-trees in different parts of the tree. While client can write such snapshots, clearly we can't represent them in this format, as path of the tree node is encoded within itself, not within its parent. This is wrong.
- there is no way to omit some tree for client to download individually later. I.e. if some tree is missing, we assume (with this representation) that it's empty. This does not allow us to omit trees that are marked for deletion by GC.

A representation we can use for "11863e07-96e4-4624-ad31-3c1e54aba66e" tree:
```
{"id":"bHwoAAAAjAAAAAQAAAAYAAAA=","children":[{"bHxEAAAAjAAAAAQAAAAYAAAA=", ".component", "blob"},{"bHxIAAAADAAAAAQAAAAYAAAA=","664f35ed-cf9d-4bc6-a957-ee93bbd1690b","tree"},{"bOx8AAAABAAAABwAAAA==","803f0d71-58dd-46a2-9ef9-bf002e97061d","tree"}]},
{"id":"bHxIAAAADAAAAAQAAAAYAAAA=","children":[{"bHxQAAAADAAAAAQAAAAYAAAA=", ".attributes", "blob"},{"bHxMAAAADAAAAAQAAAAYAAAA=", "header", "blob"}]},
{"id":"bOx8AAAABAAAABwAAAA==","children":[{"bOyEAAAABAAAABwAAAA==",".attributes","blob"},{"bOyAAAAABAAAABwAAAA==","header","blob"}]},
```
In this representation an object (tree) contains full information about its children (id, path, type), and thus child does not need to repeat it. It addresses all the problems raised above and it's much more compact representation.

Or we can make it even more compact, in a form of **[id, [trees...], [blobs...]]**:
```
["bHwoAAAAjAAAAAQAAAAYAAAA=",[{"bHxIAAAADAAAAAQAAAAYAAAA=","664f35ed-cf9d-4bc6-a957-ee93bbd1690b"},{"bOx8AAAABAAAABwAAAA==","803f0d71-58dd-46a2-9ef9-bf002e97061d"}],[{"bHxEAAAAjAAAAAQAAAAYAAAA=",".component"}]],
["bHxIAAAADAAAAAQAAAAYAAAA=",[],[{"bHxQAAAADAAAAAQAAAAYAAAA=", ".attributes"},{"bHxMAAAADAAAAAQAAAAYAAAA=","header"}]],
["bOx8AAAABAAAABwAAAA==",[],[{"bOyEAAAABAAAABwAAAA==",".attributes"},{"bOyAAAAABAAAABwAAAA==","header"}]],
```
Flattening child trees and blob entries will give us even more compact representation, and faster parsing due to less memory allocations:
```
["bHwoAAAAjAAAAAQAAAAYAAAA=",["bHxIAAAADAAAAAQAAAAYAAAA=","664f35ed-cf9d-4bc6-a957-ee93bbd1690b","bOx8AAAABAAAABwAAAA==","803f0d71-58dd-46a2-9ef9-bf002e97061d"],["bHxEAAAAjAAAAAQAAAAYAAAA=",".component"]],
["bHxIAAAADAAAAAQAAAAYAAAA=",[],["bHxQAAAADAAAAAQAAAAYAAAA=", ".attributes","bHxMAAAADAAAAAQAAAAYAAAA=","header"]],
["bOx8AAAABAAAABwAAAA==",[],["bOyEAAAABAAAABwAAAA==",".attributes","bOyAAAAABAAAABwAAAA==","header"]],
```
This representation is 423 bytes! It does not container name of the tree ( "11863e07-96e4-4624-ad31-3c1e54aba66e") which will be listed with parent, but total improvement is 2x!
It also requires less manipulation on client to actually build a tree, as we do have all the info at each node, i.e. processing time to construct runtime objects (ISnapshotTree) is much faster.

Some other observations that are likely harder to implement:
1. Guids are very long. Are there more compact ways to generate unique IDs?
2. We would be way more efficient if we used binary representation,. For example, each 2 characters are 4 bytes (if using utf-16 representation), but they actually represent only one byte (for guids). Similar, it looks like storage IDs are actually very short (4-5 bytes?) IDs that are encoded in very long ascii string.

**Comment by vladsud** [comment]
And looking at how we encode blobs:

> {"id":"bHxEAAAAjAAAAAQAAAAYAAAA=","content":"eyJwa2ciOiJbXCJAbXMvc2NyaXB0b3JcIl0iLCJzbmFwc2hvdEZvcm1hdFZlcnNpb24iOiIwLjEifQ==","encoding":"base64","size":58},

Represents this content:
> {"pkg":"[\"@ms/scriptor\"]","snapshotFormatVersion":"0.1"}

Switching to binary representation would remove most of the glue. 59 bytes of content (plus 26 characters for ID) are encoded using 159 characters (which are in UTF-16 encoding are 318 bytes!).

**Comment by vladsud** [comment]
I'd propose we go with this format:
```
[
   [id1, [trees1...], [blobs1...], id2, [trees2...], [blob2...], ...],    // trees
   [id1, content1, id2, content2, ...],      // blobs
   [op1, op2, ...],     // ops
]
```

This format uses the least amount of constructs - only binary blobs (for IDs we will use utf-8 encoding) and arrays.
(ops can be represented as binary payload, i.e. string, either each op being its own blob, or whole array of ops being one giant string that we need to JSON.parse).
The benefit of using least amount of constructs is that our options for using various tools / byte representations for this content is likely greater the less constructs we use.

Or we can use this format (more smaller arrays), if arrays are cheap:
```
[
   [
      [id1, [trees1...], [blobs1...]],
      [id2, [trees2...], [blob2...]],
      ...
    ]
   [
       [id1, content1],
       [id2, content2],
       ...
    ],
   [op1, op2, ...], 
]
```

**Comment by vladsud** [comment]
All the interesting data serialization formats:
https://en.wikipedia.org/wiki/Comparison_of_data-serialization_formats

Some notes:
- **BSON** is not compact
- **MessagePack**: The Protocol Buffers format aims to be compact and is on par with MessagePack. However, while JSON and MessagePack aim to serialize arbitrary data structures with type tags, Protocol Buffers require a schema to define the data types. Protocol Buffers compiler creates boilerplate code in the target language to facilitate integration of serialization into the application code; MessagePack returns only a dynamically-typed data structure and provides no automatic structure checks.
- **Apache Avro**: JSON for type and protocol definitions. Payload contains schema definition. It is similar to Thrift and Protocol Buffers, but does not require running a code-generation program when a schema changes (unless desired for statically-typed languages).
- **Apache Thrift**: A bunch of protocols. TCompactProtocol – More compact binary format; typically more efficient to process as well
- **FlatBuffers**: similar to Protocol Buffers, Thrift, Apache Avro, SBE, and Cap'n Proto. Compared to other serialization formats however, the handling of FlatBuffers requires usually more code.
- **protobuf**: IDL -> code gen. Protocol Buffers are similar to the Apache Thrift (used by Facebook), Ion (created by Amazon), or Microsoft Bond protocols. [Supporting JS library](https://cdn.rawgit.com/dcodeIO/protobuf.js/6.0.0/dist/protobuf.min.js) from [here](https://github.com/protobufjs/protobuf.js) is 17k in size.

Worth taking a look at ability to support zero-copy operations. Given that we are switching to working with binary blobs as a primary representation format (i.e. ArrayBufferLike returned by readBlob()), if it's possible to create ArrayBufferLike objects without copying any memory (and supporting  conversion to strings), that would be awesome!

Glancing at the list, FlatBuffers & MessagePack support zero-copy operations, but need to check if it's true for JS.

More on FlatBuffers:
https://google.github.io/flatbuffers/
https://github.com/google/flatbuffers
https://www.npmjs.com/package/flatbuffers

**Comment by vladsud** [comment]
Alternatively, given so simple format, we can create custom serialization / deserialization functions.
Something like that:

**content**: any number of bytes
**entry**: _type_, _size_, _content_, \0
**type**: 1 bit, describes if it's a buffer, or an array,
**size**: 4 bytes, encodes size of the array or buffer. 

And can be optimized to extreme - types of entries (node - an array):
'E' - end
'p' - pop the stack. Changes current node to parent of current node.
'a',  _content_ - adds an element (array) to current node. Current node is changed to this newly created array (walk down the tree).
'b',  size, _content_ - adds element (binary buffer) to current node.
'A',  _content_ - same as 'p', 'a'
'B',  size, _content_ - same as 'p', 'b'

Strings (that are part of snapshot protocol itself) are always encoded in utf-8. User strings can be encoded in any encoding as they are exposed as binary blobs (i.e. it's in runtime domain how to encode / decode blobs including string blobs).

Example:

[
  ['id1', ['e1, 'e2'], ['e3', 'e4']],
  ['id2', ['g1, 'g2']],
]

```
a,
   a,
      b, 3, 'id1', 
      a,
         b, 2, 'e1',
         b, 2, 'e2',
      A,
         b, 2, 'e3',
         b, 2, 'e4',
      p,
   A,
      b, 2, 'id2',
      a,
          b, 2, 'g1',
          b, 2, 'g2',
      p,
   p,
p
E
```

Note that it only encodes the tree, no other structure is represented at this level.
"trees", "blobs" & "ops" are next (interpretation layer) that does not depend on how we encode tree.

**Comment by vladsud** [comment]
@marcmasmsft, @ram-ramasubramanian - would love to hear your thoughts on the subject.

**Comment by vladsud** [comment]
[Chapter 1 document](https://dev.fluidpreview.office.net/p/c3BvOmh0dHBzOi8vbWljcm9zb2Z0LnNoYXJlcG9pbnQtZGYuY29tL3RlYW1zL09mZmljZU9ubGluZVByYWd1ZQ%3D%3D/b!BOyJN6Bkykm_L66EicZFaDKnQ_cydFFLqph8D-t_9vqaMsGC4Tm9RYec9Rh5aw3l/01N5X4JN6BX23SZCTFTFB2D5PEQUKWMZ3E/Chapter-1-Collaborative-Components):

**Snapshot in current format: 4.5Mb (compressed: 818K)
New format: 2.8Mb (compressed: 638K)**
_(compression using explorer)_

Total blob size encoded with base64: 2.8Mb

Some short analyzes of what takes space in new format:
1. 19% is the tree structure.
   - uuids (tree IDs, that are data store & DDS ids) are long and there are many of them.
   - Tree/Blob IDs are long and are repeated twice (parent tree, and in tree/blob itself). Having more compact IDs (especially given it's binary and 
2. 81% (pretty much everything else) is blobs
3. ops - tiny portion.

Biggest 10 blobs (base64 sizes):

524,772  | /462178a5-7e0a-4bdd-afa6-391b74443543/ad3ab54f-dad5-436c-a837-982fe4f7b651/content/header
 65,388 | /atMentions/instances/header
 48,860 | /d2533952-b0f2-48a0-b705-0929c34920ee/af1bf9bc-c5d0-4768-9113-a140e55a0543/content/header
 39,888 | /4dd396ad-bc57-4699-a57e-2fe350e53781/ca7cf605-7b29-4bc6-924d-02d67178ba38/content/header
 37,780 | /5c17a949-5a84-4b34-96eb-99be31da9068/4a40584d-9961-4d93-9dec-7376c0759409/content/header
 22,940 | /bfcbe74a-25b0-4e73-b1ea-0182e6ede0f8/matrix/content/body
13,404 | /795bea18-957a-4f85-9552-757ed3040396/4b80a7a3-787d-42ad-87c8-11fc4dd3749b/content/header
 11,604 | /a52eb727-f357-46df-9a09-99b2f1d4146f/matrix/content/body
10,616 | /706d3966-02ba-4b7a-a11e-dde8d80b787e/matrix/content/body
 10,512 | /dias/instances/header

Looking strictly at blob sizes, there is a ton of duplication. If I sum up all the blobs that have size < 1612, that gives me 1.5Mb!
Most of these are duplicates and likely there is less than 100K of unique content there.
Majority of these are
- <ID>/<ID>/header
- <ID>/root/header
- <ID>/<ID>/content/header
-  .attributes
- a ton of catchupOps blobs (4 bytes long - empty array).

Aggregated based on blob type across all data stores:
- content/header: 1.42Mb, 565 blobs
- header: 853K, 2402 blobs
- .attributes: 346K, 2404 blobs
- content/body: 93Kb, 15 blobs
- .component: 53K, 581 blobs

There are some images as part of content/header, so actual payload (after image work is done) would be smaller.

Proper blob de-duping (issue #4389) likely to remove at least 700K, image work likely another 300K (pure guess).
Size below 2Mb is definitely in reach.

Further improvements can come from
- gzip: there is a ton of duplication in merge tree attributes (attribution feature). That alone likely to result in this file snapshot being under 500K!
- Optimizing attribution feature.
- Consider non JSON representation for merge tree & directory / map.
-

**Comment by vladsud** [comment]
Related item - implement reuse of trees: https://github.com/microsoft/FluidFramework/issues/4634

**Comment by vladsud** [comment]
Marcelo pointed out that we likely do not need the tree info.
I.e. tree IDs are not needed, as blob reuse is done using symbolic names (snapshot paths).
If we remove the need to provide tree data, which includes
1. ability to for snapshot to have partial tree structure
2. ability to describe empty trees
3. ability to describe some properties of trees

Then we can only record data in format _blob path_ -> _id_
That's all we need, and actual blob content.
paths can be efficiently encoded by using dictionary.

Naïve implementation that I quickly coded resulted in **2.4Mb, compressed 575K!**
That's much better than mentioned above 2.8Mb (compressed: 638K).
Dictionary is about 10% of payload (SPO ids are about 7% of it, so that can be improved even further), 
Tree structure is about 3%, the rest is data (that has a lot of dups).

**Comment by vladsud** [comment]
Prototyping can be found here: https://github.com/microsoft/FluidFramework/compare/main...vladsud:Tree?expand=1

**Comment by vladsud** [comment]
And if I do blob de-duping, then I get **1.8Mb output, 552K compressed**.
Dictionary is 6%, tree structure 3%, the rest is data. 22% of total size is images (~400K)
So we definitely can get from current **4.8Mb to to 1.4Mb** (uncompressed)

**Comment by vladsud** [comment]
Attribution feature (and in general - properties) are very expensive. I'd estimate that about 200K is just attribution payload (2K attribution instances, each ~100 characters).
At mention storage is 74K.
The rest is pretty reasonable in terms of size.

**Comment by vladsud** [comment]
Document has 565 "catchupOps" blobs. Spot-checking 3 - they are empty ([]). Why are we writing them out?
There are 15 "body" blobs. This needs to be looked into too.

**Comment by sunnyhuang2008** [comment]
Here is an attempt to create the binary format using the [filestore team's binary encoder](https://microsoft.sharepoint-df.com/:w:/t/ODSPFileStore/ESrLoBvYBdRCk9qBnxoquqIBJUdiNr3VMp8QV2pRjhOcqg?e=7PeAeD) from a sample optimized snapshot response: 
[normalTest.zip](https://github.com/microsoft/FluidFramework/files/6612938/normalTest.zip) contains the binary format file (normalTest.bin) and the original optimized snapshot response (normalTest.json)

The format goes like the following structure:
`
[49]
[49]
	<header section>
[50]
[49]
	<Tree structure section>
[50]
[49]
	<dictionary section>
[50]
[49]
	<blob section>
[50]
[49]
	<deltas section>
[50]
[50]`
Each of these sections are enclosed with an opening array marker `[49]` and a closing array marker `[50]` (details on the markers can be found in the [filestore team's binary encoder documentation](https://microsoft.sharepoint-df.com/:w:/t/ODSPFileStore/ESrLoBvYBdRCk9qBnxoquqIBJUdiNr3VMp8QV2pRjhOcqg?e=7PeAeD)), all sections are enclosed by opening/closing array markers for the whole file.

**The header section** (Note: because the binary file viewer will convert the bytes into hex, so hex(49) = 31, hex(50) = 32):

<img width="446" alt="header" src="https://user-images.githubusercontent.com/15384952/121111164-411e7f80-c7c3-11eb-9ac5-81e3e793376b.PNG">

All header entries are in the form of: `<name of header entry (string type)> <value of header entry (could be any type)>` The name of the header entries are represented as the `[14][length of name string][name content]` (Note: hex(14) = 0E) where 14 is a _marker representing a string with length that can be represented by an unsigned-8-bit little-endian integer_.

This currently contains the following information:

- MinReadVersion: This is the minimum version of the reader required to read this wire format, the reader with this min version might not get the latest features/attributes if there are higher version of the binary format. This helps manage compatibility as the format progresses further (This is inspired by the [ZIP format](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) on how they handle versions). The MinReadVersion value is represented by a string which takes the form of `[14][length of version string][version string content]`.
- CreateVersion: This is the format version which this file is created from. The form also a string same as the MinReadVersion above.
- SnapshotSequenceNumber: This is the sequence number of the snapshot which should be used to populate the seq # of the following delta (since first delta's seq # = snapshotSeq# + 1). This value will be represented as an int in the form of `[03][seq number]` (Note: hex(3) = 3) where 3 is a marker representing the seq number is an  _unsigned-8-bit little-endian integer_.

**The Tree Structure Section**: 
<img width="431" alt="TreeStructure" src="https://user-images.githubusercontent.com/15384952/121114738-0ddeef00-c7c9-11eb-9158-9802721712f5.PNG">

The form of the tree structure is the same as before: `[number][open Array][number][open array][close array][close array]` represents a tree node that has a tree node as it's children (Example: `[03][00][49][50]` represents a empty tree node with _unsigned-8-bit little-endian integer_ 0 maps to it's path in the dictionary). A blob node is represented as `[number][number]` where the first number entry represents the number mapped to the blob's path and the latter maps to it's blob id in the dictionary (Example: `[03][00][03][01]` represents a blob with _unsigned-8-bit little-endian integer_ 0 maps to it's path in the dictionary and with an _unsigned-8-bit little-endian integer_ 1 maps to it's id in the dictionary).

**The integer mapping dictionary Section**:
<img width="429" alt="Dictionary" src="https://user-images.githubusercontent.com/15384952/121121598-bb0b3480-c7d4-11eb-8a1b-1d843f3b0d36.PNG">

The dictionary (mentioned above in the tree structure section) is used to store an integer mapping to the tree paths and blob ids. The entries are arranged in the form of `[31]<string dictionary entry><string dictionary entry>....<string dictionary entry>[32]` where the string entries are in the form of `[marker representing the string length][string length][string content]`. The respective integers that maps to each string entry is the entry's position within this dictionary list, as an example: `[31][14][05]['A']['P']['P']['L']['E'][14][03]['C']['A']['T'][32]` shows 0 maps to "APPLE" and 1 maps to "CAT".

As an example to illustrate how the integer dictionary is used, consider a simple tree with the following structure:
<img width="228" alt="treeNodeEx" src="https://user-images.githubusercontent.com/15384952/121122125-babf6900-c7d5-11eb-8b4c-71e2cd09600d.PNG">

This tree structure will first have all it's path variables and blobId mapped and stored in the integer mapping dictionary like so:
[
0: "a",
1: "b",
2: "c",
3: "123"
]

Then, the tree will be serialized to a hierarchical structure as discussed in **The Tree Structure Section** like:
`[03][00][49] [03][01][49][50] [03][02][03][03] [50]` where the numbers entries `[03][00]` `[03][01]` `[03][02]` `[03][03]` maps to "a", "b", "c" and "123" respectively in the dictionary where "a", "b", "c" represents the node's paths in the tree and "123" is the blob id.

**The Blob Section:**
<img width="429" alt="Blobs" src="https://user-images.githubusercontent.com/15384952/121123466-1db1ff80-c7d8-11eb-8cfd-d4dbb9c749bc.PNG">

This section contains the contents of the blob nodes, they are represented in this form: `[49]<blob entry><blob entry>.... <blob entry>[50]` where each `<blob entry>` is in the form of: `[03][blob id mapped integer][33][length of blob binary content][blob binary content]` (Note: hex(33) = 21, hex(3) = 3). The `[blob id mapped integer]` is mapped to the blob Id stored in the dictionay (mentioned in The Integer Dictionary Section) and the `[blob binary content]` is the content of the blob, `[33]` is the marker that represents _unsigned-8-bit little-endian lengthed binary content_ followed by the length of the content and the content itself.

**The Delta Section:**
<img width="429" alt="ops" src="https://user-images.githubusercontent.com/15384952/121124954-9c0fa100-c7da-11eb-802c-af7c0573e88c.PNG">

The last section stores the deltas, in the normalTest.json and normalTest.bin the deltas contents are just integer strings for simplicity. Normally it will be a string represented JSON. The deltas are in the form of: `[49]<string delta entry><string delta entry>...<string delta entry>[50]` where `<string delta entry>` is in the form of: `[14][length of string content][string content]` the same as how we represented header name and dictionary entries above.

Notice that we did not include the seq # for each delta in the deltas section, this is because you can easily calculate the seq # with the snapshot seq # given in the header. Also, the delta contents' JSON contains the seq # entry as well and can be obtained by deserializing the JSON string.

**Comment by vladsud** [comment]
Moving to July as the work will not complete this month (end-to-end).

**Comment by jatgarg** [comment]
Proposed design for fetching the new api as discussed with @sunnyhuang2008:
1.) Server wants to support enabling the new format only for few files at server at a time and then progress slowly adding more/next files.
2.) In order to support that, at client the driver can use the same api(as today) for both fetching the older json(IOdspSnapshot) format or for newer binary format. However the client would always try to fetch the binary response by specifying the Version of format in the form data of post trees/latest call. 
3.) Server can read that and if they want to return the newer binary format response with that version for that file, they can do so and specify a response-header saying that it is the binary response and client will read it as such. However if the server wants to send the older json response, they can do so and specify no header for that and client will read it accordingly then.

**Comment by sunnyhuang2008** [comment]
> Proposed design for fetching the new api as discussed with @sunnyhuang2008:
> 1.) Server wants to support enabling the new format only for few files at server at a time and then progress slowly adding more/next files.
> 2.) In order to support that, at client the driver can use the same api(as today) for both fetching the older json(IOdspSnapshot) format or for newer binary format. However the client would always try to fetch the binary response by specifying the Version of format in the form data of post trees/latest call.
> 3.) Server can read that and if they want to return the newer binary format response with that version for that file, they can do so and specify a response-header saying that it is the binary response and client will read it as such. However if the server wants to send the older json response, they can do so and specify no header for that and client will read it accordingly then.
> 
> fyi @vladsud
> 
> Also if we go with this, for now so as to integrate faster, we will read the a flag in local storage and based on that call the new rest api which always gives us the binary response and read accordingly.

Going with this route, the client can use the "accept" parameter in the header when making a request to specify which format can be returned. "application/json, application/octet-stream" would mean that both formats are welcome and the server would return json or binary at our discretion. If the "application/json" is requested, the server will just return json.

**Comment by marcmasmsft** [comment]
> > Proposed design for fetching the new api as discussed with @sunnyhuang2008:
> > 1.) Server wants to support enabling the new format only for few files at server at a time and then progress slowly adding more/next files.
> > 2.) In order to support that, at client the driver can use the same api(as today) for both fetching the older json(IOdspSnapshot) format or for newer binary format. However the client would always try to fetch the binary response by specifying the Version of format in the form data of post trees/latest call.
> > 3.) Server can read that and if they want to return the newer binary format response with that version for that file, they can do so and specify a response-header saying that it is the binary response and client will read it as such. However if the server wants to send the older json response, they can do so and specify no header for that and client will read it accordingly then.
> > fyi @vladsud
> > Also if we go with this, for now so as to integrate faster, we will read the a flag in local storage and based on that call the new rest api which always gives us the binary response and read accordingly.
> 
> Going with this route, the client can use the "accept" parameter in the header when making a request to specify which format can be returned. "application/json, application/octet-stream" would mean that both formats are welcome and the server would return json or binary at our discretion. If the "application/json" is requested, the server will just return json.
> 
> When we return from the server, we will specify what format in the "Content-Type" param in response header.

Might be interesting to create a specific content-type for fluid? e.g. application/fluid

**Comment by sunnyhuang2008** [comment]
One small maybe naive question: If the client is willing to accept both formats, there's no need to request us with the accept header to state which format they need since we know returning Json and Binary would both just work? @marcmasmsft @jatgarg Would it be okay if on the server side we just respond with application/json or application/fluid when client request, since we don't read which format you are requesting as we know both formats are accepted?

**Comment by jatgarg** [comment]
So only the driver with latest changes would accept both formats, not all. So previous version of released drivers would not be able to read both format.

**Comment by sunnyhuang2008** [comment]
> > Proposed design for fetching the new api as discussed with @sunnyhuang2008:
> > 1.) Server wants to support enabling the new format only for few files at server at a time and then progress slowly adding more/next files.
> > 2.) In order to support that, at client the driver can use the same api(as today) for both fetching the older json(IOdspSnapshot) format or for newer binary format. However the client would always try to fetch the binary response by specifying the Version of format in the form data of post trees/latest call.
> > 3.) Server can read that and if they want to return the newer binary format response with that version for that file, they can do so and specify a response-header saying that it is the binary response and client will read it as such. However if the server wants to send the older json response, they can do so and specify no header for that and client will read it accordingly then.
> > fyi @vladsud
> > Also if we go with this, for now so as to integrate faster, we will read the a flag in local storage and based on that call the new rest api which always gives us the binary response and read accordingly.
> 
> Going with this route, the client can use the "accept" parameter in the header when making a request to specify which format can be returned. "application/json, application/octet-stream" would mean that both formats are welcome and the server would return json or binary at our discretion. If the "application/json" is requested, the server will just return json.
> 
> When we return from the server, we will specify what format in the "Content-Type" param in response header.

@vladsud Any thoughts on client being acceptive of both formats? If it sound good, we will design our roll out plan based on this.

**Comment by vladsud** [comment]
It feels to me that we will find bugs in both client and server implementations, or maybe will adjust payload / structure based on learnings and would want to move quickly breaking things (not supported "older pre-release formats"). So we will have number of client bits in circulation, and number of server bits in circulation at the same time in different rings.

So I think the right thing to go about it is for client to clearly articulate a version (range) it it supports. If server supports exactly that version, then it can return it, otherwise it falls back to JSON.

Semantic versioning is our friend here. In pre-release versions (0.x), minor (first number) is actual treated same way as major release. I.e. 0.1 and 0.2 are not compatible. We can use it to start testing overall process (with a difference that in future server will need to support number of versions potentially, as we would not be able to deprecate that quickly already in circulation versions).

So IMHO client needs in some form clearly articulate versions it understand (it's a range), and server responds with a version in this range.

We can treat JSON as 0.1 or something, and that version is always supported, and everything else is negotiation.

Once we ship to production, that mechanism should stay in place almost exactly the same, with the following differences:
- JSON and all pre-release versions are no longer supported.
- 1.0 is the base that is in long-term support and can't be deprecated for next 3 years.
- Future changes go through same minor/major release bump and same negotiation pipeline
   - service can respond with higher minor format that client supports, as we assume minor == non-breaking.

**Comment by jatgarg** [comment]
Please do discussion related to fetch snapshot api in the new issue above this comment.

**Comment by jatgarg** [comment]
Closing the issue with PR: https://github.com/microsoft/FluidFramework/pull/7121. Opening issue https://github.com/microsoft/FluidFramework/issues/7188 to follow up with latest snapshot format improvements on server side and corresponding parsing implementation at client side.
