### ISSUE TITLE
[FluidHelloWorld] Difference in rendering dice in Chrome and Firefox

### ISSUE THREAD

**Issue by infojunkie** [microsoft/FluidFramework#4592]
## Describe the bug
Running FluidHelloWorld on Chrome and Firefox side by side results in differences in rendering the die's orientation. To be clear, this is a minor annoyance at best and is likely related to Unicode font differences in Chrome vs Firefox.

### To Reproduce
1. git clone git@github.com:microsoft/FluidHelloWorld.git
2. npm i && npm start
3. open http://localhost:8080/ in Chrome to start new session
4. copy session URL and paste in new Chrome Incognito window
5. paste session URL in new Firefox window
6. Roll die in any window until you get asymmetric result (2 or 3)

### Expected behavior
Dice show the same on Chrome and Firefox. 

Instead, they show reversed as per attached screenshots.
![Screenshot from 2020-12-13 14-00-14](https://user-images.githubusercontent.com/92977/102025391-7d10e480-3d4c-11eb-9e04-f39e849e1a69.png)
![Screenshot from 2020-12-13 13-59-44](https://user-images.githubusercontent.com/92977/102025392-7e421180-3d4c-11eb-8cba-20260260b7db.png)

**Comment by skylerjokiel** [comment]
Thanks for reporting @infojunkie . With our FluidHelloWorld example we've tried to keep it simple and this involves using native browser font to render the die face. As you pointed out it seems like different browsers represent this differently.

Since this isn't impacting the functionality, and our goal here it to optimize for simplicity, does it seem reasonable to wont-fix this issue? If not do you have a proposed solution?

**Comment by infojunkie** [comment]
Yes it makes total sense to not attempt fixing this issue. I was initially thrown off by the difference in rendering at first, so maybe a note on the README would suffice.

**Comment by skylerjokiel** [comment]
The resolution here is to add a note in the FluidHelloWorld readme noting that because the dice are ascii they can appear different depending on the browser.
