### ISSUE TITLE
IRuntime.stop() has unclear semantics in presence of local changes, delay-loaded channels

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4685]
I'm not sure what snapshot collected by this API represents.
It can not produce correct design in presence of local changes, for two reasons:
1. Snapshotting logic assumes no local changes and likely works incorrectly (i.e. behavior is undefined)
2. Even if had some definition, serialization and de-serialization would either lose local state, or rehydrate it at the state where we can't properly ack local ops.

I believe all snapshotting and summarization calls should assert that pending state manager has no pending ops it's tracking - we need to add that.

The other part that is not very clear to me is what happens with data stores and DDSs that were not loaded yet, but have pending ops. I believe stop() will realize them all, which might be very expensive.

The overall problem is somewhat similar to data loss prevention that Wes is working on, but is complicated by potential code version differences, see here: https://github.com/microsoft/FluidFramework/pull/4597/files#r548197303

I believe we can partially solve it by
1. (staging) Starting with the serialization being just latest sequence number (semantically or literally), and rehydrating container at that sequence number. No other state (including local state) is saved, we lose local changes.
2. We move to move complicated design where
   - code proposal is actually not code proposal but document data schema proposal
   - 99% cases are covered by code shipping dark, and existing code already understanding old and new data schema formats and be able to work with both (1% case results in data loss of local state).
   - We leverage data loss prevention work (Wes' work) to serialize container in old schema, and new code being able to rehydrate from it and start writing ops / snapshots in new data schema.

**Comment by arinwt** [comment]
There's a lot to unpack in this issue, but let me try to ack the distinct problems first:

1. The reload snapshotting at best case loses local state, and at worst case may corrupt state since it cannot correctly understand inbound local ops after reloading.
2. The reload snapshotting will realize every data store/DDS that has ops in their pending queue. This is relatively expensive and unnecessary for hot-swap snapshot.

I think this issue is largely mitigated from issue #4600 (PR #4723), which makes it so that new code proposals that are incompatible (using the new "satisfies" function), will call `ContainerContext.dispose()` followed by `Container.close()`, then relying on the host to handle refreshing the page and loading a new container with new code. A key aspect here is that we no longer call `ContainerContext.snapshotRuntimeState()`, meaning we never call `ContainerRuntime.stop()`.

We did add a loader option to enable hot-swapping container contexts (i.e. how it was working before), but we are just in a state of saying we don't fully support hot-swap.

Applying this refresh flow to the points above:
1. We lose local state, since we are disposing and closing. There should be no chance of corruption, since we have no pending local ops from the new Container's perspective.
2. We do not call the reload snapshot function, so we don't have this expensive wait. We do however have a page refresh, iframe swap, or something else that is likely expensive depending on how the host handles it.

@vladsud, for this issue, should we be thinking about cleaning up the hot-swap scenario? Or do we want to make changes to improve the new reload flow?

**Comment by arinwt** [comment]
After discussion, I think the resolution to this issue is to move towards deleting the code that supports hot-swap context reload for now. There will be some work to rebuilding it (i.e. keeping runtime/summarizer stable through reload), but since we aren't using it at all for now, it will become stale anyway.

This should include deleting the old `stop` and `snapshot` functions, though there might be some other lingering dependencies, we can at least deprecate them and move towards deleting them.
