### ISSUE TITLE
Update snapshot cache during long running sessions

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#4795]
The snapshot cache is only updated on the initial load of a container. This means that any edits applied by the local user or changes that came in as ops during a session will not be in the snapshot cache for the next load. We would like the ability to update the snapshot cache during long running sessions to improve the perceived performance of the next load. Ideally, we'd like for the local clients to be able to update the snapshot cache directly, but this may not be feasible due to the local client not having all the data available to generate a new snapshot. An alternate approach may be to make a trees/latest call to update the snapshot cache, but this would bring up concerns with an increased amount of data usage.

**Comment by vladsud** [comment]
In my view, this is a punt for GA. Couple reasons:
1. It's not clear that it's really benefits end-to-end flow that substantially. I.e. I'd rather see first cache being invalidated after some time (and next boot going to network), and get data on how often that happens (i.e. how many cases are there when session is long, and also very active in terms of ops)
2. Any work in this area does not accrue to user not having file opened and guessing on how much content changes in determination of duration of cache validity (i.e. use or not use cache). That's likely the primary scenario.

**Comment by christiango** [comment]
That makes sense

**Comment by vladsud** [comment]
Current state:
1. ODSP driver will cache ops up to a limit (controlled by host, default 5K).
2. When the limit is hit, it deletes all the cached info about this file and stops caching any more ops.
3. We have exposed stand-alone API to prefetch file.

So really, the only thing that is missing here is one of the two (or maybe both):
- A signal that # 2 has happened. Host can use # 3 at various points in time to pre-cache file for future.
- A method that restarts caching from scratch by re-fetching latest snapshot and resetting op counter to cache
   - We can add purging old ops from cache, but this can be done only when we get new snapshot (and thus know it's sequence number).

Do we have data that solution in this space is needed?
How often sessions last over 5K ops? We have some telemetry in this space (see "CacheOpsLimitHit" event), but I do not know how representative it is - i.e. it might be worth waiting for GA and recessing.
It would be great to be data driven here.
Also is 5K the right limit? Not sure, we should be able to rather quickly process 10K ops (again, having data here would be great).

I worry about adding even more complexity to already rather complicated driver.
At the same time leveraging only first proposal seems not interesting, as without continuing op caching it's not interesting.

**Comment by vladsud** [comment]
Oh, we can also bake some solution as a policy into driver (i.e. no new APIs). That's likely the easiest path.

**Comment by jbissat** [comment]
Vlad, if the document goes through this 5K ops then cache deletion scenario, then gets reloaded - does that second load populate the cache with the snapshot again?
Also what is the pre-fetch API, and is it being used yet?

**Comment by vladsud** [comment]
Yes, every load would refresh cache with new snapshot.
prefetchLatestSnapshot() was added recently to use minimum amount of code and be called outside of iframe, such that host case pre-populate cache with latest snapshot.

**Comment by Zlatkovsky** [comment]
@vladsud , it certainly feels like from a host's/developer's perspective, they would just want the cache to work. An eventing solution whereby a host needs to listen to "we purged the cache" event and request that cache to be filled again feels like unnecessary work on the host's part: if we fired the event and if we know how to fetch the latest cache, shouldn't we just do it for them?

So yeah, I would be in favor of the "no-new-APIs" approach, and just have the cache silently refill after it gets purged. Is there a downside to doing that?

(And of course, for 1st-party hosts that go through Office Web Host, we can of course wrap things for them so that they don't have to worry about it. But that still leaves 3rd-party to have to deal with this unnecessary cache-purge-refetch dance, which doesn't seem like a concept that they should have to worry about -- unless I'm missing something?)

Note that I'm FF Bump OCE this week, and also may be OOF for a couple hours, so probably won't be able to get back to this thread today. But am happy to discuss more -- either on the thread or briefly in person -- anytime next week or thereafter.

**Comment by jbissat** [comment]
I agree with Michael that having the host listen and trigger seems unnecessary, since we know already that they want to cache things.

FYI with the modeling I had done (not running in Fluid, but using the indexdb to push data similar to the format we use in fluid (I copied the add item code basically), if I push in parallel 100 arrays containing 100 ops each (an op being 650 bytes), it takes about 400-450ms on my dev box. If I do 50 arrays (so 5k ops total instead of 10k) it takes about 200-250ms. Is that data useful or would you prefer a different kind of analysis?
