### ISSUE TITLE
GC back compat - do not do GC on "old" documents

### ISSUE THREAD

**Issue by danielroney** [microsoft/FluidFramework#4948]
Documents created prior to all data objects storing handle references should not have the GC reference check run against them, as it will incorrectly make objects as unreferenced.

**Comment by vladsud** [comment]
The gist of this issue is that there is a lot of (mostly independent) work happening that needs to complete before
- ODSP may trust summaries and stop returning (in snapshot) some paths that are marked as collected
- We can trust it on our side and fail external URI resolution as "deleted component"
For example, app needs to represent links in file as handles.

For that, it seems like we need some kind of watermark, or marker in the file that tells all interested parties that this summary was written by client who has all the work completed, and thus info in the file can be trusted.
All the files that were created long before that (and never opened), should be ignored by these processes until we open them and regenerate summary.

This marker might be a version of container runtime, i.e. value from .attributes (or .component?) or code proposal - if possible, we should not come up with new ways of doing things.
Once we settle on what it is, ODSP needs to be notified and use it.
