### ISSUE TITLE
Errors thrown in Driver layer (resolver code) do not appear to signal to the host

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#5024]
I've observed several hosts over the past weeks hit token/driver errors for varied reasons. One thing I noticed with all of these (and confirmed with the hosts themselves) is that while there is usually a clear logged error in the console when fluid logs are turned on - usually from something like odspDriverUrlResolverForShareLink line 165: "throw new Error("Failed to get share link");" there doesn't appear to be an error bubbling up to the host. It seems like sometimes there's an attempt (logs on the console to reject promise?) to bubble up the error, but the Loader promise (likely loader.resolve) successfully completes and no container close operation happens on the returned container.

I imagine the expected behavior here for a driver error on load is for loader.resolve to reject the promise. Can someone verify why this is not happening?

**Comment by curtisman** [comment]
I see this [code](https://github.com/microsoft/FluidFramework/blob/c432b2bf390ed48d184ff10e23823138a35894f3/packages/drivers/odsp-driver/src/odspDriverUrlResolverForShareLink.ts#L120)

```
        if (odspResolvedUrl.itemId) {
            // Kick start the sharing link request if we don't already have it already as a performance optimization.
            // For detached create new, we don't have an item id yet and therefore cannot generate a share link
            this.getShareLinkPromise(odspResolvedUrl).catch(() => {});
        }
```

Looks like it is deliberate, and has no functional impact.  We probably shouldn't log the error to telemetry in that case though

**Comment by leeviana** [comment]
The thing about this error is it always precedes an actual driver connection error with joinSessions/tree/latest/push or something else failing and the container floating around in a "not connected to anything" state but not closed. Maybe it has to do with our handling of the link later on down the pipeline and we should throw there and not exactly here.

**Comment by curtisman** [comment]
@leeviana  can you be more specific?

From telemetry, when I search for `Data_error == "Failed to get share link"`, they all comes from `ContainerClose` events.
When I search for `Data_eventName containes "FluidFileUrlError"`  all the session that I see get to `ContainerClose` pretty quickly.

Please let me know if you have a repro case, or SessionId when that happen, otherwise, it is impossible to guess what situation this is referring to.

**Comment by curtisman** [comment]
@leeviana I have a theory of what you are describing.  The design for the loader is to return back a `Container` as quickly as possible.  However, because the loading process kicks off a lot of asynchronous tasks that are not waited on by `loader.resolve`, error in these async tasks will not be reported as error in `loader.resolve`.  Instead, these tasks closes the container when there are critical failure if the container can't continue. 

So it is possible that when the result or `loader.resolve` returns back, the container is already closed (before your event listener can have a chance to register).

To verify this theory, you should add code to check if the container is already closed when you register the event listener.

**Comment by leeviana** [comment]
I asked Teams to check this last time I saw this failure pattern and they told me that the container was not already closed when they received it. The registration of the event listener happens in host code, not in any FFX code :)

**Comment by leeviana** [comment]
I notice that we have a setInitializedState in our IFrame proxy to get some initial values for the container across faster. I can see about adding "closed" to that which may ensure we give a more accurate signal to hosts. I don't think this will be perfect as there still always will be some delay between the container coming back from the loader vs the host registering the close signal but maybe it will help out hosts a bit given your theory?

**Comment by jatgarg** [comment]
These are the results for measuring this error. 
Data_hostName	count_
Fluid Preview App	12
OneNoteMeetingsDefaultTab	1442
Outlook_Web_App	48
Office.com	5
Microsoft Teams Web	3
All these errors happen when we are attaching the container as I looked in Kusto. The container states were all "attaching" as we call getAbsUrl during that.
Ruchika brought this error up from OneNoteMeetingsDefaultTab and we figured out that they were having this issue because while attaching when they move away from meeting tab and we get fetch error 710 due to that and they then log this. as they don't dispose the tracker. This is also inline with the findings.

Currently ruchika is on plan to fix the logging logic at her end. We also added the share link retry logic in last version,
Next we are planning to retry attach logic at loader layer based on retry policies set by the host/app so that every host/app does not need to worry about this.

**Comment by jatgarg** [comment]
So as state in my previous comment, all this was happening during attach, we have this issue opened here to add retries to attach in loader layer itself so that every host does not need to bother about it.
https://github.com/microsoft/FluidFramework/issues/5615
Also these are no substantially reduced from above stats due to OneNote fix(as they had specific scenario) and due to retries in share link fetching.
So closing this issue.
