### ISSUE TITLE
SharedTree: Introduce dense integer 'ShortIds' for addressing nodes

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#5091]
## Work Item
This work item describes the design and plan for replacing random UUIDs with integer 'ShortIDs' when referring to tree nodes in memory, in ops, and in summaries.  Because UUIDs are currently represented using heap allocated strings (40+ bytes per node), we predict a reduction in memory use and immediate and future speedups due to faster key comparisons and denser locality.

**Approach**
When processing an ACKed 'build' op each client assigns the next available ShortId, thereby trivially reaching consensus by virtue of Fluid's total order broadcast.  Delaying ID assignment until ACK is not a problem for clients processing the op remotely, as they learn about the existence of the node and its ShortId simultaneously.

For the local client that produced the ‘build op’, however, this delay creates an unbounded window in which the client may need to refer to the node (e.g., in a subsequent ‘insert op’) without yet knowing the node’s ShortId.  To address this temporary gap, newly created nodes are assigned a ‘temp id’. Like the ‘short id’, a ‘temp id’ is also an integer index distinguished as being temporary via its sign (e.g., temp ids are negative, short ids are positive.) 

Build ops communicate the temp Id of newly inserted nodes to remote clients who add it to a per-client table that is used to map the remote client’s ‘temp Id’ to the final ‘short Id’:

```
    (ClientId) -> (tempId) -> shortId 
```

Once the local client that produced the build op receives and processes the ACK from the Fluid server, the producer is required to refer to the node by its ShortId from that point forward.  (This allows remote clients to drop the tempId from their tables once the remote client has processed its ACK... more on this later).

Client’s assign ‘temp Ids’ sequentially starting from the last known ‘shortId’ (effectively making the ‘temp Id’ an educated guess at the ‘short Id’). This has two advantages: 

1.  Remote clients can defer creating a table entry until the producer begins "guessing wrong". 
2.  Because 'temp Ids' are sequentially allocated, groups of 'temp ids' that map to contiguous ranges of 'short Ids' can be compressed to single delta.

For Example: if the remote client observes creation of node 205 with 'temp id' -203 it would insert the following into the client’s table: 

```
    startId: [ -203 ]
    delta: [ +2 ] 
```
When node 206 is created by the same client with 'temp id' -204, the delta is still +2, so there is no need to update the table. However as ops continue to stream in, we observe an interleaving that changes the delta (node 223 is created with 'temp Id' 210) and update the table as follows: 

```
    startId: [ -203, -210 ] 
    delta: [ +2, +13 ] 
```

(Note that a circular queue/ring buffer is a natural data structure for storing the rows.)

Columns can be removed from the table when two conditions are true: 

1.  The client has processed an ACK for all 'temp Ids' represented by the column (we can tell by either minSeq# or by examining the refSeq# of later ops from the client.)
2.  The column has been captured in a subsequent snapshot after condition 1 has been met. This ensures that a client can retrieve the table information if they need to traverse the history in reverse.

One strategy is to track just the seq# of the most recent node inserted into the table and drop the entire table once the producer has "caught up".  (Another is to track a seq# per column and drop columns individually.)

Finally, because Fluid clients “box car” batches of outgoing ops we expect interleaving to be somewhat infrequent and the number of columns to stay relative short, in which case it may be a win to interleave the table rows into a single array and use a specialized binary search to find the column by examining items at multiples of two: 

```
    [-203, +2, -210, +13] 
    ^-- head     tail --^ 
```  

**Open questions**
While 'ShortIds' are densely allocated, they are not recycled in order to allow history/branching to continue to reference old nodes with their original 'short ids'.  This means that this design still requires a sparse mapping from 'short Id' -> physical storage.  Can we do better?

**Comment by CraigMacomber** [comment]
At least as things are, this would cause some issues. The current design depends on having identities for nodes which are known, and stable, from before they are inserted into the tree.

For example, we depend on being able to create an identity of an object which might get inserted into the tree (currently as a uuidv4), and then at a later point in time, maybe insert it into the tree with that identity.

We also expose APIs that allow users of the tree to directly observe the identities of nodes. These identities are allowed to be passed into places outside the control of shared-tree where it will not be able to fix them up when they are finalized (for example be used to derive identities of objects within out application, and to encode references between them).

This means that there are cases there the node identities are included as part of data-structures that would be impractical to update (operational transform style) when we need to adjust them, due to those data structures either being outside the control of shared-tree, or being placed into the shared tree in ways that are impractical to update (ex: application logic can get these identities, and store them as data in the tree without shared tree knowing: this is our plan for how to implement some references between items).

One other example of data that would be very hard to fixup for adjusted ids is constraints ( https://github.com/microsoft/FluidFramework/blob/8b0ede92971ef19ce6cd1a64add9218d2ab731ec/experimental/dds/tree/src/PersistedTypes.ts#L144 ): We plan to put hashes of trees, and hashes of sequences of ids into constraints. This particular case is within the scope of shared-tree, so we could theoretically adopt a constraint API that made this update possible (I can't think of a good one), but this approach would not work in general for usages of these identity outside of shared tree.

Thus I think it would be difficult to support out existing scenarios if we used temp ids.

**Comment by PaulKwMicrosoft** [comment]
Here's a proposal that might address all concerns:

Based on discussions with Craig, Daniel and Taylor, it is desirable to assign a UUID to each node at the moment it is created, so that this can be used offline or before a sequenced change is received from the Fluid server. The design below provides this guarantee, while avoiding the assignment of multiple UUIDs to the same node, and supporting a consensus assignment of ShortID aliases for the UUIDs within a document that will typically remain under 31 bits in length and can therefore be implemented efficiently in JavaScript engines.

Summary

The central idea is that each client chooses a UUID base that it will use for all created nodes in a session editing a document (or, potentially across multiple sessions editing that document). New UUIDs are created by simply incrementing an offset from this base. Once edits have been sequenced by the server, all clients can deterministically map contiguous ranges of these UUIDs into clusters of ShortIDs. ShortIDs are reserved in blocks to ensure that interleaved edits do not cause too many clusters to be created.

Algorithm
 
Each client picks a UUID when a document is opened (which may or may not persist between sessions). It transmits this to other clients (perhaps with every change, for simplicity).

All clients in a session agree on a block size (this could simply be hard-coded to a fixed value, e.g. 2^8).

Each time a client needs a new identity, an offset from its local base UUID is incremented. This can also serve as a local ID, and can be encoded as a negative number to distinguish it from a permanent ShortID. See main text above for details on how a map between local IDs and short IDs can be efficiently maintained. Local IDs are transmitted to other clients, but they can immediately convert them to ShortIDs upon receipt. So, each client is effectively transmitting UUIDs to other clients.

Each client, as it sees sequenced edits from the server, assigns a permanent ShortID to each created node, but it does so in a very specific way: 
 
•	The first time it sees a particular UUID range, it allocates a block of short IDs. 
•	It also creates a cluster record, storing a base UUID computed to let the allocated short IDs produce the desired UUID range when used as offsets. 
•	When a given block is full, a client must allocate a new block and, if the two blocks aren’t contiguous, create a new cluster record. 
•	Each client maintains a binary-searchable UUID=>ShortID map that has one entry for every cluster record.
•	The ShortID 0 is reserved for use as a null value.
 
The following shows an example. The details of local IDs are omitted, since UUIDs are effectively being transmitted. The “UUIDs” shown below are obviously fake and are chosen for readability, and a block size of 2^8 is assumed.

Client A transmits identity 0x1000001000 
              All clients start a cluster beginning with ShortID 0x100, with UUID base 0x0x1000000F00, add a ShortID=>Node map entry for ShortID 0x100 
Client A transmits identity 0x1000001001 
All clients add a ShortID=>Node map entry for ShortID 0x101 
Client B transmits identity 0x2000001000 
              All clients start a cluster beginning with ShortID 0x200, with UUID base 0x0x2000000E00, add a ShortID=>Node map entry for ShortID 0x200 
Client A transmits identity 0x1000001002 
All clients add a ShortID=>Node map entry for ShortID 0x102 
Client B transmits identity 0x2000001001 
All clients add a ShortID=>Node map entry for ShortID 0x201 
… 
Client A transmits identity 0x1000001100 
              All clients start a cluster beginning with ShortID 0x300, with UUID base 0x0x1000000E00, add a ShortID=>Node map entry for ShortID 0x300 
Client A transmits identity 0x1000001101 
All clients add a ShortID=>Node map entry for ShortID 0x301 
 
Note that while all of Client A’s UUIDs are contiguous, they are stored in two clusters with distinct UUID bases.

Some notes: 
 
•	If Client B hadn’t created any identities before Client A reached identity 0x1000001100, there would be no need to create a new cluster. I.e. 256 isn’t a limit on cluster size, it’s just the block reservation granularity. 
 
•	If a client needs to create a contiguous block of identities for virtual nodes (e.g. a long ink stroke), and those won’t fit in its current block, then a new cluster will have to be started (but, given the above point, there’s no problem if it needs to create >256 virtual nodes at once, as multiple contiguous be blocks can be allocated simultaneously).

•	Clients can also reclaim space within blocks if it there is confidence that it will never be used (e.g. Client B appears to have left the session). Even if a client rejoins the session, there is no significant harm done if the remaining space in a block started for its UUIDs has been reclaimed, all clients simply start a new block for its latest UUIDs, and there are a couple of clusters that are smaller than the block size.

•	If ShortIDs exceed 2^30 (on 32-bit platforms, remember that these are signed integers) or 2^31 on (64-bit platforms), the only downside is that the JavaScript engine will start using a slower implementation for these numbers.

•	Anytime an offset is added to a UUID, to avoid occasionally corrupting UUIDs we must either a) do 62-bit modular arithmetic or b) discard client base UUIDs with trailing 62 bits that are “close” (e.g. within 2^53) to 0 or 2^62-1.
 
Larger block sizes mean fewer cluster records, but that we eat through ShortID space more quickly (assuming no reclamation). Assuming the goal is to keep ShortIDs within a document below 2^30, then the worst-case scenario with a block size of 2^8 is exceeding 2^23 sessions contributing one identity each to a single document. 8 million seems pretty high, so a block size larger than 2^8 might be appropriate. One motivation for a larger block size is virtual nodes, especially since we need to keep the entire cluster map in memory even if only a portion of the snapshot is.

Benefits

•	Full offline support with stable UUIDs, requiring no special protocols for transmitting offline work
•	Each node has exactly one UUID for all time
•	In overwhelming majority of documents, ShortIDs can be implemented as small integers in JS engines

**Comment by DLehenbauer** [comment]
@PaulKwMicrosoft, @CraigMacomber, @taylorsw04 - Thank you for your help in finding a good "local maximum" in the design space.  This is really excellent work!

**Comment by DLehenbauer** [comment]
Hacking the latest SharedTree to replace UUIDs with randomly assigned Int32s yields a 2x speedup (~30 -> ~60 bubbles):
```ts
export const nodeId = () => ((Math.random() * 0x7fffffff) | 0) as unknown as NodeId;
```
36% of time still spent in BNodeInternal.get(), almost exclusively via getSnapshotNode.

**Comment by DLehenbauer** [comment]
(Actually, this work is going to land soon.)
