### ISSUE TITLE
Client can hold collab window for very long time on reconnecting as "write"

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5150]
While working on https://github.com/microsoft/FluidFramework/pull/5104, it became obvious to me that our logic around DeltaManager.active state handling is not ideal.
Specifically, this issue should track the following non-ideal situation:
Client that is connected as "write" but is not yet up to date (i.e. non-active, processing ops until it sees its own join op) is in situation where
1. It can't reject quorum proposals
2. But it also does not accept them right away (by sending no-op).
3. Most important, it holds collab window, and can do so for very long time (catching up after being offline for 2 weeks).

I think we should fix by allowing noops to be sent automatically in this state. I.e. change the logic in scheduleSequenceNumberUpdate() to not check for active, but for write connection.

This currently fails one test, so someone need to take a look at why and if this test is wrong or there is indeed some issue with such proposal.

**Comment by curtisman** [comment]
I think this is by design? If the proposal is before it's Join message, then the client can't do any thing about it.  The fact that we are holding the collab window until we get the Join message is so that proposal after it can still be rejected as needed. 

 If we allow the min sequence number to advance beyond the Join message, that also means that we will have to keep being "inactive" until it can catch up to that new min sequence number that we have allowed (by sending the NoOp).  We need to make sure that this converge and the new client will get into the collab window in a reasonable time.

**Comment by vladsud** [comment]
We could allow MSN to advance up to our own join message. I.e. change logic in scheduleSequenceNumberUpdate() not to check "active" connection, but only "write" connection. In other words, send noops every 2 seconds as we inbound ops and are not active on write conneciton.

**Comment by curtisman** [comment]
Ah.   I assumed that since a client shouldn't send ops before it's own Join message, the server could have assume and enforce it.
Alas, just checked the code right now, and it doesn't seem to be the case currently.

https://github.com/microsoft/FluidFramework/blob/b582d10944dc3c0841223c9c5337ea396768f7ec/server/routerlicious/packages/lambdas/src/deli/lambda.ts#L262

The question is should we change this so that the server would assume refseq of a new client starting from it's `Join`'s seqnum, so that the client doesn't need to send `NoOp` unnecessary. @tanviraumi

**Comment by curtisman** [comment]
Separately @tanviraumi  I  think this assert need to change into a `Nack`.

https://github.com/microsoft/FluidFramework/blob/b582d10944dc3c0841223c9c5337ea396768f7ec/server/routerlicious/packages/lambdas/src/deli/lambda.ts#L329

It looks like a bad client can bring down the server by regressing the refseq.

**Comment by vladsud** [comment]
I think server should be simple and not care about these things (as much as possible). The only thing it should care is timeouts - it should disconnect client if it did not see an op from it for a while.
Client can do the rest.
The only reason I did not address it right away is that we have some dependency on existing behavior in our tests and a bit more digging is required :)

**Comment by vladsud** [comment]
I've forked assert -> nack issue into https://github.com/microsoft/FluidFramework/issues/5154

**Comment by curtisman** [comment]
> I think server should be simple and not care about these things (as much as possible). The only thing it should care is timeouts - it should disconnect client if it did not see an op from it for a while.
> Client can do the rest.
> The only reason I did not address it right away is that we have some dependency on existing behavior in our tests and a bit more digging is required :)

Yeah, but the initial refseq for a new client should be a server policy (since the server assigns it), I think this could be a rule for protocol that a client can't generate op referencing seqnum before it's Join op.  

Nevertheless, it can't send NoOp before it process up to the minseq number on the `Join` op, right?  Otherwise, it will regress the reqnum that the server assigned.  Does the client know what the minSeq number that it is allow to start generate ops before it process the `Join` op anyways?

**Comment by vladsud** [comment]
Hm, you are right, MSN is likely near or at our own join op, so we can't send noops for most of the time we are catching up.
At least not with ref seq number of the currently processed op (which can be weeks old). It does not really matter that much if we can't send ops till our join op or current MSN - they should be very close (unless there are other clients behind that are catching up :)) Given that process of catching up can take minutes, it's a challenge.

I think there are couple ways to resolve it:
1. Server to reduce substantially timeout for how long it allows a client to hold MSN. This will result in pushing out reconnecting client from quorum, and it will keep trying to reconnect, and will eventually succeed when it's close to being up-to-date at connection time. I.e. the goal here is to ensure that MSN moves with some reasonable speed that does not block things like version upgrade to be minute-long process.
   - we could also make DeltaManager delay reconnection on web-socket if gap between last known sequence number and current is above certain threshold (like 10K ops), thus reducing number of useless connections that are going to be nacks with timeout.
   - (instead) After an hour of not having connection to web socket, we could also stop attempts to connect to websocket until fetching ops from storage succeeds and we process all the ops that we receive that way. This will ensure we are rather close to being caught up, while not changing any other invariants of the system. This would solve all offline cases, but would not solve a case of loading from very old cached snapshot which is way behind. Logic could be adjusted to be either offline time or number of ops we are behind (as we will learn on first reconnection of how far we are behind).
2. Container to send no-ops with ref seq number of some latest op (on socket) and delay raising "connected" event to runtime till we process such op,. Later part will not be much different form the code we will add as part of https://github.com/microsoft/FluidFramework/issues/4399 where we need to wait for our previous leave Op before letting client switch to connected mode.

**Comment by vladsud** [comment]
I'm inclined to keep this issue alive. I worry as we change designs (like https://github.com/microsoft/FluidFramework/issues/5629 - "Reconsider noop coalescing"), issues that relatively low impact might grow in impact. For example, today, client does not reject or accept any proposal that is sent right before new client joins as "write" (that happens to be within collab window of such new client, but before its join op). Today, it sort of resolves with non-immediate noops, but if we change their frequencies or eliminate them, then this issue because more severe (though worth pointing out that today we usually connect as "write" if client is about to send some op, so it usually lifts collab window by doing so).

I think Curtis suggestion for client to have ref seq number = join op seq number seems like good starting point here.
It does not address the duration of catch up, but at least it keeps system correct.

I think there are a lot of benefits from raising "connected" event for "read" connection only after client caught up to last known op to it (IDocumentDeltaConnection.checkpointSequenceNumber). That way transition to "write" in most cases would be very fast. It would also reduce the need for clients to do the same (in various workflows, where we use it as a workaround for various limitations).
