### ISSUE TITLE
Assert in lambda.ts should be changed into nack

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5154]
Forking from https://github.com/microsoft/FluidFramework/issues/5150#issuecomment-779821054

Separately @tanviraumi  I  think this assert need to change into a `Nack`.

https://github.com/microsoft/FluidFramework/blob/b582d10944dc3c0841223c9c5337ea396768f7ec/server/routerlicious/packages/lambdas/src/deli/lambda.ts#L329-L331

It looks like a bad client can bring down the server by regressing the refseq.

**Comment by tanviraumi** [comment]
Good catch! Turns out the assert was unnecessary since we are already nacking the client here (https://github.com/microsoft/FluidFramework/blob/b582d10944dc3c0841223c9c5337ea396768f7ec/server/routerlicious/packages/lambdas/src/deli/lambda.ts#L295)

Raised a PR https://github.com/microsoft/FluidFramework/pull/5163

**Comment by tanviraumi** [comment]
#5163

**Comment by curtisman** [comment]
@tanviraumi  What if I have a `NoOp` and refseq === -1?  Seems like that would get the client into a bad state right after the assert.

**Comment by tanviraumi** [comment]
Good catch! Forgot the no-op case. I am thinking more about it. The "-1" check was to support "REST API" where a client has no idea about its refseq. However, it also enables the client to fake its "reference sequence number" and join as most recent. Do you think it can introduce a problem? I think the answer is no (cause client can fake anyway) but wanted to double check.

**Comment by curtisman** [comment]
That's probably fine.  The one rule that the server need to enforce is that msn always march forward.   So refseq that get upserted needs to be always >= msn, and Nack otherwise.

It is weird if the client's ref seq number jump backwards, but as long as server nacks them if it falls below msn, then it would only cause problem for that client.   So I don't think the server need to enforce it (that refseq needs to be always equal or larger then the last one from the same client)

For the client that doesn't care about refseq/minseq, then using -1 is perfectly fine.  It is just the client tell the server don't keep msn for other client.  All these ops doesn't need those information to be interpreted.

**Comment by curtisman** [comment]
Reactivate to track the  NoOp and refseq === -1 issue

**Comment by tanviraumi** [comment]
Makes sense. I am allowing client to send no-ops with reseq -1. We don't want to nack the client after the sequence number is rev'd. So if the client does not care about refseq number, we use the current sequence number. The earlier check will prevent any refseq < msn, unless its -1. If client sends -1, we update to current sequence number.

https://github.com/microsoft/FluidFramework/pull/5169/files

**Comment by curtisman** [comment]
Closing after fix in PR #5169
