### ISSUE TITLE
Scheduler / leader election needs to be optimized

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5292]
Analyzing Chapter 2 file size.
There are too many ops coming from scheduler:
op/op/write ([_scheduler]/2f17378a-2220-4631-aca7-66d0c3351dd1) 13,702   6,518,843

That's a lot of ops, even though it's roughly 50% over number of joins in a file.

Looking at data, two things are obvious:
1. We always go through null (i.e. separate op) before sending another op to try to assign leader to self.
2. Clients send ops (attempt to assign leader to self) even when they already know it will fail. I.e. their reference sequence number is already high enough to include the op from another client who already became leader.
   - this one is weird, we should be sending ops because some signal told us old client is not there any more. At the same time both reference sequence number and lack of null transition for such client suggests that it already knows someone else grabbed it, why it is sending an op?

**Comment by jatgarg** [comment]
Moving it to April due to OCE for last 10 days of this month.

**Comment by jatgarg** [comment]
So one of the pitfalls in scheduler that I found was that should be causing lot of op traffic was that lets say we have 10 client in a document and the current leader leaves, then all the other 9 clients would send "null" for all tasks assigned to that client in order to make it available to other clients. 

Sol: I am thinking of adding some randomization on "removemember" task in scheduler where instead of clearing that task immediately, each client would wait for random amount of time from lets say 0..100 s and then if its sees that task is still assigned to the member who has left then only it will try to clear the tasks. That way all members will not try to clear the tasks and we would significantly reduce the op traffic related to leader.

**Comment by vladsud** [comment]
Correct me if I got it wrong, but I believe that (based on memory)
1. All clients would send null, and then send their own clientID attempting to own that task. So that's 2x traffic required.
2. When client is catching up and processes a bunch of ops, for each leave op that lost leadership it will send null, when it can avoid it and send it only when it gets connected.

So I think these are the two places where we could optimize.

I agree with your statement as well, that's how most routers / hubs operate on network to avoid collisions. But I think there is a difference here - the latency for op roundtrip is high enough (~60ms on average, last I checked), where randomization would need to be over a second or so, and that would start to impact SLA. We might want to do it, but I'd first figure out what's the best we can get out of it without randomization.

Also note there are other possibilities. For example, we can say that the oldest client in quorum (at the moment when leave op for other client was generated) is responsible to take action and assign a task to one of the clients. When this client dies, next client picks up the task of reassigning. This would eliminate most of the traffic, but needs to be designed very carefully to ensure that system always settles down to right state despite all the churn and possible timings of clients leaving (newly assigned client maybe on the way out, and his leave might sequence before task is assigned to it).

**Comment by ChumpChief** [comment]
You can probably skip the null write altogether by adding a little more client-side logic.  There's no public exposure of the assigned clientId for a given task, so there's no real penalty for leaving a stale clientId in the CRC (all clients can calculate that it's stale on the client side and treat it as equivalent to null).

**Comment by jatgarg** [comment]
@ChumpChief I think we cannot leave stale clientId in the CRC as it has to be reassigned to a new client.

**Comment by jatgarg** [comment]
@vladsud For your second point, as I can see when we receive removeMember event we only send null when the client is Active.
One problem that I see with oldest member being assigning tasks to other clients is that then it should now whether that client wants to run that task or not. Although I agree that it can at least send null and then all client won't have to send null. 
In my PR, I am trying to straight away apply for leader task instead of sending null for the task.

**Comment by vladsud** [comment]
What Matt is saying (I think) is that there can be an "interpretation" layer on top of DDS that replaces (in its projection to next layer only) all clientIDs that are not in quorum with nulls. That way there is no reason at all to send nulls, as every client would have same interpretation layer and would instantly get that same message that it became null.

And yes, you are correct that either knowledge should be spread out (i.e. capabilities of clients known to all), or oldest client either takes it or assigns to null, allowing other clients to participate.

I think your PR is good enough here, it cuts traffic in half. We will simply keep monitoring and may come back later again here :)

**Comment by jatgarg** [comment]
oh okay. Got the point now. Thanks for explaining.
Yes, makes sense for this issue. Will close the issue with above PR and then we can analyze later.
