### ISSUE TITLE
Consider tracking build version of LoggingError class at runtime

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5544]
Note - mismatch in LoggingError versions is definitely a possibility (with errors from driver & runtime reported by loader). But it's trivial to detect - we can make LoggingError class report "telemetry version" it's from (i.e. version of package where LoggingError class is), and thus this code can easily figure out if it comes from future or past (only future is a problem).

_Originally posted by @vladsud in https://github.com/microsoft/FluidFramework/pull/5308#r595635838_

**Comment by curtisman** [comment]
Can you elaborate why we want to detect this mismatch?

**Comment by vladsud** [comment]
There are couple complications around how logger composes into layers.
1. Tags on logger properties becomes public API / compatibility surface.
2. Different parts of eco-system change with different speeds, and thus will use different version of logger with different tags (and meaning)
3. Loggers compose (i.e. child loggers), and they may be coming from different versions (due to # 2 above), and thus certain assumptions might be broken (that only known tags are used).

version of logger might be useful for case of keeping # 3 asserts (validation of invariants) but softening them if loggers on the stack are coming from different versions. We might also chose (that would be bad, but it's an option) to send logs to /dev/null if there is unexpected pairing of versions (i.e. version pair we do not support for simplicity), We would lose logs, but if that covers 1% of logs, but potentially opens a hole for PII data to go through, we might chose to go that path (not that we could drop properties, not whole events, still leaving some room to be able to see and diagnose problems).

It's not well thought through plan, but adding details to allow us brainstorm.

**Comment by markfields** [comment]
The way I wrote the code is just to say any unknown/future tag gets scrubbed. And I added test coverage to ensure existing tag values aren't changed in future (you have to add a new one Id you want different semantics than the existing ones)

Doesn't this solve it?

**Comment by markfields** [comment]
And when we move the handling of tags to the host, we can recommend they do the same. And we could even have them indicate in their `ITelemetryBaseLogger` that they support tags, and we can check that property before processing tags and scrub if that flag isn't set rather than passing tagged data.

**Comment by markfields** [comment]
@vladsud I propose we close this based on my last two comments.  Or do you still have concerns?

**Comment by vladsud** [comment]
I think that's fine, but I have a feeling that we need to move scrubbing out to host sooner than later (maybe separate issue to track it?).
Consider scenario where our (FF) logger is sandwiched between 3rd party DDS / data store that extends tags with 3rd party tags and 3rd party host that handles those tags.
This feels similar to extensibility of errorCodes, where each layer is free to create their error codes and all we promise that it's a string, and you use that version of driver / loader / runtime, then you know full set, otherwise you do not and should expect unknowns.

**Comment by markfields** [comment]
@vladsud Issue #5560 is already tracking the update to `ITelemetryBaseLogger` that would move tag handling to the host.

**Comment by markfields** [comment]
After further discussion, we are updating the tag to be `string` (see #5962) so that should ameliorate this specific compatibility concern.  Consumers of the tags may choose to import an enum from one package or another that they believe has been used to tag props, but it won't be enforced in the type on the API.
