### ISSUE TITLE
Add documentation on deployment

### ISSUE THREAD

**Issue by flvyu** [microsoft/FluidFramework#5611]
### Issue Category

- Missing page/section/topic

**Background**
There are some open questions around how to deploy Fluid apps to production. Right now, there exists a couple posts that explain what is needed to get a Fluid app deployed to production with Tinylicious, but I'm still not sure how to deploy with Routerlicious. Other users are having the same questions.

Here are two open questions from users on StackOverfow:
- https://stackoverflow.com/questions/66649787/how-to-deploy-fluid-framework-app-into-azure-app-service
- https://stackoverflow.com/questions/64151496/how-to-deploy-the-fluid-server

**Proposal**
1. I propose we add a section to the documentation that offers step by step guides on how to deploy fluid apps to production with Routerlicious and Tinylicious. This will be very beneficial because it will reduce/remove the ambiguity around deploying Fluid apps and make it less of a blocker for developers to work or continue working with Fluid.

I don't know if this is possible, but right now we have to load our apps from a package or CDN, but maybe this section can also explain how to deploy apps so they don't have to be loaded like this. 

Here are some issues I encountered with the current method.

-  If I don't put my app in a CDN or package I was not able to deploy it.
- App code is not obfuscated or minimized,
- Docs says Tinylicious is not secure and should not be used in production apps

2. _Update Kubernetes ReadME_
As part of this effort we should also update this [README](https://github.com/microsoft/FluidFramework/tree/main/server/routerlicious/kubernetes)

There are a few issues I see with the steps in this ReadME.

1. The container mentioned is private and adds an extra step to the process. If this can be made public it would make deployment easier.
2. We can move the Routerlicious helm chart into a public Github pages site so users don't have to download the Fluid Framework repo to their machine.
  - Something like: https://kurtb.github.io/charts
3. I could not get the step about using generateChart.js to work because the tools directory is not available anymore.
4. It is also not clear what we need to do once someone is able to get Routerlicious deployed via a helm chart.

Let me know your thoughts on this. I'm down to help put this together and testing out some deployment methods.

**Comment by skylerjokiel** [comment]
Hey @Flavyoo thanks for reaching out. As you've called out, we currently do not actively support any production scenarios around using the Fluid Framework.

The Tinylicious service is designed for local development and prototyping. The Routerlicious service is designed to be a reference implementation service. This implies that it has the characteristics/properties of a production Fluid Service but it is not in the shape to be used in any production capacity. Because we don't believe the Routerlicious service should be used in production scenarios we have not added collateral around how to deploy and manage the Routerlicious service.

Delivering a production scenario with Fluid is something we are actively working towards. We are currently working to bring a production Fluid Service to developers through an Azure offering.

If you are looking to standup just Routerlicious locally you can find the Docker containers on docker hub. https://hub.docker.com/search?q=Fluid%20Framework%20Reference%20Service&type=image

It looks like you've called out a collection of smaller issues. Some technical and some documentation. Do you mind logging these individually so we can address/prioritize each.

**Comment by Flavyoo** [comment]
@skylerjokiel Sure, I can create separate issues for the things I mentioned.

What I can do is try to setup the Routerlicious in a production scenario and then try to deploy a Fluid app using it. If I can get that working, maybe we can use it as an initial Tutorial for others to get their Fluid apps deployed.

Any ideas when that Azure Fluid Service will be available?

**Comment by celsoaguiar** [comment]
I'll second @Flavyoo's request. I've been working on a POC of a collaboration mapping app here in my company and when the time comes to show it to stakeholders I'll have to settle for a demo using my localhost only. It would be way more compelling if I could present it inviting others to play with the app from different places in the world in our Teams meeting. Having some documentation of tinylicious deployed in GCP, for example, would have solve my problem.

**Comment by skylerjokiel** [comment]
@Flavyoo , @kurtb has a blog post about deploying and running a Fluid Service you can use as a reference. https://medium.com/@kurtberglund/deploy-and-run-your-own-fluid-framework-service-8c82294e74b7 . I would love to see more blog posts and progress in this space but unfortunately the team is not currently committed to providing a self deploying flow.

The Fluid Service running on Azure currently doesn't have a release date but we are currently working through all the steps to get it to a Public Preview.

@celsoaguiar , this is a good callout scenario. Do you think [ngrok](https://ngrok.com/) support in tinylicious would unblock your scenario?

**Comment by celsoaguiar** [comment]
> @celsoaguiar , this is a good callout scenario. Do you think [ngrok](https://ngrok.com/) support in tinylicious would unblock your scenario?

thanks for the response. not sure, from what I understood one of the issues was getting letsencrypt to work in gcp, but there were other issues. what advantage would ngrok give us?

**Comment by celsoaguiar** [comment]
I see, 

> Temporarily sharing a website that is only running on your development machine

definitely

**Comment by Flavyoo** [comment]
@skylerjokiel Can you explain why Routerlicious is not sufficient for production scenarios?

**Comment by skylerjokiel** [comment]
@celsoaguiar, there are two parts to the service. There is the service itself and the client-side driver that knows how to point to the service. For Tinylicious we have the service hardcoded to a specific localhost port and we have the driver talking to the same port. For ngrok to work we would need to update the Tinylicious driver to support a custom url so you could specify your ngrok endpoint. @SamBroner @tylerbutler 

@Flavyoo , currently we don't have any SLAs around performance, reliability, or maintenance of the routerlicious service. Since it's designed to be a reference we want to provide transparency in how we believe a service could be designed but we currently don't have the bandwidth to support deployment or provide direction.
