### ISSUE TITLE
ContainerRuntimeFactoryWithDefaultDataStore is not assignable to parameter of type 'IRuntimeFactory'.

### ISSUE THREAD

**Issue by phanivaranasi** [microsoft/FluidFramework#5648]
I followed same brainstrom example but while developing I found with below issue
Argument of type 'ContainerRuntimeFactoryWithDefaultDataStore' is not assignable to parameter of type 'IRuntimeFactory'.
  Types of property 'instantiateRuntime' are incompatible.
  

https://github.com/phanivaranasi/hello-world-react-fluid

above is my repository

**Comment by tylerbutler** [comment]
@skylerjokiel This seems like a bad bug. Can you take a quick look?

**Comment by skylerjokiel** [comment]
@phanivaranasi , you don't have a "package-lock.json" checked in but I see you are using the caret in your package definition. Can you try hard coding your package version to a specific version (Ex. `^0.36.0` to `0.36.1`) remove your package-lock if you have one and see if this resolves your issue.

**Comment by phanivaranasi** [comment]
I have mentioned my repository details as well, kindly could you fork and look into it.
https://github.com/phanivaranasi/hello-world-react-fluid

**Comment by tylerbutler** [comment]
@phanivaranasi Thanks for reminding me about your repo. You mentioned that you based your code on the brainstorm sample. Is this the one you're referring to? <https://github.com/microsoft/FluidExamples/tree/main/brainstorm>

If so, then I think the problem is that the package versions you're using do not match the ones in the brainstorm example. When I update the dependencies in your package.json to `^0.33.3` like in the brainstorm example (which will actually install `0.33.5`, but that's OK because they're compatible), then the error about incompatible types is fixed.

Unrelated to this issue, I suggest committing your package-lock.json file to Git so it's possible for others to reproduce the state of your project.
