### ISSUE TITLE
Provide APIs to construct handles that contain 2 parts - base that points to GC node, and tail that participates only on object resolution

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#6001]
Today, `IFluidHandle` is a reference to a fluid object. They are used to serialize the fluid object and they participate in GC. We need another lightweight handle (extended fluid handle) that is not a reference to a fluid object but to an object / path within the fluid object.
This extended handle has an underlying IFluidHandle and a relative path within the fluid object. For getting the object referenced by the extended handle, get the fluid object from the IFluidHandle and then request the relative path from it. For serialization and GC purposes, we use the underlying IFluidHandle.

For example, lets say a data store represents a database. Then for a query like "Get me the names of all people starting with the letting A", one could create an extended fluid handle which has a handle to the data store and the query as the relative path. In this case, we don't want this handle to participate in GC and we only want the IFluidHandle to the data store to be serialized.

**Comment by agarwal-navin** [comment]
@vladsud FYI. Can you please add / update the description as required.

**Comment by vladsud** [comment]
I think a bit more background is due :)

Handles provide mechanism to aid with serialization. They make it possible for a graph of objects to be serialized and restored (loaded) on remote machines - that's their primary purpose. In addition to that, handles are participating in GC.

We looked at couple scenarios:
1. Internal & external URIs/handles poking into sub-items of IFluidObject, like maybe a query to table data store to return only specific records (result is JSON, not IFluidObject)
2. Ability to reference sub-elements, like at-mentions from at-mention collection, or paragraph from Scriptor

It becomes clear that we need to separate representation for GC, and representation that GC should ignore. For example, we could support query params on handles, but drop them for purposes of GC (when building GC nodes, as URIs map to nodes).
This seems a bit arbitrary, and the following picture emerged:

1. IFluidHandle always resolves to IFluidObject (true today) and represents node in the GC graph.
2. new IFluidExHandle (or some other name) is a combination of IFluidHandle and extra path (which can include query params, but also additional tail URI). It resolves to anything (IResponse) and does not participate in GC beyond IFluidHandle that it stores
   - Support from serializer is required, but no changes are required for GC to roundtrip it back and forth.

We do provide API to produce new IFluidExHandle  from IFluidExHandle  / IFluidHandle by appending URI to part of URI that is not participating in GC.
The guidance we would provide - the most ideal approach is always ask the target to produce you IFluidExHandle  / IFluidHandle, and thus not leak internal routing mechanisms of target. Documenting API of a component through REST is not a great idea, it's much better for components to provide strongly typed TypeScript API (including one that can give you back IFluidExHandle) and do most of the operations using IFluidHandleContext, not directly manipulating handles.
I.e. we should consider not providing this API.

Coming back to scenarios, the following would be possible:
1. At-mention collection could use IFluidHandle to represent individual elements in collection. That way it needs to do a bit more work when exposing info to GC, but GC at level of individual elements is possible.
2. It may also chose not to care about GC of sub-elements, and produce IFluidExHandle for individual nodes, thus ensuring that GC works on whole collection only. It simplifies coding at the expense of GC (and in our case - search relevance, so it's not an option for us, but might be viable option for somebody).
3. Scriptor, representing paragraphs through query params, for sure would want to use IFluidExHandle, as it likely will not want GC to work on paragraph level - that's not the right granularity. GC would not need to do anything about it, because IFLuidHandle used here would be pointing to whole Scriptor

**Comment by vladsud** [comment]
@curtisman , @anthony-murphy, @tylerbutler  - FYI.
Added design required to talk on Monday about it.

**Comment by vladsud** [comment]
One thing to add - IFluidExHandle  maybe implemented completely outside of FF code base as a bunch of code and new custom structure. The only problem with this approach is that each place that resolves it would need to use static function to resolve it, i.e.

interface IFluidExHandle {
    handle: IFluidHandle;
    uriTail: string;
}

const handle = map.get<IFluidExHandle>("key");
const foo = await resolveFluidExHandle<IFoo>(handle);

Maybe it's not a big deal, and that means that serializer does not need to know anything about it.

In original description above IFluidExHandle would be an interface with get() (better - resolve()) method on it. So it's slightly better encapsulation at the expense of additional complexity in the core of runtime.

**Comment by anthony-murphy** [comment]
I think i agree with everything here, but i don't know why we need to serialize the uri tail separately. My thought is GC parses the path, looks at the path parts, looks for GC able elements. right now that will only be data store, but down the line maybe there is an interface to same something participates in GC.

**Comment by anthony-murphy** [comment]
these are also all internal paths, external path never participate in GC. they if an external path want to participate in GC is should be routed to a handle based on internal paths

**Comment by vladsud** [comment]
If we think about it as a general system, then I think GC can't make assumptions here. I.e. if I have handle that that maps to /A/B, and /A exists, but /A/B does not, are we sure we want to keep /A forever? I feel like it's responsibility of the target (data store) to say "I'm /A, there is /A/C, everything else - I do not care, it does not exists and does not hold me alive" vs. "I'm /A and any subpath holds /A". I.e. I'm not sure I want GC to control these things, I want target data store (that controls GC node namespace, and also gives away handles of various types) to have full control over story - all the knowledge is in single place.

It makes things a big more complicated from usage POV, but it also makes system more flexible and powerful.

**Comment by anthony-murphy** [comment]
I was thinking the same thing, but drew the opposite conclusion. I would say that for all paths, things higher in the path control the lifecyle of things lower in the path, regardless of if they are dds, nested data stores (which does exist yet), or some other construct. so in your example, A owns B and C, and will be is control of how things like GC are or are not delegated to things below it. From the runtime i would also say we assert that the first thing is the path must be a physical thing. Being a physical thing is what allows it to have a handle at all, and if therefore must  participate in things like GC, for us right now that is data store, maybe someday it's a more abstract channel, but i don't think that changes anything

**Comment by vladsud** [comment]
So here is modification of a proposal based on Monday's discussion, leveraging same "explicit" model (i.e. runtime does not guess on what parts of URI map to GC node):

1. Handles created through **IFluidHandleContext** mechanism (today's main way of creating handles, you can trace all code paths via generateHandleContextPath) are representing nodes in the GC system as well. By default (99% of the cases - using data stores and DDSs and not having collections / custom routing that maps to data stores / DDSs through some redirection) developers do not need to do anything special
   - Documentation should clearly state that path passed to FluidObjectHandle constructor participates in GC (i.e. resulting full URI points to GC node). Developers should use mechanism described below if their need is different (i.e. create handle with path = "", and then create new handle with tail URI).
   - We should also consider removing path from FluidObjectHandle constructor, and instead force people to create extra IFluidHandleContext node. This will create more clarity. Need to access how much pain it causes.
2. We provide a way to create new IFluidHandle by appending URI tail to existing IFluidHandle. Internally, it stores 2 parts of URI - first part that maps to GC node, and tail part that is tail request to resulting object, i.e. it is convenience for users, it does not change how GC observes state.
   - process of serializing and de-serializing handles should account for that and staged appropriatly.

The biggest implication here (not so implication, as I believe it's broken today either way) is how collections should be handled.
Collection should not manually create URIs / Handles, they should use # 1 above to create handles for sub-elements.

As for IFluidHandle.get() itself, it (on its API) can resolve to anything (with default being IFluidObject).
However implementation in RemoteFluidObjectHandle only allows IFluidObject (i.e. there is a check for response.mimeType === "fluid/object"). We should fix it and be consistent - either allow everything (and remove this check) or make sure that interface only allows for T to extend IFluidObject.

**Comment by agarwal-navin** [comment]
An observation based on what's happening in the Boehmia / Scriptor repo and something we might want to consider in the design process - They are storing a handle whose `absolutePath` is `\scriptorId?start=x&end=y` and I believe the expectation is that this should mark the underlying Scriptor component as referenced from GC perspective.
Using # 2 from the above post will solve this problem but then we will have documents at rest with serialized handles that have the path with the query params. So, we will have to continue supporting them.

**Comment by vladsud** [comment]
First, we should mark absolutePath as readonly :)
Second, we should fix their code to be correct based on a proposal (or future proposal we agree upon), in a back compat way.
How things were written before TAPP does not matter, as files created after TAPP are in right format for GC to work correctly.
Does this address it?

**Comment by vladsud** [comment]
@agarwal-navin, do you need any help here?

**Comment by agarwal-navin** [comment]
The absolutePath is now marked as readonly. Bohemia is not updating it in the Scriptor code which was the main concern. They have another place that does this but I created a bug to fix that. So, we can punt this to June since we have other high priority GC items in May.

**Comment by agarwal-navin** [comment]
Tracked by AB#410
