### ISSUE TITLE
TaskManager does not handle properly disconnected state

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6190]
Connection can be lost at any event, between any async operations.
More over, it can be lost after point in time where TaskManager was used, but before ops coming from such interactions had a chance to be sent. Because of that, there is no way to move responsibility to handle connectivity state to end users, each DDS (including TaskManager) should work correctly across such transitions and abstract it away from users:

Error: Attempted to lock in disconnected state: initSync
       at TaskManager.lockTask (E:\FluidFramework\packages\dds\task-manager\dist\taskManager.js:212:19)
       at Function.createRunnerInstance (E:\FluidFramework\packages\test\test-service-load\dist\loadTestDataStore.js:103:27)
       at processTicksAndRejections (internal/process/task_queues.js:93:5)
       at async LoadTestDataStore.run (E:\FluidFramework\packages\test\test-service-load\dist\loadTestDataStore.js:227:27)
       at async runnerProcess (E:\FluidFramework\packages\test\test-service-load\dist\runner.js:136:30)

Stress tests have a bunch of race conditions that result in deadlocks and failures, I found this bug by attempting to use TaskManager to address these issues. Also TaskManager is already used in the test itself, and it will fail through the long test with exactly same symptoms as result of being disconnected while waiting for a lock in main cycle (disconnections are injected into test run plus they happen on regular bases).

**Comment by ChumpChief** [comment]
Chatted with Vlad to get some more info.  He pointed out this logic in the stress tests that is unpleasant for a customer to write as an example of a scenario that could be made easier:
https://github.com/microsoft/FluidFramework/blob/main/packages/test/test-service-load/src/loadTestDataStore.ts#L228

Note that `TaskManager` does not (at least currently) attempt to make any guarantees about the actions a client takes in response to acquiring a task (e.g. guaranteeing that ops from the task are not sent if/when a disconnect occurs).  Tasks can protect themselves somewhat with cautious `haveTaskLock()` checks between async operations but will always run the risk of ops going out inappropriately due to op-resubmit logic which cannot be controlled today.  This is another area where we should do better but doesn't have an immediate/local fix we can make.
