### ISSUE TITLE
The message sanitize tool doesn't scrub Sequence segment properties

### ISSUE THREAD

**Issue by KRyan** [microsoft/FluidFramework#633]
There may be other cases too. Will need a compliance review before using with customer data.

Example from a sanitized message.json (after running packages\test\snapshots\dist\sanitize.js)--

    "contents": "{\"address\":\"defaultComponent\",\"contents\":{\"content\":{\"address\":\"31597146-2bb1-4c92-9d6a-314f9ffdde23\",\"contents\":{\"pos1\":5839,\"pos2\":5847,\"props\":{\"spellingError\":[\"scripter\",\"script or\",\"scripture\"]},\"type\":2}},\"type\":\"op\"}}",

**Comment by heliocliu** [comment]
Tool has been updated to scrub more completely and should produce output compatible with the replay-tool, but is not compatible with the fluid preview.  That work is tracked separately (because it's not an issue of _how_ the content is sanitized, but because either the sanitize tool or the fluid debugger needs to support additional file formats)
