### ISSUE TITLE
Remove all usages of instanceOf from the repo

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#6351]
`instanceOf` in inconsistent and doesn't work all the time, especially around iframes. We should remove all usages of it from the repo and also add checks to ensure more usages are not added.

Some recent fixes: #6345, #5366

**Comment by tylerbutler** [comment]
@agarwal-navin Based on your recent fixes I think this eslint rule might be helpful: <https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-instanceof-array.md>

**Comment by agarwal-navin** [comment]
We need to disable usages of `instanceOf` not just for Arrays but for everything else too. Maybe that is what you meant too but just making sure :-).

**Comment by tylerbutler** [comment]
Yeah, I didn't mean to imply the rule was a solution for all the cases. Just that it could be useful in partially enforcing the policy as we make fixes. I just wanted to make sure this issue had mention of a related lint rule. 

I'll keep looking for other linting rules that could help.

**Comment by vladsud** [comment]
I think the tone of the issue is a bit too harsh - there is no real need to remove all usages of isntanceOf (and it's simply impossible, due to usage of 3rd party code).
While it might be good direction, in really requirement is to do it only for objects that could pass iframe boundary, which is small set (logging, arrays). And as part of this exercise we should also re-evaluate the need to do instanceOf in such cases.
For example, instead of using ArrayBufferLike we might want to define our own interface (to be used on storage APIs) that hides implementation (i.e. has unknown prototype chain, no ArrayBuffer there), and ideally remove the need to even use duct typing by providing enough conversion / accessor methods on this interface to satisfy all the needs. Is this possible / viable direction?

**Comment by agarwal-navin** [comment]
That sounds reasonable. How do we find the list of objects that pass iframe boundary?

**Comment by vladsud** [comment]
I think it's less about finding objects, but rather establishing where iframe boundaries could be and inspecting API and ensuring it adheres to certain requirements (sourced iframes would have much more requirements, if we support them).

Maybe for starters it's useful to enumerate where we support this boundary today (I believe today all of runtime code runs on same side of boundary, i.e. driver + loader + runtime). If so, where and how objects outside of this boundary can be passed to runtime or reverse? I remember we had issues with array buffers, but I'm not sure how (I do not remember :)).

I see 4 possible solutions here:
1. We disable all instanceOf in code base.
2. We disable usage of instanceOf for specific types (like array buffers - more likely to be used on iframe boundary) and push people toward bindInstanceOfBuiltin() for them
3. We advise people to do # 2 (i.e. no enforcement).
4. We ensure that it's impossible to use instanceOf in places where it should not be used, i.e. objects that cross iframe boundary are exposed through interfaces only and hide (encapsulate) original type (make it inaccessible).
   - for example, we can create IFluidBufferLike that has toString(encoding) & toUint8() methods on it - that seems like the only things that we care about.

Which one are we pursuing? It feels like it's # 3.

**Comment by jcmoore** [comment]
Touched base briefly with @curtisman and he confirmed my understanding that it is ultimately a goal to have some sort of linting rule that prevents the use of `instanceof` in "all" cases (with the option of locally disabling the linter in exceptional cases) like @agarwal-navin described above -- because it is a pattern we want to discourage -- so I believe we are targeting your # 1 @vladsud.

Built-in type validation should be covered reasonably well by `bindInstanceOfBuiltin()` proposed in #6674 and validations for custom classes would leverage user-defined type guards (to be added in subsequent PRs), like [`LoggingError.is()`](https://github.com/microsoft/FluidFramework/blob/main/packages/utils/telemetry-utils/src/logger.ts#L570-L576), that duck-type-check the precise interfaces actually required.

**Comment by danielroney** [comment]
@vladsud @ChumpChief  does this meet our criteria for 1.0? If not, I'd like to punt into the future.

**Comment by ChumpChief** [comment]
I'd say not needed.
