### ISSUE TITLE
sequence numbers are reported in telemetry under too many properties

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6395]
When I'm doing queries in Kusto, and need to investigate summarization issues, I want to see all the fields that carry sequence numbers.
Intelligence gives me a zoo of names, like these:
> Data_seqNumber, Data_sequenceNumber,
Data_referenceSequenceNumber, Data_refSequenceNumber

Can we standardize our repo to use fewer different names when logging similar concepts?
We can cut this list in two.
Are there any other cases like that?

This view might be useful to see all the properties that get indexed in Kusto to examine for similar names.
BTW, merging columns would reduce COGS as well :)

This is not urgent, but feels simple and has immidiadate impact, so putting it into June.
Feel free to move out if needed

@markfields - FYI

**Comment by markfields** [comment]
This is exactly the kind of stuff I want to be doing with Kabir this/next month, thanks for opening!

**Comment by markfields** [comment]
It can be a separate issue in the end, but I'd like to take an inventory of field names now, and identify other redundant sets.

An idea I had to help enforce using consistent "spellings" of common fields is to add a generic type param to `ChildLogger` which would be a Partial interface of all the common fields that might be logged at that layer, and then the event passed in would also include that type to get some auto-complete suggestions.  The thought is, it's like the property bags, but instead of being fixed or getters, they're just placeholders.

**Comment by vladsud** [comment]
I do not think it will work. First, it would be pain in the butt to add new properties.
It would also break our desire to have various layers (like driver, loader, runtime) to change independently from one another.
And developers build components in their own repos, leveraging our stack.

**Comment by markfields** [comment]
Not sure I understand your objections @vladsud. There would be nothing leaked between layers. Just whenever you create a ChildLogger you would do ChildLogger<T> where T is a type with canonical prop names for that layer, and the send functions would have an extra optional param of type Partial<T> so you can set those props and have the compiler help you spell them right. Maybe actually we just change the type of the event param to be Partial<T> & ITelemetryBaseEvent, or augment that base type to get the generic param, or something.

**Comment by markfields** [comment]
Not sure how practical it really is, but something to keep in mind while cleaning these and others up.

**Comment by markfields** [comment]
I'm going to close this - the two examples Vlad gave are not actionable - in the code there's only one spelling of each case, it's from older versions that the other is still there.

As for the more general problem, two comments:
* Let's keep opening small issues like this (and fix them right away because they're easy!) when we find redundant properties
* I've opened this issue covering the larger concern about standardizing and documenting some of our telemetry events: https://github.com/microsoft/FluidFramework/issues/6976
