### ISSUE TITLE
Should classes be a part of DDS public API?

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#6399]
In the review of the SharedCounter public API (#6334), @vladsud suggested that the SharedCounter class not be exported, and instead export only the ISharedCounter interface. From Vlad:

> I do not see much value in having SharedCounter class in here. It should be internal implementation detail., It should be free to change over time as long as public API (ISharedCounter) is not changed.
Other way to say it - this class should not be exported from package. Only interfaces, and factory.
Basically either we push developers to use interfaces, or we should ditch interfaces and export class only - there is not much value in having both.

@ChumpChief points out that today, our DDSes export a class, and that class exposes static create methods that are widely used, so we should be intentional about this change across DDSes to be consistent.

**Comment by vladsud** [comment]
@anthony-murphy has stronger opinions here than me :)

There are certain benefits from exporting only interfaces and static factory function. That said, it may add more pain in various ways (that we can address), like back/forward compat check (I'd prefer these interfaces only to have back compat requirement, and DDS implementations to export mock classes, and any place where someone depends on DDS actually define their own interface, not use DDS interface for that - following classical Ports-and-Adapters design pattern).

The other alternative - get rid of interfaces and use only classes. It's Ok too. But I'd say it puts even stronger emphasis on defining custom interfaces by consumers.

**Comment by anthony-murphy** [comment]
My feeling is we should only export 1 and not both like we do today. 

If we choose interface, we can easily just use an `export function` rather than a static.  The think the downside the interfaces is we can't stop people from implementing them. one pattern to consider is to always add a new interface in non major releases.

If we are in a state like:
```
interface MyDds{
foo()
}
function createMyDds(args): MyDds
```
and we want to add something it becomes:
```
interface MyDds{
foo()
}
interface MyDdsNext{
bar()
}
function createMyDds(args): MyDds & MyDdsNext
```
Then in the next major release collapse them back:
```
interface MyDds{
foo()
bar()
}
function createMyDds(args): MyDds
```

Classes have the advantage that they come with implementation, so if they are extended and child implementations automatically get that implementation as well. The downside is they are treated pretty strictly by the type system example:
https://www.typescriptlang.org/play?#code/FAYwNghgzlAECyBPAIgEygb2LWAHATgJYBuEALgKaxkAWhAdgOYBc9ArgLYBGF+sAvLAAMAbmywAZgHspACgCUWHDlqEoAOlVNYAah1icAX2DHgqCuAj4qEtvRBlCU+rDZQKaKLNTpmCFOjyfsRShKhiwG4e6LL0FADu-p4K8hFRyUqSMgoYxobyQA

This strictness can make testing and mixed package versions hard. The best work around is to always wrap the class like we do in the type tests with type only
https://github.com/microsoft/FluidFramework/blob/main/packages/dds/cell/src/test/types/validateCellPrevious.ts

the above example then is a bit better: 
https://www.typescriptlang.org/play?#code/FAYwNghgzlAECyBPAIgEygb2LWAHATgJYBuEALgKaxkAWhAdgOYBc9ArgLYBGF+sAvLAAMAbmywAZgHspACgCUWHDlqEoAOlVNYAah1icAX2DHgqCuAj4qEtvRBlCU+rDZQKaKLNTpmCFOjyfsRShKhiwG4e6LL0FADu-p4K8hEA9ABUGdgZ1HRwarAQLrz4Unw8IBBR1Ii4VBQAHrhS7nC0VJYwsAyU+PQQYFDMObAAgviMnBT0ZLBSErX1sADkGJIyCsGh4bCGKz1w9FJz0FCEjANcYFRkUnhWEBwUffOLZHVUK0ieK+riAAUyvV8B9VlpGAdChw1OdtAwll91tI5EFYCEwiI9gcuGw5tYAI5sQjWVA9FwfZbfAJQP7AFYQqFwcyWUmwXFzQhkOCkMBsKiFOLEXiwawQVD-WAZNKRdzJJQbVEYYyGeRAA

but now all usages need to be very carefully managed, so we don't couple to classes.


Overall, i think i prefer the interfaces world, but neither is a slam dunk

**Comment by curtisman** [comment]
My 2 cents, classes aren't very idiomatic for JS.  All methods in the class are not tree shakable as well.  We should also reduce the number function included with the object.  It does make function discoverability (thru intelligence).  We should figure out a balance here, but in general, I think @anthony-murphy is in the right direction.
