### ISSUE TITLE
Fix assert in getEncodedShareUrl

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#6430]
The following assert in `getEncodedShareUrl` seems incorrect and is getting hit in production - https://github.com/microsoft/FluidFramework/blob/ccf14f8a002724b85128c05f37effe6080696825/packages/drivers/odsp-driver/src/fetchSnapshot.ts#L368

This should be patched to 0.40 and 0.41 as well.

**Comment by jvoels** [comment]
Can we clarify more details about why this was added, but especially contrast in detail to why it is incorrect? Is the problem the assert, or that the method shouldn't have been called incorrectly. Instead of removing the assert, should we be removing a full trail of other events that were irrelevant?

**Comment by agarwal-navin** [comment]
Yeah, I am not 100% sure that this assert is incorrect. This issue is more about tracking what is going on here. @jatgarg is most familiar with the code, he can take a look and should be able to answer these questions and update the issue.
