### ISSUE TITLE
Tag the stack property on error logging events as CodeArtifact

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#6603]
And this is when we'll replace `TelemetryDataTags.PackageData` with `CodeArtifact`.

**Comment by heysujal** [comment]
please assign me this issue.

**Comment by vladsud** [comment]
@markfields, correct me if I got it right, but here is how I see this item:

1. Find code like below and change "PackageData" to TelemetryDataTag.PackageData
```ts
               errorWrapped.addTelemetryProperties({ fluidDataStoreId: { value: this.id, tag: "PackageData"} });
```
2. Rename TelemetryDataTag.PackageData to be TelemetryDataTag.CodeArtifact
   - do that with back compat in mind, maybe first introducing new tag and adding note about it in breaking.md, and then (in next build0 removing old tag and moving all the usage to new tag
3. Add TelemetryDataTag.CodeArtifact to places where we collect stack, i.e. prepareErrorObject()

Does this look right?
I'd love to see if I got scope right (if I did, this seems like reasonable task for Kian to own).

**Comment by kian-thompson** [comment]
@vladsud What exactly does `CodeArtifact` mean in this context? Is there something I can read into about the motivation for this change?
In terms of tagging the `stack` property, I'm not seeing an obvious way of doing this since `stack` is typically of type `string`. I could create a nested object in the error, but I can't think of a good naming scheme off the top of my head that would include both the stack trace and tag.

**Comment by vladsud** [comment]
Sorry, issue description can be clearer :)

Some of the data collected might be considered PII (Personally identifiable data). We, as a library, do not know for sure, because we do not have enough data on how platform is used. For example, names of various objects that application assigns, package names, factory type names - all of that is fixed for our 1st party partners and known upfront (anybody can look into our bundles and find these names). But, if some 3rd party code is using FF, such information can be unique enough to identify particular application. And if such application runs in a small tenant, that's essentially equivalent to identifying end user (using this app).

For that reason, we want properly markup telemetry properties to let app developer enough data to reason on what to do. They may drop such properties (remove from telemetry payload), they may choose to send data to their servers, or to our servers. Scenarios might be complex (in the future) - like our 1st party apps supporting some kind of extensibility model that allows running 3rd party code - in such case telemetry events may fire in FF code used by 3rd party, but data would flow to us - we would want (in such case) to remove every bit of info that may potentially identify a user.

So, things like stack, or various IDs that are part of JS code will identify particular JS bundle. We want to call all of such information "code artifact", or in code - TelemetryDataTags.CodeArtifact. We have started with marking some subset of such data as TelemetryDataTags.PackageData, but I think that name can be interpreted not as broad as "code artifact", so we want to rename it, and mark more of a data we collect with such tag.


As for stack, we should add to the end of prepareErrorObject() this code (or equivalent):

```ts
event.stack = {tag: TelemetryDataTags.CodeArtifact, value: event.stack};
```
