### ISSUE TITLE
Move Tinylicious to Server Packages

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#6915]
## Work Item
We should move tinylicious to the server packages. This will make sharing implementations with local-server easier, prevent  breaks due to server changes, and provide a 1-1 mapping of tinylicious and server versions

**Comment by anthony-murphy** [comment]
@curtisman prefers tinylicious to not be part of the docker image, which i think makes sense. this will add complexity to this item, as currently we build as part of docker. one option would be to move the build out of docker, and use npm i in the docker rather than building in the image

**Comment by anthony-murphy** [comment]
another option could be to make tinylicious its own mono-repo that directly references the server packages. this could make the build more complex though, and require redundant builds (server docker, and server tinylicious)

**Comment by curtisman** [comment]
We should separate the NPM package build/publish and the docker image building (instead of building withing the docker image) It makes the docker image cleaner, and also if docker build failed for some reason, it doesn't block the NPM packages.

However, we should maintain the docker image build in the same pipeline as the packages, and I'd like to see we run the client e2e test targeting both tinylicious and docker image as a validation step.

**Comment by anthony-murphy** [comment]
@heliocliu @skylerjokiel and @tylerbutler this could help with some of the tinylicious issues we see
