### ISSUE TITLE
fluid:telemetry:InitialElectedClientNotFound errors in telemetry

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6948]
We do see these events in automation:

union office_fluid_ffautomation_*
| where Data_eventName contains "InitialElectedClientNotFound"
| summarize count() by Data_eventName

I see 3977 cases.

Plus this event should have some reasonable prefix, i.e. fluid:telemetry:**OrderedClientElection**:InitialElectedClientNotFound

**Comment by anthony-murphy** [comment]
We should def fix the prefix here, looks like the raw logger is getting past rather than the summarize's or contianerRuntime's sub-logger

**Comment by arinwt** [comment]
After reviewing the telemetry, it looks like the bug is attributed to an older summary (at seq `x`) being accepted, but the server is stamping it with protocol state at a later sequence number (`x + k`), which is the same as another previously nacked summary attempt.

This needs to be fixed in the scribe lambda, I think rejecting summaries that are older than the current protocol state is a must, maybe a regression from #934?

Additionally, I think we should fail faster, by recording the reference sequence number of the runtime in the .metadata blob and failing immediately on load if that doesn't match the one in the .protocol tree.

**Comment by pleath** [comment]
Is there something particular about the way the stress test issues summary nacks that could be bypassing the original fix in the scribe lambda? Or is it more likely that something (a race?) is causing that fix not to work?

**Comment by pleath** [comment]
This seems to have dropped off the radar. No hits in current Kusto data.

**Comment by vladsud** [comment]
There are no events in Prod, our scalability tests or ODSP scalability tests.
All issues are resolved due to latest set of improvements in summarizer logic, including reliable last summary flow.
