### ISSUE TITLE
odsp-driver package is bringing in a dependency of "buffer" package

### ISSUE THREAD

**Issue by pragya91** [microsoft/FluidFramework#6999]
odsp-driver package is bringing in a dependency of "buffer" package of size ~6kb gzipped. odsp-driver any of its dependencies does not seem to have any direct dependency on "buffer". Could you check if it is indeed required?

**Comment by heliocliu** [comment]
Investigated further last night, reason is because odspPublicUtils.ts is pulling in sha.js to do some SHA-256 hashing.  Looks like it's always been like this and I just missed it the first go round way back when because it wasn't covered in the original report on our end.  It needs some changes to the common-utils hashing functions, so I'm going to go ahead and try to get that this week before the release because common-utils already got bumped this patch
