### ISSUE TITLE
Limited Offline Support for Data-loss Prevention

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#7594]
## Scenarios
There are three high-level customer scenarios for general Fluid Offline support:

* Create and edit a new container while offline, upload on connection
* Best-effort recovery of edits after rude termination
* Load and edit a cached container while offline, synchronize on connection

The first scenario (create offline) has been previously addressed by the detached container work for the "walkup and use" scenario.

This workstream targets the second scenario (best-effort recovery), allowing customers to work offline for brief periods of time.

Support for the third scenario (working offline) is limited in this solution, both by service retention policies and the time required to resynchronize the document by replaying ops.  (See limitations section below.)

## Prior Work

The offline creation scenario is supported today using the detached container
workflow, which allows the application to retrieve, store, and rehydrate a
summary of the container's contents while offline.  This rehydrated summary
may then later be attached to the service when connected.

It is the application's responsibility to store the summary, as well as to
provide an implementation of IDetachedBlobStorage, which stores
blobs uploaded while the container is in a detached state.

When connected to the service, the Fluid runtime already tolerates transient
network failures by caching locally pending/unsequenced ops and resubmitting
them during reconnection.

Finally, the runtime team has prototyped the ability to retrieve the set of
pending ops and provide them to a rehydrated container to address the best-effort
recovery scenario (#4597).

## Stashed Ops design

A new 'closeAndGetPendingLocalState()' API is added to IContainer which allows
the application to close the container and retrieve the pending/unsequenced
ops from the PendingStateManager.

As in the detached container workflow, the application is responsible for persisting
the returned pending ops in local storage, along with the summary and IDetachedBlobStorage
as before.

When rehydrating the container from local storage, the application provides the
pending ops to the loader. The pending ops are used for two purposes:

1. The pending ops are re-applied to the DDS on top of the last summary to restore
   the client's local state.

2. The pending ops are used to initialize the queue of outgoing messages in the
   PendingStateManager.

In order to re-apply pending ops, a new 'applyStashedOp' API is added to the DDS.
One nuance is that because local op metadata is not serializable, the 'applyStashedOp'
API must re-create it for the runtime.  This requires a minor amount of per-DDS work.

A second nuance is that some pending/unacknowledged ops may have been in flight at the
time the the application extracted the pending ops list. This is mostly handled by our
existing reconnection logic in PendingStateManager, with the caveat that we need to
remember our original client ID so that the PendingStateManager can recognize ACKs for
previously sent ops during the "catch up phase".

### Known Limitations

Portions of the document that were not cached prior to the client disconnecting will continue to be unavailable
while offline.

The duration a client may be offline and still successfully reconnect is limited by the retention policies of
the service.  If the require op history is no longer available, the client is unable to adjust its pending ops
to account for concurrent changes.  Furthermore, the client is unable to determine which of its pending
ops may have previously been received prior to disconnection.

Ops have higher storage overhead than summaries. Keeping the list of ops for long offline sessions
may increase pressure on Fluid and DDSes to compress the op representation (#2676), support
coalescing of ops (#1912), or page-out the PendingStateManager's queue to local storage as it
grows large.

Similarly, replaying/uploading long lists of pending ops will impact load time for
offline documents.  Longer term, we may want to consider enabling DDSes to summarizing
their locally pending state in order to accelerate loading and/or synthesize their pending
ops from their locally pending state (e.g., MergeTree can do this.)

A limitation of our current design is that PWAs and browser tab instances will not synchronize
with each other while offline. Rectifying this would require introducing a local intermediate
ordering service that provides a partial ordering of local changes in advance of the Fluid
service's total ordering. Such a change would require modifying DDSes to use version vectors
instead of a single seq#, which is out of scope.

Finally, we anticipate that the op-based merge semantics we use for real-time collaboration
may yield poor results for offline workflows.  We've speculated in the past that the application
may want to preserving app-specific metadata on ops, or fallback on an interactive 3-way diff
when reconnecting a stale document. While we currently do not know of anything that would
preclude an application with a custom DDS from building these experiences, it's currently an unknown.

### Technical Requirements
* Offline storage retains everything the client has downloaded for the current document: summary, blobs, and ops up to the seq# of the summary.
* The offline storage of hosts must be isolated, in that one host does can not evict contents that the other host needs.
* When transmitting attachment ops, care must be taken to ensure that offline blobs have first completed upload.
* When reconnectioning, rehydrated pending local ops must be transmitted prior to any concurrent local edits added.

## Phase1

The remaining work for the runtime team is to ready the stashed ops work for production,
as well as provide the applyStashedOps implementation for the built-in DDSes.  Work to plumb
the storage/retrieval of stashed ops through the container implementation and implement
applyStashedOps for proprietary DDSes will be funded by our partners.

## March/April
[#9240](https://github.com/microsoft/FluidFramework/issues/9240) (wait for leave message of serialized container)
[#9241](https://github.com/microsoft/FluidFramework/issues/9241) (closeAndGetPendingLocalState() returns still-pending stashed ops)
[#9242](https://github.com/microsoft/FluidFramework/issues/9242) (Container layer state snapshot and rehydrate)
[#9245](https://github.com/microsoft/FluidFramework/issues/9245) (runtime layer state snapshot and rehydrate)

## Future
[#7713](https://github.com/microsoft/FluidFramework/issues/7713) (stashedOps implementation for DDSes)

[AB#24](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/24)

**Comment by vladsud** [comment]
I think @wes-carlson also produced a document (back in Spring) with his notes on where we are, gaps, items to be completed, etc. - would be great to reference it here.

As for SPO deleting ops - it is indeed causes limitation for offline to be only working for 30 days. This is possible to address as SPO keeps "file versions" around and we have been talking about the need for other scenarios to be able to scan that history and extract information (blobs that are already collected in latest snapshots, ops that are already deleted, etc.). This is likely doable, however you run into another problem - GC design (as of today) has same limitations, assuming that it will not allow any sessions (offline or not) to last over 30 days, to correctly collect content. With offline support discussed here, notion of "session" (in GC world) changes to include all offline sessions (i.e. all sessions that originated at some point by loading a specific snapshot version and continuing making online/offline progress). I think there is no easy way out here and we would need to leave with that limitation, until we come up with other ways to merge files (3-way merge) that would allow to remove any of these limitations. @agarwal-navin - FYI

**Comment by wes-carlson** [comment]
Thanks Vlad, I forgot about that
<details><summary>here is the document I wrote</summary><p>

# stashed ops
## completed work
We get stashed ops from Container.closeAndGetPendingLocalState(). Stashed ops are supplied to a new container as an argument on Loader.resolve(). ContainerRuntime/PendingStateManager will give stashed ops to DDS via SharedObject.applyStashedOp() when their reference sequence number is observed. If we see an ACK for a stashed op, we treat it as a local ACK. UnACKed stashed ops are resubmitted at time of "connected" event.
## challenges
- Stashed ops are matched against ACKs from the previous container by client ID and client sequence number. This has a couple of consequences:
    1. When we get stashed ops from a container, we must close the container at the same time. Otherwise, the container could reconnect with a new client ID and resubmit the ops. This would mean we couldn't match our stashed ops to the successfully submitted ops, resulting in duplicate ops submitted, which can cause document corruption e.g. in the case of attach ops
    2. We (and our partners) should be careful to treat stashed ops as "consumable", i.e., once stashed ops are given to a container, they should not be given to another (unless we know it never reached "connected" event), since the second container could not match stashed ops to ops resubmitted by the first container.
- In order to apply stashed ops, the relevant data stores and DDS's must be loaded. This means applyStashedOp() must be async, but process() and setConnectionState() on ContainerRuntime are synchronous. We work around this by listening directly to DeltaManager "op" events and pausing between ops.
- In order to apply stashed ops, we need to load from a summary at or before the reference sequence number of the first stashed op (i.e. the lowest one). SPO wants to delete old summaries though, which would affect our ability to apply old stashed ops.
- Serialized stashed ops may be kept by host for arbitrary amount of time and given to newer version loader, which could cause compatibility issues
## remaining work
- Implement applyStashedOpCore() on all DDS's. Currently only implemented on map (except for ValueType ops).
- Need the ability to load from a summary at or before specified sequence number.
- Loader should only return container after it is connected when loaded with stashed ops.
- Support uploadBlob(). When BlobHandles are attached, they submit a "BlobAttach" op which tells storage that the blob is attached and it should not be GC'd. However, stashed BlobAttach ops may refer to already deleted blobs, so we need to either save pending blobs and reupload them or discard these stale ops somehow.
- Make sure that we connect as "write" when we have stashed ops.
- Currently "pause" headers are ignored since we need to connect in order to apply and resubmit stashed ops. It might be nice to pause container after "connected" event when pause is requested (is this still possible? didn't we remove pause()?)
- hot-swap context reload will definitely not work currently but I think this is not supported anymore and will be removed sometime?
</p></details>

Some of it is no longer accurate, for example, BlobAttach ops are no longer sent when the handle is attached, but are sent right after the blob is uploaded and before the promise returned by uploadBlob() is resolved. It would still be important to make sure this is handled correctly.
