### ISSUE TITLE
Consider renaming AzureFunctionTokenProvider

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#7770]
AzureFunctionTokenProvider is not tied to an Azure Function implementation. My suggestion is to rename it to RESTTokenProvider or UrlTokenProvider. You can use the token provider with any HTTP endpoint as long as it accepts the params sent by the token provider and returns valid tokens.

**Comment by heliocliu** [comment]
Are the params specific to some AzureFunction template we specify?  It kind of sounds like it's not quite a generic RestTokenProvider because it would be expecting these Azure-specific params if so.  And that if all we did was rename it, we probably would keep it in the azure-client package anyway.  Overall seems fine to me, but more in a technical correctness sort of way rather than a user benefit sort of way?

**Comment by AndrewCraswell** [comment]
For what it's worth, this thought crossed my mind when reading the docs. Calling it AzureFunctionTokenProvider made me feel that this only worked with Azure Functions, but it isn't clear why that would be. A new name could dispell confusion.
