### ISSUE TITLE
Repo should be node 16 / npm 8 compatible

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#7820]
The repo is currently compatible with Node 12 and 14 LTS, but is broken for 16.  16 is moving to LTS at the end of 10/2021 and 12 is reaching end of life 05/2022.

- [x] Find blockers for upgrade.
- [x] #8051
- [x] #8061
- [x] #8090 
- [x] #8091
- [x] #8092
- [x] #8108
- [x] #8116
- [x] #8117
- [x] #8118

**Comment by znewton** [comment]
As suggested by @tylerbutler, moving the conversation from #7909 (where I proposed moving to Node 14 while staying on NPM 6) to here.

**Comment by tylerbutler** [comment]
I think we need to close on a plan this month, though the work could be done later. Assigning to myself and October to reflect that.

**Comment by tylerbutler** [comment]
> I would prefer to move to 16 rather than using 14 as a stopgap.

After talking with @curtisman, 14 will be the new lowest LTS version, so we would want to run that in CI. And by the principle of "CI and local environments should be the same" we should use node 14 in the repo. #8146 tracks that.

**Comment by christiango** [comment]
@tylerbutler - I wonder if we should enforce that developers should be using node 14 via tooling or the engine field in package.json. It took me a while to realize that I HAD to be on Node 14 to deveop against FF since all other repos I work in support 16

**Comment by tylerbutler** [comment]
@christiango Definitely open to those suggestions. We do have an `.nvmrc` in the root of the repo to help indicate what version should be used, but it doesn't help much. With your recent experience, was it a problem with Node compat or npm? Last time I looked at this the main problem was npm because of peer deps and lockfile format. If you manually downgrade to npm 6 then it might work. Not that you should have to do that of course.

Ultimately we need to move the repo to another package manager and/or invest in better tooling ourselves. @heliocliu has done a bunch of thinking around this. There is work planned for 1.0; see the "Developers do not need to consider layers when making changes" section of #8007.

Regarding the `engines` field, according to [the docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines):

> Unless the user has set the engine-strict config flag, [the engines field] is advisory only and will only produce warnings when your package is installed as a dependency.

I'm not sure what the experience will be or if it will help. Some experimentation is in order! :) I filed #9434 to track that.

**Comment by christiango** [comment]
Sorry for the confusion @tylerbutler - yes it was ultimately the npm version included with node 16 that caused the issues, not node 16 itself!

**Comment by heliocliu** [comment]
@tylerbutler Could you clarify the relation to the 1.0 work here?  Maybe I'm just missing some context, but the layering issues for 1.0 are more around our repo organization rather than anything specific to our npm version

**Comment by tylerbutler** [comment]
@heliocliu I was specifically thinking of #8105.

> Once the work is done to independently version packages, we should merge all the separate monorepos into the same repo so all dependencies have full internal linkages instead of the current system where cross-repo dependencies rely on published packages.

I assumed that we'd be using a workspace-aware package manager to help manage everything. How are we going to handle symlinking the right versions of each package as changes are made? E.g. Package B 1.0 depends on Package A 1.2, now you want to test a package A changes with package B?

**Comment by heliocliu** [comment]
@tylerbutler I'm with you there; I just got lost on how that relates to the npm version 😅

**Comment by tylerbutler** [comment]
@heliocliu Ahhhh, yeah, I wasn't clear about that. npm 6 does not support workspaces, so if we want the tools to help us manage the repo, we'll need to upgrade to npm 7+ or yarn or pnpm. Yarn is my vote since it seems the most mature and best equipped to handle our needs. But that's just an opinion.

Anyway, if you _don't_ think we'll need to upgrade or switch package managers as part of the repo reorg work, let's continue that discussion on #8105.

**Comment by ssimic2** [comment]
Hey @tylerbutler, I'm curious once we move to npm 8 lockfiles, are we fully abandoning support for npm 6 (node 14)? I'm pretty sure that npm will progress your lockfiles from older to newer version when you upgrade, but uncertain what happens with node14 support once we move to node16, now that workspaces were introduced with updated lock formats.

Also, if node14 and node16 don't play well together, how we would sequence this upgrade across our branches? I have seen you doing couple up node upgrades PRs, so you may have some more context here.

**Comment by tylerbutler** [comment]
> I'm curious once we move to npm 8 lockfiles, are we fully abandoning support for npm 6 (node 14)? I'm pretty sure that npm will progress your lockfiles from older to newer version when you upgrade, but uncertain what happens with node14 support once we move to node16, now that workspaces were introduced with updated lock formats.

We would still support people consuming our published packages using npm6 or node 14. But you're right that everyone who's contributing to the repo will need to use npm 7+. But that's similar to today where we require v6.

> Also, if node14 and node16 don't play well together, how we would sequence this upgrade across our branches?

Excellent point. I think we'd need to upgrade at least in main, next, release/1.0, and release/azure/1.0 for consistency. To minimize pipeline issues between the branches, we should do the upgrade immediately after a release, so we have the most time to upgrade the pipelines on all branches.
