### ISSUE TITLE
Increase validation in TextSegment text property parsing

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#7899]
In Office Fluid telemetry, we're seeing this error a bunch recently:

error message: `this.text.substring is not a function`

![image](https://user-images.githubusercontent.com/12305068/138005883-f34126ee-ae2b-447c-b534-9b04f1e7e066.png)

Apparently, we're ending up with `TextSegment`s with non-string `text`.

**Comment by anthony-murphy** [comment]
this bug does not appear to be real, as it looks like the data come from a dev's prototype session. however, it does look like we can increase validation of TextSegments when constructing from both insert and parsing from json in shared string. specifically we should validate that the text property is of type string `typeof seg.text === "string"`, rather than just relying on type script typing
