### ISSUE TITLE
Op telemetry point improvement

### ISSUE THREAD

**Issue by curtisman** [microsoft/FluidFramework#7983]
Currently we have `OpRoundtripTime` and `InboundOpsProcessingTime` to measure the op perf lifecycle (sent from client -> server -> back to client, and processing)

- We should synchronize the sampling of these so we can have correlated samples (and probably a single telemetry point for them)
- In addition to the overall time and inbound ops processing time, we should measure when the op got back to the delta queue to measure the actual round trip of the ops. 
- Including the reference sequence number will also tell us and segregate whether the ops roundtrip is delayed by other ops.

**Comment by vladsud** [comment]
https://github.com/microsoft/FluidFramework/issues/7312 suggests that measuring latency at DeltaManager level ("raw") and at container runtime level (what we have today) would be advantageous to both have accurate numbers, but also to learn where in whole pipeline we have issues. For example, it's pretty clear that many issues that we see with latencies (as measured today) for op processing, and join op processing in particular are due to container runtime pausing op processing
