### ISSUE TITLE
Merge the separate monorepos into a single repo

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#8105]
See parent epic.  Once the work is done to independently version packages, we should merge all the separate monorepos into the same repo so all dependencies have full internal linkages instead of the current system where cross-repo dependencies rely on published packages.  Independent versioning will allow us to only version bump/publish when it's actually required, achieving the original purpose of the separate repos.

**Comment by tylerbutler** [comment]
How do you define "monorepo" in this context? Are you referring to the client and server? What does it mean to combine them?

**Comment by heliocliu** [comment]
So I'm not entirely sure I have the repo terminology right, but I mean all the separate build groups within microsoft/FluidFramework such as client/server/common-defs.  By combine I mean have it such that running any commands from repo root affects the entire repo rather than just client, and all packages see all other packages in the repo rather than relying on published packages for some.  Some existing package groups like docs can remain exempt from this, but that becomes the exception rather than the norm

**Comment by DLehenbauer** [comment]
This would be amazing.  For external contributors, this is a big source of friction:

* Mixing published NPM and local versions of the same packages is confusing.
* Because CI verification uses mixed NPM/local packages, breaking commits often slip through.
* '-symlink:all' ignores packages that don't have a pre-released version published in NPM, which is a blocker for external contributors.

**Comment by tylerbutler** [comment]
@heliocliu Thanks. The terminology is always confusing in this area. :) I think another way to say it is that our end state will be that we'll have a "typical" monorepo instead of the hybrid we have today.

What is the relationship between how the repo is organized physically and the "build groupings?" I.e. do we expect to be able to create build groupings independent of the physical layout? I ask because both yarn and pnpm use directory hierarchy as part of organizing workspaces, and I think we'll want to use the workspace construct if possible so we can avoid writing a bunch of custom tooling. To Daniel's point about friction, custom tools contribute to it, so better to avoid it where we can.

**Comment by heliocliu** [comment]
@tylerbutler I don't think build groupings need to specifically be tied to directory organization, but probably always will in practice because it makes sense to put related things together.  Groupings here means they receive versioning in lock-step, like how right now everything in client has the same version, so it's primarily for the version detection/determination.  Does the workspaces construct imply anything from the packages regarding their versions?

**Comment by tylerbutler** [comment]
@heliocliu It's still possible to version packages independently and have them in a workspace, yes. While I don't like it that much, [the Yarn folks have terminology](https://yarnpkg.com/features/workspaces) that covers the relevant constructs, so using them might be helpful:

**Project**: a project is the whole directory tree making up your workspaces (often the repository itself).
**Workspace**: a local package made up from your own sources from that same project. 
**Worktree**: the name given to workspaces that list their own child workspaces.

> A project contains one or more worktrees, which may themselves contain any number of workspaces. Any project contains at least one workspace: the root one.

I think groupings are worktrees, and they do depend on hierarchy as far as I can tell. But they're optional. So, to your point, we can add worktrees where we may want to regularly act on a group of packages (e.g. "Property DDS packages" or "all examples" or "all drivers" etc.) but versioning can still be done independently at the workspace level.
