### ISSUE TITLE
Remove Close Functions

### ISSUE THREAD

**Issue by scottn12** [microsoft/FluidFramework#8185]
## Overview

There are several occurrences of a `close()` function which have been deprecated and have all been replaced with a `dispose()` function. 

## Proposed Solution

There are no known instances of these `close()` functions being used in the internal repositories searched (FluidFramework, FluidExamples, Bohemia, OneNote). Therefore, the function declarations can simply be removed from the FluidFramework repository.

## Methodology

The `close()` function declaration will be removed in the following files:

1. common\lib\driver-definitions\src\storage.ts
3. packages\drivers\driver-base\src\documentDeltaConnection.ts
4. packages\drivers\file-driver\src\fileDocumentDeltaConnection.ts
5. packages\drivers\iframe-driver\src\innerDocumentDeltaConnection.ts 
6. packages\drivers\replay-driver\src\replayDocumentDeltaConnection.ts
7. packages\loader\container-loader\src\deltaManager.ts
8. packages\loader\test-loader-utils\src\mockDocumentDeltaConnection.ts
9. packages\test\test-service-load\src\faultInjectionDriver.ts

**Comment by sumedhb1995** [comment]
This sounds like a good plan! Let's also include these in the BREAKING.md with the change so that any 3P consumers of the next version are aware that this deprecated API is now fully removed and `dispose()` is the alternate option to use.
Also, for any of the files listed, if `dispose()` doesn't already get exposed, we should add that in. But I think most of them already do so you should be fine there

**Comment by ChumpChief** [comment]
Looks good!  Couple notes:

1. Since this touches both driver-definitions as well as the implementations, you'll need to stage the work.  Most likely you'll end up removing from the definitions first, and then once we've released a version you can depend on then you'll be able to remove from the implementations.
2. I removed `stop()` from iframe-host already :) #8058
3. For deltaManager.ts I believe you're referring to `NoDeltaStream.close()`, and not `DeltaManager.close()` -- might want to clarify
4. You have faultInjectionDriver.ts listed twice -- just wanted to double check that you didn't mean to paste something else that is missing from the list above.

**Comment by anthony-murphy** [comment]
i think this work is being done in the wrong order. we should remove usage in the code before removing the property, as right now main in broken with the latest driver definitions.

**Comment by anthony-murphy** [comment]
in general, we should remove usages of deprecated apis, before removing the apis themselves

**Comment by heliocliu** [comment]
@anthony-murphy i think what happened here was scott was going to make the second half of this change immediately after (since he had the full change already), but it didn't get done before the weekend.  my bad as well for not catching it at the time

**Comment by anthony-murphy** [comment]
@heliocliu  sure, but it's better to stage changes in a way that doesn't leave the repo is a broken state, which was possible here by doing the changes in the reverse order
