### ISSUE TITLE
Epic: Runtime errors should be distinguishable from external errors in telemetry

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8260]
This Epic logically tracks issues / processes identified in [this document](https://www.onenote.com/meetingnotes/c3BvOmh0dHBzOi8vbWljcm9zb2Z0LW15LnNoYXJlcG9pbnQtZGYuY29tL3BlcnNvbmFsL21maWVsZHNfbWljcm9zb2Z0X2NvbQ%3D%3D/b!AGWSVA8h1UCt8TshsiDv62IsjlwKMQFEkh5WI6pJaYkjabRsIQWsQ484ChTJDnwb/01PUF2H46U5O5NGNR2KRE3NV6FJLOQE5F5?iCalUId=040000008200E00074C5B7101A82E008000000009C3739DDD9D1D701000000000000000010000000B2BFA352B7B6CC4A8E51A93F4A12DBC1
):

The goal here is for FF OCE to be able to run a query and observe results in noisy environments (pre-production, ODSP stress tests, etc.) and determine if there are any regressions in this particular version of FF that is about to move to next ring.
Currently, we use category="error" in telemetry for this purpose, but it is noisy and contains a bunch of things we want to be able to exclude (either remove from error table, or have an easy way to build a query to exclude them). Here are key categories:
1. ODSP errors that are result of normal usage (403/404 errors - user has no access to document)
2. Exceptions thrown to FF in various forms, like token fetch callback, DDS event listeners, etc.
3. Similar to above, but issues hiding behind dataProcessingError / container "closed" errors ("Loading chunk plannerConnector failed.")

(Mark speaking here) A corollary is that the errors showing up in these queries should be suitable to aggregation at various levels of granularity.  Something like [Layer] -> [Error Type] -> [Error Case].  Getting this taxonomy right is another requirement here.

### Work breakdown

Fix confusion around fluidErrorCode v. message
- [x] #8929

Some errorType fixups
- [x] #8163
- [x] #8489
- [x] #8954
- [x] #8262 (related to #8954 above)
- [x] #9027 

Other: 
- [x] #8258 
- [x] #7800

**Comment by vladsud** [comment]
+ @anthony-murphy, to raise awareness of direction I thin we should be going (this is follow up to discussion we had 2 weeks back).

**Comment by markfields** [comment]
Closing #8099 and marking this as design required.  It's a dupe.

**Comment by markfields** [comment]
# Design Proposal (DRAFT)

## Leveraging errorType

errorType is already pretty close to what we need for distinguishing errors by source, but it has some issues.

* "genericError" can mean anything (error we raised, error passed to Container.close by host, unknown error passed to normalizeError)

Practically speaking, we will identify a mapping from errorType to a courser classification of "source".  This might not be the best long-term approach, but will meet our needs in the short term and inform next steps.

Note: Sometimes we call `logger.sendErrorEvent` supplying no `error` param. These need to be distinguished from error logs where the error had no errorType, and also will need some means of classification.  Perhaps we make a pass over them to add errorType as a prop on the event.

## Cleaning up as we go

* `new Error` should be replaced with a particular error class with errorType
* As we review top errors and refine our queries, we'll be opening bugs for incorrect errorType, etc

**Comment by markfields** [comment]
@vladsud - Please review the design draft above and leave comments.  Thanks, see you next week!

**Comment by markfields** [comment]
Update:  All main coding tasks are done. There are some bugs/follow-up items that either exist or need to be opened, I'll get those logged/grouped this month.  I will also be putting together error queries for OCEs and others to use to quickly filter errors by source, for use in evaluating ship-readiness at different points.

Determining source will be a mix of `untrustedOrigin` markup and various `errorTypes` as discussed above.

**Comment by vladsud** [comment]
I've glanced at one week of latest data. Here are some observations:

1. Some number of our errors are hiding behind Data_untrustedOrigin == 1 (counts are not high today, but I think we should have a plan to look into them somehow and ideally not mark with Data_untrustedOrigin  or have other ways to include them into "our" queries:

fluid:telemetry:Container:ContainerClose	0x16f	dataProcessingError
fluid:telemetry:Container:ContainerClose	0x29a	genericError
fluid:telemetry:Container:ContainerClose	0x170	dataProcessingError
fluid:telemetry:Container:ContainerClose	Failed to fetch	genericError
fluid:telemetry:Summarizer:HandleSummaryAckError	Unexpected end of JSON input	genericError
fluid:telemetry:RealizeError	0x0fa	dataProcessingError


2. These errors do not have Data_untrustedOrigin :

fluid:telemetry:Container:ContainerClose	Current version of the container 'Prod'-'20220303004' is no longer supported	genericError
fluid:telemetry:Container:ContainerClose	_acquireToken::NetworkOffline::isOnline-false	fetchTokenError
fluid:telemetry:OdspDriver:GetDeltas_Error	Failed to acquire auth token for OneDrive	fetchTokenError	2763
fluid:telemetry:Container:ContainerCloseException	Attempted to access context before it was defined	
fluid:telemetry:OdspDriver:GetDeltas_Error	_acquireToken::NetworkOffline::isOnline-false	fetchTokenError
fluid:telemetry:DeltaManager:GetDeltas_Exception	_acquireToken::NetworkOffline::isOnline-false	fetchTokenError
fluid:telemetry:Container:ContainerClose	Teams token retrieval timeout	fetchTokenError
etc.

3. I'd love for this event not to be in our telemetry - it comes from outside due to usage of our logger:
fluid:telemetry:FluidDataStoreRuntime:ErrorFetchingPresenceColorForUser			3870

4. Looks like we have a bug somewhere:
fluid:telemetry:Container:ContainerEventHandlerException	undefined is not an object (evaluating 'error.message')		1036

5. It would be great for this error to have Data_odspError = true:
fluid:telemetry:OdspDriver:GetDeltas_Error	offlineError	517


The query that seems like we want to use for our OCEs would be something like that:
> Office_Fluid_FluidRuntime_Error
| where Event_Time > ago(7d)
| where Data_odspError != true
| where Data_untrustedOrigin != 1
| where Data_loaderVersion contains "0.56"
| summarize count() by Data_eventName, Data_errorType

**Comment by markfields** [comment]
The query is a little more nuanced than that but yeah that's the idea. Thanks for pointing out those bugs I will open issues.

**Comment by markfields** [comment]
Reminder to take a look at #9183 and make sure that error is bucketed properly (it's a Scriptor bug)

**Comment by markfields** [comment]
Responding to @vladsud's observations:

* We can and should pull out asserts (using regex) and look at those ourselves
* "Failed to fetch" / "Unexpected end of JSON input" - I'll open issues for these, and put more notes there about how to follow up, we will need to keep our eye out for opportunities to improve our error handling/instrumentation like this.
* Data_untrustedOrigin does not do exactly what you want. All listed under (2) are excluded from "our" errors in my query
* "fluid:telemetry:FluidDataStoreRuntime:ErrorFetchingPresenceColorForUser" - Good catch I'll file a bug on Office Loop folks, they're passing the wrong logger around.
* "undefined is not an object (evaluating 'error.message')"  - This looks like a bug in Office Mobile, in their handling of `closed` event, they must be assuming `error` is not optional.  I will figure out how to file a bug.  It's properly classified as "not ours" in my query
* I'll have to think about GetDeltas_Error, we shouldn't instrument it with `odspError` because it's in shared driver code.  Maybe we rename that flag to `networkError` or `serviceError`.  I'm not convinced that should be a blanket-exclusion from our main query, either.

**Comment by markfields** [comment]
Got a dashboard up for internal analysis of top errors, classified according to the following sources:

* Service/Storage
  * Raised on account of an error response from the Storage service
* Service/Relay
  * Raised on account of an error coming over the connection to the relay service
* FF/Driver
  * Thrown from the Driver layer
* FF/Other
  * Thrown from some FF code not otherwise classified
* External/HostTokenProvider
  * Thrown from the token provider code supplied by the host
* External/RuntimeImplementation
  * Likely thrown by the host/app's implementation of the container runtime or DataStores/DDSes within (Equivalent at the moment to DataProcessingError)
* External/Unknown
  * Thrown from some code outside the FF repo, but not otherwise categorized as to which system originated the error.


Closing this Epic.  Long tail of follow-ups to be tracked here:  #9759
