### ISSUE TITLE
Replace innerRequestHandler with rootDataObjectRequestHandler in request-handler

### ISSUE THREAD

**Issue by sdeshpande3** [microsoft/FluidFramework#8270]
Replace `innerRequestHandler` with `rootDataStoreRequestHandler`.

The files affected:
1. examples\data-objects\codemirror\src\index.ts
2. examples\data-objects\key-value-cache\src\index.ts
3. examples\data-objects\prosemirror\src\index.ts
4. examples\data-objects\scribe\src\scribe.ts
5. examples\data-objects\shared-text\src\index.ts
6. examples\data-objects\smde\src\index.ts
7. packages\framework\aqueduct\src\container-runtime-factories\baseContainerRuntimeFactory.ts
8. packages\framework\aqueduct\src\container-runtime-factories\containerRuntimeFactoryWithDefaultDataStore.ts
9. packages\framework\data-object-base\src\runtimeFactory.ts
10. packages\framework\request-handler\src\requestHandlers.ts
11. packages\framework\request-handler\src\test\requestHandlers.spec.ts
12. packages\test\test-utils\src\testContainerRuntimeFactory.ts

**Comment by ChumpChief** [comment]
There is some compat risk here I think, but is probably manageable.  In particular, I'm noting that `rootDataStoreRequestHandler`, since it uses `getRootDataStore` will end up asserting [here](https://github.com/microsoft/FluidFramework/blob/main/packages/runtime/container-runtime/src/containerRuntime.ts#L1538) if the request is not for a data store that was originally created as a root.

Newer documents aren't likely to hit this, but old documents that were created before the concept of a "root data store" existed will throw for "root-like" data stores, resulting in a 404 response where before the data store was successfully retrieved.

Luckily this is easy for customers to mitigate by passing an equivalent request handler to the base runtime factory classes themselves, so I think it should be sufficient to just include guidance in breaking change notes.  So my recommendation would probably be:

1. For the base runtime factory classes (`BaseContainerRuntimeFactory`, `ContainerRuntimeFactoryWithDefaultDataStore`, and `RuntimeFactory`), simply remove the `innerRequestHandler` and do not replace it with anything.
    * IMO this was always a mistake, as it's not at all likely that a container should publicly expose all of its root data stores by default.
2. Advise in BREAKING.md that if container authors want to permit requests for specific data stores, they can add `rootDataStoreRequestHandler` to the list of request handlers they pass to the runtime factory.  This will restore the ability to request root data stores.
    * Further warn that this will only work for root data stores, and if they require support for requesting non-root data stores and/or for legacy document support they can create a request handler of their own that calls `runtime.IFluidHandleContext.resolveHandle(request)` just like `innerRequestHandler` used to do.

@vladsud who might have further thoughts.

**Comment by ssimic2** [comment]
@ChumpChief by legacy documents you are referring to docs whose snapshots never had `isRootDataStore` attribute?

Interestingly, we adapt these [here] (https://github.com/microsoft/FluidFramework/blob/main/packages/runtime/container-runtime/src/dataStoreContext.ts#L773) so we probably wouldn't hit assertion for legacy docs, but agree about being explicit in the guidance about breaking changes: using new API is safe only root data stores.

**Comment by ssimic2** [comment]
Also `resolveHandle` within container runtime does have logic targeting paths beginning with `_channels` and `_blobs`. Any considerations there ? `innerRequestHandler ` -> `rootDataStoreRequestHandler`, does not look like 1:1 replacement even if you put root data store differences on the side.

**Comment by ChumpChief** [comment]
Yeah, `isRootDataStore` is what I was referring to - I missed that adaptation so maybe that's totally fine.

I'm not really worried about colliding on the names `_channels` and `_blobs`, I don't think this is likely to be a threat in practice.
