### ISSUE TITLE
Replace DriverErrorType.genericError usages

### ISSUE THREAD

**Issue by sdeshpande3** [microsoft/FluidFramework#8272]
The enum member `genericError` for enum `DriverErrorType` has been deprecated. To replace its functionality, consider `genericNetworkError` or add a new specific error type if necessary.

Files affected:
1. `\common\lib\driver-definitions\src\driverError.ts`
2. `\packages\drivers\odsp-driver\src\odspDocumentStorageManager.ts`

To remove this error type, we must consult with partner repos to determine if `genericNetworkError` is an adequate replacement, or if a new error type must be defined. Once all uses are replaced with either solution, we can delete `genericError`.

### Steps to complete

- [ ] Add additional error types to `DriverErrorType` to help replace `genericError` (It'll be `DriverErrorType.usageError = "driverUsageError"`, see #8489).
- [ ] Replace all usages of `DriverErrorType.genericError` from Fluid Framework packages (to different enum values) and partner repos (to string literal `"genericError"` for back compat)
- [ ] Remove `genericError` from `DriverErrorType` in `driver-definitions`.

**Comment by scottn12** [comment]
To remove the deprecated `genericError` API, we first need to remove all references to it in our partner repos. To do this we can replace the occurrences of `genericError` with `genericNetworkError`. Additionally, we can define additional more specific error types if necessary. @jvoels , do you have any insights on if we need to define additional error types, or if `genericNetworkError` is enough?

**Comment by ssimic2** [comment]
It looks like Bohemia also has `tryMatchDriverErrorType` logic that tries to match `ContainerErrorType` to `DriverErrorType `. If there is bubble up/down of error messages, we should consider that as well.

**Comment by jvoels** [comment]
Is it true that all existing DriverErrorType.genericError are conceptually "generic network errors"?
I don't have any case off hand, but that seems lucky that would be a seamless 1:1 genericError -> genericNetworkError

Is there more context for the motivation on making this change?

To be really useful when logging values for telemetry the strings for these need to not collide across typescript enums or we would also need to logging (errorType) the actual enum type with the logged symbol that 'genericNetworkError' is actually from.

It looks like that may be the problem you're trying to solve. By removing genericError from DriverErrorType because it already exists in ContainerErrorType, or is it being removed from both?

Is the plan to manage not colliding symbol values across these enums going forward? 

@markfields fyi, some similarity here to conversations we've had on error handling and logging. This conversation brings up some interesting concerns on if an attribute 'errorType' alone on a logging event is enough when the value is an enum symbol value only without the enum type identifier. "ContainerErrorType.genericNetworkError" v. "genericNetworkError"

**Comment by markfields** [comment]
There were no usages that I knew of until @vladsud added some in the last month in #8464 :(  The client never picked up the driver-defs version with the deprecation.  See #8489.

And yes, the whole reason I deprecated this in #6489 was because the enum value is indistinguishable between DriverErrorType and ContainerErrorType.

> Is the plan to manage not colliding symbol values across these enums going forward?

Yes, and I'm also considering how we can migrate to a namespaced error type, maybe leveraging the `name` property.

**Comment by scottn12** [comment]
From these comments my understanding is that we should still continue to remove `DriverErrorType.genericError` since it collides with another enum. If that is the case, @jvoels, could we start the process of replacing instances of this enum in Bohemia? If so, who would be the best person to contact to help get these changes completed?

**Comment by jvoels** [comment]
For internal/partner repos, start a thread with myself and Mark internally (teams/e-mail is fine). It sounds like we want work items made internally for bohemia et al that track the work needed so this doesn't just catch FF 'bumps' off guard, and we will also consider other systems that may have less obvious references (unlikely though).

**Comment by scottn12** [comment]
Closing this issue. After further discussion with @markfields, we decided to keep `genericError` and we will not be adding in a new error type.

**Comment by markfields** [comment]
More context in [this comment](https://github.com/microsoft/FluidFramework/pull/8803#issuecomment-1024640085).
