### ISSUE TITLE
Remove requestFluidObject_UNSAFE

### ISSUE THREAD

**Issue by sdeshpande3** [microsoft/FluidFramework#8283]
Using handles is the recommended way moving forward and instead of calling getComponent_UNSAFE, the developers should just be calling handle.get() if they don't need to worry about back-compat.

**Comment by ssimic2** [comment]
Hey @sumedhb1995, this file & function name has gone through some renaming. This used to be `getComponent` and it looks like you marked this call unsafe here: https://github.com/microsoft/FluidFramework/commit/26ad2a88e86637b5bd2b7992a3cb4464546980ee#. Can you give us some more context around deprecation? It looks like you left it for test purposes, but the issue you listed there is closed.

**Comment by ssimic2** [comment]
I'm guessing the intention here is to get rid of this call, as we are now relying on Shared Object handles, instead of `LegacyUriHandle`.

It seems like `requestFluidObject_UNSAFE` is really only called by `getFluidObjectFromDirectory`. Given that we do have existing code that is migrating old shared values to handles when processing incoming `ISerializableValue`, it seems like `getFluidObjectFromDirectory` will always get handle back and not the id (url). Therefore bypassing need to call `requestFluidObject_UNSAFE`.

One other concern is that API caller of `getFluidObjectFromDirectory` can pass a callback that will return id instead of a handle.

**Comment by sumedhb1995** [comment]
`getFluidObjectFromDirectory` was intended to be a forward migration pattern developers could follow to transition from using ids to using handles. Using handles is the recommended way moving forward and instead of calling `getComponent_UNSAFE`, the developers should just be calling `handle.get()` if they don't need to worry about back-compat. Since this change was made more than a year ago, most developers should no longer ever need to get the object by ID

**Comment by ssimic2** [comment]
Summary here: 
1. No usages in partner repos. 
2. Given that we do have existing code that is migrating old, shared values to handles when processing incoming ISerializableValue, `getFluidObjectFromDirectory` should only be considering handles.
3. The usage is TableSlice may not be relevant, as we are removing table documents here: https://github.com/microsoft/FluidFramework/issues/8187.
