### ISSUE TITLE
Refactor/Deprecate createProps

### ISSUE THREAD

**Issue by sonalivdeshpande** [microsoft/FluidFramework#8292]
Context: #1635, #3631

The `createProps` property for the interface `IFluidDataStoreContext` and its implementation classes `LocalFluidDataStoreContextBase` and `MockFluidDataStoreContext` have been deprecated in 0.16 and should be removed. 

To remove it must be removed from both FluidFramework and partner repos. It is used in the following files in the FluidFramework repo:

1. `\packages\runtime\container-runtime\src\dataStoreContext.ts`
2. `\packages\runtime\runtime-definitions\src\dataStoreContext.ts`
3. `\packages\runtime\test-runtime-utils\src\mocksDataStoreContext.ts`
4. `\packages\framework\aqueduct\src\data-objects\pureDataObject.ts`

**Comment by ssimic2** [comment]
Hey @leeviana could you comment on Bohemia and readiness there?

I saw your discussion here: https://github.com/microsoft/FluidFramework/issues/3631. As well as PR that was reverted: https://github.com/microsoft/FluidFramework/pull/2951.

In Bohemia repo I do see that some DataObjects are still relying on `createProps`. 

If you have any tickets that track related items on bohemia side, please share them here. On FF this is the only open ticket that tracks `createProps`. The older one was closed: https://github.com/microsoft/FluidFramework/issues/1635.

**Comment by leeviana** [comment]
We have a need for inputs into initializingFirstTime (initial config) flows in our components and have not been provided with another way to replace these flows as of now. I believe our latest suggestion for replacing the old createProps flows, involve using aqueduct factory APIs directly, but they need to be made discoverable via Provider/request patterns as they are currently not discoverable today.

However, it sounds like from this issue that you want to remove this from your client helper layer as well. In that case, I don't think we have a good solution. We could wrap/reimplement DataObject in our repo again (aqueduct's data object originally was migrated from our repo in the first place), which we've already started to do with SharedFluidLoopComponentFactory, but unless wholesale copy/pasting code, which is not ideal, we'd still need a way for DataObject/Aqueduct helpers to let us inject initial config somehow. Either through an API or by refactoring Aqueduct's DataObject into a more composition-based pattern (instead of inheritance), which would allow dependencies to compose the helpers and lifecycle pieces the way they want to instead of sticking to a single fixed class-based paradigm.

**Comment by ssimic2** [comment]
Thanks @leeviana. I have added this to "needs solutioning" (parent epic) together with https://github.com/microsoft/FluidFramework/issues/3631. I'll dig into this further as soon as we are done with the first pass on deprecated APIs.
