### ISSUE TITLE
container.isDirty flag should be true for detached containers

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#8358]
I'm working on showing users a warning dialog when they are navigating away from a page that is rendering a Fluid container that has pending ops. To achieve this, I use the isDirty flag and the 'saved' event. This covers the case where we have an attached container that has not finished pushing ops to the server.

One other scenario we'd like to handle is a container that is not yet attached. Refreshing in this case would also cause data loss, so we should also warn the user in this case. Ideally, we'd be able to use the same isDirty and 'saved' APIs to achieve this as well. Right now, isDirty is false for detached containers based on local testing. My proposal is that the isDirty flag should be true for containers that have not had attach called or have an attach call in flight. Once the container is attached and all ops are persisted, it should set isDirty to false and emit a saved event.

**Comment by ChumpChief** [comment]
Seems reasonable to me that both should be considered "dirty" before attachment (really "unsaved" would have been a better name perhaps :shrug:).  Should probably also cover containers created via `rehydrateDetachedFromSnapshot`.

Would probably also be good to guard the `"saved"`/`"dirty"` events to only emit if the state actually changes in `updateDirtyContainerState` implementation in `container.ts` -- currently there are guards in the runtime but would be reasonable to guard at the loader layer too.

Since the `ContainerRuntime` is the only place where we can know whether there are outstanding pending ops, it will need to be the place that declares the first `"saved"` post-attach.

**Comment by tylerbutler** [comment]
Please make sure the documentation is updated as part of this work. It won't be accurate after this change. <https://fluidframework.com/docs/build/containers/#isdirty>
