### ISSUE TITLE
Add back-compat tests across URL resolver <-> driver layer boundary

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#8408]
Follow up from - https://github.com/microsoft/FluidFramework/issues/8250. The issue was that a new property was added to `IOdspResolvedUrl` and the code was updated to use the new property. This broke the url resolver (loader) <-> driver boundary.

We need tests to ensure we maintain back-compat here and don't break these. Same goes for other URL resolvers <-> driver.

**Comment by agarwal-navin** [comment]
@jatgarg Assigned this to you.

**Comment by vladsud** [comment]
I believe this is based on PR https://github.com/microsoft/FluidFramework/pull/8293
And the core of the problem is that changes to api-report/odsp-driver-definitions.api.md can be only additive/optional, i.e. support back compat.
In other words, in addition to having some tests, we need to have a process similar to other .api.md files where developer has to describe type of changes from compatibility POV and raise the bar to making these changes.

**Comment by pragya91** [comment]
I can work on this. Feel free to assign it to me.
