### ISSUE TITLE
Eliminate shouldJoinWrite concept from loader layer

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8424]
This area was not ideal before, but it becomes clearer with some refactoring (see PR #8423) that flows around shouldJoinWrite() in Container / DeltaManager areas are not ideal and need to be re-evaluated.

Here are some issues as I see them:
- Current flow (with tracking clientSequenceNumber, clientSequenceNumberObserved, trailingNoopCount has baked too many assumptions that may easily change over time. For example, this logic assumes that any op resubmission on reconnection happens synchronously, in one go. This may change with the work @wes-carlson is doing around blob upload being incorporated into pending manager, and thus making op resubmission process async.
- in general, there is tool much knowledge in this layer about specific handling of noops by service. Ideally these layers should not care

Ideal solution:
- Is correct if all reconnects are "read" or "write". I.e. correctness does not depend on state of the universe
- there is a way for container runtime to provide a hint to loader layer RE optimal connection mode, and thus optimize process of reconnecting. This can be similar to "dirty" / "saved" states that container runtime communicates to loader (to raise such events), but I think we need dedicated mechanism, as one can be in situation where container is never "dirty" (i.e., no loss of data if user decides to close it), but contains runtime has local state that needs to be accounted correctly (acks) on reconnection (possibly - online game).

I think we already have the tools to make it happen. We already wait for own leave message before raising "connected" events for "write" connections. This acts as barrier, similar to own join message. We can extend it to all connections rather easily. I.e. we can't raise "connected" event until leave from previous "write" connection was received. This includes cases, like "write", "read", "read" connections, where we still did not see leave from first "write" connection (very similar to today's behavior where it would be "write", "write", "write", but last two would not raise "connected" event as we did not see "leave" for first connection.
We need to consider serialized / rehydrated container, as it should behave similar to disconnect / connect RE ensuring leave from old connection is processed.

This will give us correctness. 
I believe this is in line with issue #7884 that advocates for raising "connected" event for "read" connections only when client is up-to-date. That for sure should include processing of old leave op (in case one of the previous connections was "write"). 

@markfields, @jatgarg - can you please take a look? I've assigned to you both as you both have affinity - Jatin worked on similar logic for "write" connections (ConnectionStateHandler class), while Mark has issue I've referenced above. I think once we have finalized design, I think we can figure out pieces of the work and who to assign them. It will probably take many iterations, as any changes in container runtime - loader interaction would need to be staged over multiple releases (most likely, at least to reduce risk of non-performant behavior, as we can easily make it correct in one go, but non-performant - always reconnect as "read" unless container runtime has new functionality).

**Comment by vladsud** [comment]
@ChumpChief - FYI

**Comment by markfields** [comment]
Unsure if I have much bandwidth for this in Jan, but we can discuss priority.  @jatgarg how about you?

**Comment by jatgarg** [comment]
Unfortunately, I don't think I have bandwidth in Jan for this too.

**Comment by markfields** [comment]
> We already wait for own leave message before raising "connected" events for "write" connections

I've been looking closely at this code in `ConnectionStateHandler` and discussing with @jatgarg this week.  Today, `shouldClientJoinWrite` is a precondition for waiting for previous connection's Leave Op. Rationale being - as far as I understand - that we only need to wait for Leave op if there were unack'd ops that _may_ have been received by ordering service stamped with prior clientId.  In this case, we must wait for those acks and then the Leave op before telling the Runtime we're connected with the new clientId, to avoid duplicating ops in the ordered op stream.

We could certainly remove this check and always wait for Leave op after a write connection. **(1)** Is this part of what you're suggesting?

As for the usage in `connectCore` where it actually overrides the connection mode to be write if it's true, **(2)** are you simply suggesting that we expose a new hook to the Runtime called like `waitingForAcks` and move the implementation in there, rather than making assumptions about client sequence number and noops?  This seems orthogonal to (1) but I may be missing something here.

@vladsud - I snuck two questions (1) and (2) in there, please respond to those to clarify the goal of this issue.  Thanks!
