### ISSUE TITLE
normalizeError should take fluidErrorCode and should not leave it empty

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8472]
```typescript
    const fluidError: IFluidErrorBase = new SimpleFluidError({
        errorType: "genericError", // Match Container/Driver generic error type
        fluidErrorCode: "",
        message,
        stack,
    });
```

**Comment by markfields** [comment]
This was an intentional removal.  See https://github.com/microsoft/FluidFramework/pull/8124.

**Comment by markfields** [comment]
Here's my current thinking:

* `fluidErrorCode` is reserved for errors we create in our codebase (including where we _wrap_ an error, creating a new one). If it's missing, that means the error was thrown to us from some other code (could be an easy approximate solution to epic #8260)
* `normalizeError` simply exists to stamp with `errorInstanceId` and add support for telemetry props
* If we want to track where we saw/normalized an error as it propagates (I think this is useful, even in presence of stack), then two options (they're functionally equivalent, just used/optimized differently):
  A. sprinkle the code with `logger.sendEvent` and then you can aggregate the sequence of events a particular `errorInstanceId` passed through into an interesting list (or just look for a particular event of interest)
  B. Add a new concept to `normalizeError` separate from `fluidErrorCode` that gets glued together into a list, basically collapsing all points of interest into a single row rather than approach (A).  They're otherwise equivalent though.

**Comment by markfields** [comment]
Probably close as By Design, but pending design/review on #8260
