### ISSUE TITLE
Unhandled Rejection 0x265 are hit

### ISSUE THREAD

**Issue by chensixx** [microsoft/FluidFramework#8626]
## Describe the bug

In recent OCE incidents, we found many instances of unhandled rejection that is 0x265 (in summaryManager.stop)

## Example Logs
from `sessionId` 4ff50f44-5d03-4c3e-aeca-6e8c1585c5f8
these are the events that happened right before assert failed
|Event_Time	|Data_eventName	|Data_message_string|
|-----|--------|--------|
|2021-12-29 17:45:40.4220000|	UnhandledRejection|	0x265|
|2021-12-29 17:45:40.4120000|	fluid:telemetry:SummaryManager:EndingSummarizer	||
|2021-12-29 17:45:40.3960000|	fluid:telemetry:Container:ContainerWarning|	0x25d|
|2021-12-29 17:45:40.3940000|	fluid:telemetry:SummaryManager:SummarizerException|	0x25d|
|2021-12-29 17:45:40.3930000|	fluid:telemetry:Summarizer:Running:UnexpectedSummarizeError	||
|2021-12-29 17:45:40.3870000|	fluid:telemetry:SummaryManager:RunningSummarizer_cancel	|0x25d|
|2021-12-29 17:45:40.3850000|	fluid:telemetry:Container:ContainerClose	||
|2021-12-29 17:45:40.3840000|	fluid:telemetry:ContainerRuntimeDisposed	||
|2021-12-29 17:45:40.3810000|	fluid:telemetry:Container:ConnectionStateChange_Disconnected	||
|2021-12-29 17:45:40.3800000|	fluid:telemetry:Container:noWaitOnDisconnected	||
|2021-12-29 17:45:40.3770000|	fluid:telemetry:Summarizer:WrapError	||
|2021-12-29 17:45:40.3740000|	fluid:telemetry:Summarizer:StoppingSummarizer	||
|2021-12-29 17:45:40.3700000|	fluid:telemetry:Container:connectedStateRejected	||
|2021-12-29 17:45:40.3700000|	fluid:telemetry:DeltaManager:ReadConnectionTransition||	
|2021-12-29 17:45:10.3060000|	fluid:telemetry:Summarizer:Running:UnexpectedSummarizeError	||
|2021-12-29 17:45:10.2930000|	fluid:telemetry:Container:connectedStateRejected	||
|2021-12-29 17:45:10.2930000|	fluid:telemetry:DeltaManager:ReadConnectionTransition	||
|2021-12-29 17:40:09.8140000|	fluid:telemetry:Summarizer:Running:Summarize_end|	summaryAck|

**Comment by pleath** [comment]
SummaryManager.stop is apparently being called while SummaryManager is already in a stopped/not-started state. My guess is that we call stop() first via the "disconnected" event handler (note that these asserts all seem to coincide with a Container disconnect) and then, without checking SummaryManager.state, in the catch handler in SummaryManager.startSummarization. 2 possible solutions: 1. check the state in the catch handler before calling stop(); 2. check the state in stop() and, instead of asserting, do nothing if we're already in a stopped/stopping state. There's no reason why we couldn't do both. My preference is to add a state check to the catch handler first to confirm that that's the source of the assert.
