### ISSUE TITLE
"Summaries: Should generate summary tree with isolated channels disabled" test failing in real service

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#8637]
The real service tests are failing - https://dev.azure.com/fluidframework/internal/_build?definitionId=56&_a=summary.
The logs in the pipeline run don't have information on which test is failing but on running locally, I see this failure consistently:

```
"Summaries: Should generate summary tree with isolated channels disabled" -  Error: Should not have attempted summary with disposed summarizer.
```

**Comment by chensixx** [comment]
so when `result = summarizer.summarizeOnDemand({ reason: "test" });` is called in the test at line 231, i set breakpoint and stepped in, it seems neither summarizer or running Summarizer was disposed here `if (this._disposed || this.runningSummarizer?.disposed)` from summarizer.summarizeOnDemand 
is this relevant? 
@pleath since you worked on this mainly

**Comment by anthony-murphy** [comment]
looks like a timing issue. the test probably needs to wait longer after the stop for the summarizer to actually dispose
