### ISSUE TITLE
ODSP driver: Handle share links whose ODB is moved (e.g. https://microsoft-my.sharepoint.com/ ->  https://microsoft-my.sharepoint-df.com)

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8654]
Data needs to be copied over from https://office.visualstudio.com/OC/_workitems/edit/5534117
Related Incident: Incident-268907204 Details - IcM (microsofticm.com)
Related Teams post: Marco Cimmino Gibellini: Cannot load any more a component within Teams 

Robert Chen will provide more data in the bug RE protocol and expectations for client.
Work very likely will involve not just recovery (for this session), but also some communication to host such that host can fix its URI for future sessions not to hit this problem.
Marco promised to follow up with meeting to get to the plan.

- [ ] https://github.com/microsoft/FluidFramework/issues/9064
- [ ] https://github.com/microsoft/FluidFramework/issues/9067

**Comment by jatgarg** [comment]
From @vladsud 
Changes on FF / protocol side 
1.) TreesLatest will start leveraging new flag to get 308 instead of 404 

- It will generate new error code and will throw it to host to recover. 
- There will be no caching at this layer to optimize experience for future loads 

2.) When any of the driver requests receive 308, driver will remember redirect (in-memory only) and will start supplying this info to token callback (i.e., we will change siteUrl & will add oldSiteUrl to OdspResourceTokenFetchOptions) 

- If we get 308 twice in a row (i.e., token refresh did not fix the problem), FF will terminate session with critical error.  

3.) joinSession should be changed not to use siteUri (origin), such that ODSP can detect request being made using old & new siteURI to be belonging to same file.
