### ISSUE TITLE
Stress: `fluid:telemetry:ContainerRuntime:GarbageCollector:gcUnknownOutboundRoute`

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#8672]
Looks of `fluid:telemetry:ContainerRuntime:GarbageCollector:gcUnknownOutboundRoute` errors in stress runs:
let buildid = "47789";
office_fluid_ffautomation_error  | where Data_buildId  == buildid
| project-reorder Event_Time, Data_eventName, Data_error, Data_message, Data_reason, Data_loaderVersion, Data_runtimeVersion, Data_stack, Data_fluidErrorCode

**Comment by anthony-murphy** [comment]
@agarwal-navin this bug will block the release that should happen at the end of this week

**Comment by agarwal-navin** [comment]
Yes, I have been debugging this since last week but with no luck. If I can't figure it out before release, we can disable this event.

**Comment by agarwal-navin** [comment]
Ok, I finally figured out what's going on. A lot of things has to happen for this to repro and it could only happen in the stress tests, so yay for stress tests :-).

**Repro steps:**
Here are the sequence of steps to repro this issue:
1. Enable GC, have a few data stores and summarize a container. Close the summarizer.
2. Load a new summarizer with GC disabled, update a few data stores (not all) and summarize it. Close the summarizer.
3. Load a new summarizer with GC enabled, add one or more new data stores (or DDSs) and summarize it.
4. When GC runs in step 3, it throws the error `gcUnknownOutboundRoute`.

**Root-cause**
In step 2 in the repro-steps above, when GC is disabled and only some of the data stores are updated, it re-summarizes those data stores and updates their GC data as empty. However, for data stores that did not change, the data from the previous summary is used and their GC data is not reset.
When a new summarizer is loaded from this summary, some of the data stores have GC data and some don't leading to an inconsistent state.

**Fix**
This will be fixed when we enable writing all GC data at the root of the summary tree which was merged via [this PR](https://github.com/microsoft/FluidFramework/pull/8389).
However, since we are currently writing GC data at the data stores layer, this has to be fixed at that layer too. The fix should be to regenerate the summary for each data store and reset the GC data. I am working for this and will send out a PR soon.
