### ISSUE TITLE
azure-client support for long connected sessions

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#8745]
## Overview

Fluid Framework has a default behavior of reconnecting a container when a web socket expires or loses connection. This can result in long running sessions when a user leaves a tab open. These long-connected sessions cause additional load on the server and result in additional COGS for our customers.

## Key Result
- There are exposed APIs that enables developers to connect, disconnect, and set the reconnection policy in order to control the connection state and COGS.

## Solution Design
There is a lot of information which the application using Fluid has access to which Fluid itself does not. Some of this information can help determine whether a user is "active" or "inactive", for instance, a user moving their mouse. Additionally, the definition of "active" may vary from application to application. Because of this, the developer is the party best suited to manage a user's connection state. In order to provide the developer control over the connection state, we will be making changes to the following APIs on the container level.

#### `Container.setAutoReconnect()` - Deprecate
Although we want to give developers more control over the connection state, we still want to keep reconnection logic internal. To prevent developers from accessing reconnection logic we will deprecate `Container.setAutoReconnect()`. To replace its functionality, we will introduce `connect()` and `disconnect()`, which will be described below.

#### `Container.resume()` -> `Container.connect()`
To give developers a more intuitive API to connect a container, we will introduce `Container.connect()`. This function will attempt to connect the container and set the reconnection policy to always try to reconnect if the conneciton is dropped. The functionality will be very similar to the current `Container.resume()`, therefore `resume()` will be deprecated and removed.

#### `Container.disconnect()` - Create
Similarly, we will need to introduce an API to disconnect a container. This will also prevent the container from reconnecting automatically without calling `connect()`.

#### `IFluidContainer.connectionState` - Create
To make `IFluidContainer` consistent with `IContainer`, `IFluidContainer.connectionState` will be added to represent the container's current connection state.

#### `IContainer.connected` & `IFluidContainer.connected` - Deprecate
`connected` and `connectionState` serve the same purpose. Therefore, we will deprecate and remove `connected` on both interfaces.

Note: In the future we want to create functionality to control the connection state of all containers via `Loader` or a new scoping object.

## Tasks

- [x] Tech Spec outlining 3 options and 1 recommendation
- [x] Create corresponding issues depending on direction
- [x] #9168
- [x] #9396
- [x] #9167
- [x] #9397
- [x] #9170

**Comment by vladsud** [comment]
RE Notes section:
- Building on top of setAutoReconnect() - that's rather orthogonal to how IContainer looks like. And yes, we should favor composition (and separate layers) over putting everything on container. But the way I read that first note - we already have what we need - it's setAutoReconnect(). If higher-level scenarios need to be built, they need to be built as separate layers.
- I've left comment in #8708 - that a ton of work, and I do not think we want to iterate and experiment here for quite a while before considering anything we built to be public API.

**Comment by scottn12** [comment]
Based on the feedback over the past few days, the solution has been adjusted to take a new approach. In addition, this issue's description has been updated to provide additional context and a high-level overview of the problem/solution. Before moving forward and finalizing the tasks, please leave any feedback/questions you may have here. @vladsud @anthony-murphy @skylerjokiel @heliocliu @ChumpChief @ssimic2 @tylerbutler 

Note: The tasks will be updated when the solution design is more settled.

**Comment by vladsud** [comment]
I understand connect() & disconnect() flow (that's what setAutoReconnect() does today in one API).

I'm not sure I see the scenario where user wants to control reconnection flow only, but not change current (connected or disconnected) state.
Maybe other way to ask it - why user even needs to know that there is reconnection logic? Can we not expose it at this layer?
I'll use analogy of internet adapter on PC - you can disable or enable it, but user is not exposed to controls like "if cable is disconnected for a moment or router reboots, please do not reconnect to it". It seems pretty silly to have that option, as it would only confuse users. It does feel like analogy is applicable here, but I'm happy to be wrong (would love to hear more on that).

Some historical context: setAutoReconnect(false) was previously not disconnecting socket right away but would not reconnect on loss of connection in future. We essentially relied on ODSP behavior of disconnecting socket every 15 minutes. That is being changed and socket might be alive for hours, so I changed it and now setAutoReconnect(false) results in immediate disconnect.
It was also very hard to follow telemetry (and get any believable data) as quite often browser would freeze tab, and thus all events (including disconnect events) would fire many hours later when user would come back, even though connection was lost way earlier.

**Comment by scottn12** [comment]
> I'm not sure I see the scenario where user wants to control reconnection flow only, but not change current (connected or disconnected) state.

I definitely agree that this is an uncommon scenario, however I do believe it is still something we would like to support. Since we would be pushing the responsibility of connection state to the developer, we want to give the developer proper control over each aspect of connection. 

If we are worried about confusing the developer, one option is to call `setAutoReconnect(true)` as part of the `connect()` flow. This would require developers to explicitly call `setAutoReconnect(false)` in order to disable automatic reconnection. This would probably be preferred, since the vast majority of developers will likely want automatic reconnection enabled after calling `connect()`.

**Comment by vladsud** [comment]
If we do not have clear scenario or clear partner ask, then we should not add new API. Once it's there, there is no way to remove it, and we will continue to pay support cost.  I believe reconnection logic should stay internal business. Clients should only be exposed to boolean state - either they want to see container connected or disconnected. They express their intention, and framework does its thing to get to such states.

The only exception to this is agents (including summarizer), and I'd say that even that should be gone at some point, as it's too expensive way of achieving our goals (we create & destroy these agents on each connection loss).

**Comment by vladsud** [comment]
@skylerjokiel, I'm fine with that (expose what setAutoReconnect in different packaging).

I do not see a need for
- exposing to control auto-reconnection logic
- converting from push to pull (i.e. instead of APIs that customers can call switch to providing callback that is called by framework).

Moreover, I think these constructs should stay internal implementation details (not leak) and they will (and are) not true for all usages (for example, driver that does not use socket for communication does not have these concepts, a good example of that is Word over OCS). I think these concepts should eventually move into drivers and not exists at loader level. The only two concepts that should exists - does container tries to maintain connection, or it's disconnected, no states in between.

**Comment by scottn12** [comment]
> I do not see a need for
> 
> * exposing to control auto-reconnection logic
> * converting from push to pull (i.e. instead of APIs that customers can call switch to providing callback that is called by framework).

I agree that we should not convert push to pull, and this is reflected in the updated GitHub descriptions as well.

> The only two concepts that should exists - does container tries to maintain connection, or it's disconnected, no states in between.

@vladsud and @skylerjokiel, I just want to clarify that we do **not** want to support a scenario where a container is connected but does not try to automatically reconnect. 
If so, we can go ahead and modify the solution design to create/expose `connect()` and `disconnect()` which will call `setAutoReconnect(true)` and `setAutoReconnect(false)` respectively. Alternatively, we can simply expose `setAutoReconnect()`, however I prefer using `connect()`/`disconnect()` since it is more consumer friendly (as Skyler mentioned).

**Comment by vladsud** [comment]
That's fine with me, but you probably want to
- merge newly created connect() with existing resume() functionality and have just one API for that.
- Consider changing name form "connect" to something that has less certainty about what would happen, i.e., developers should think about it as "we will try to connect and maintain connection", not "one gets connection right away after this call".
- We should start to "tax" work items like this one with exposing this at loader level and applying to all containers under loader management. And ideally - not having these methods on Container / IContainer at all. I can go into details on why this is the right place to expose all these APIs.

**Comment by scottn12** [comment]
@vladsud, could you expand more on your last point? I'm interested to know the reasoning behind exposing these APIs on the loader level. Are there any other advantages other than applying the action to all containers created by the loader? Also, I'm unsure how these APIs would be accessible from an `AzureClient` perspective, because `AzureClient` users don't directly interact with the loader. They do have access to the container, however there is nothing exposed on `IFluidContianer` to give access to the loader.

**Comment by vladsud** [comment]
Sure!

There are couple reasons. They may not be interesting for 3rd party SDK world where loader === container, but it's not true for more general case where
1. Loader could have multiple containers
2. Loader is caching containers and they could be reused (i.e. request to resolve URI will return existing container that someone else is already using).
3. A container itself can request loader to open a new (child) container - this is used to implement guest component features (i.e., one fluid file has a reference to component in another fluid file, and it renders in-place). In case of such relationship, a hosting app may not even know / realize about such child containers.

This results in couple interesting dynamics:
1. Users of the system may not realize that changing some settings on a container may screw up some other user of same container. Much better to have a scoping / context object where such policies are exposed (and Loader is such object).
2. host need an object to set such policies to apply to main container it has access, and any child containers opened by main container. Again, the best direction is to use context object - loader.

This assumes, of course, that players in the system can create new context objects (loader instances) as they see fit, to break this linkage and control policies independently for newly created container.

**Comment by markfields** [comment]
Following!

**Comment by vladsud** [comment]
I'd add one thing: it's more obvious to users of the system that changing setting on loader has bigger impact (all containers under loader) and thus developers are more likely to create new loader instances if they want unique properties / settings for their containers. When such controls are exposed on container, it's not very clear that same container may have multiple users working with same object (due to loader handing over same container instance when resolving URI).

It can be somewhat resolved through education, but we should strive to make default / the easiest way to use system to be correct one and allow more complicated scenarios. It's sort of goes in this order:
1. Very simple usage: loader === container, does not matter where controls are exposed
2. More nuanced usage - guest components, multiple loader users - system should push people to right patterns
3. Really complicated usage - possible, pushed people to create their own loader objects and have deeper understanding of the system.

I worry mostly about # 2 - clients having rather basic understanding on the system, and not even caring about how it works, and thus being more vulnerable to misuse.

**Comment by scottn12** [comment]
After more discussion we came to the following conclusions:

1. The new `connect()` and disconnect()` functions will be implemented on the container level.
2. We will want to introduce functionality in the future which uses `Loader` or a new scoping object to change the connection state for multiple containers.
3. `setAutoReconnect()` will be deprecated to keep reconnection logic internal. Its functionality will be replaced by `connect()` and `disconnect()`.
4. `connect()` will likely have the same functionality as `resume()`, therefore `resume()` will be deprecated.
5. `IContainer.connected` serves the same purpose as `IContainer.connectionState`, therefore `connected` will be deprecated.

The description of this issue has been updated to reflect these changes, along with additional details.
