### ISSUE TITLE
Use refreshSessionDurationSeconds in JoinSession response to recall JoinSession

### ISSUE THREAD

**Issue by xinyxu** [microsoft/FluidFramework#8748]
## Feature
**Is your feature request related to a problem? Please describe.**
We will send a new field **refreshSessionDurationSeconds** in JoinSession response. Change is here https://onedrive.visualstudio.com/OneDrive%20Service/_git/VroomCore/pullrequest/865522. This is the time span client is allowed to connect to Push session. Client should use this value to recall JoinSession in time to keep web socket connection with Push. Once client can frequently make JoinSession request, Push can remove CheckAccess request.

**Describe the solution you'd like**
Client should use **refreshSessionDurationSeconds**  to recall JoinSession in time to keep web socket connection with Push. If client fails to recall JoinSession in **refreshSessionDurationSeconds**, Push disconnects it.

- Note if client sees a 401 response from JoinSession, it should fetch a new token and recall JoinSession in refreshSessionDurationSeconds. 
- If client sees a 200 response, it should recall JoinSession in refreshSessionDurationSeconds.
- RefreshSessionDurationSeconds is relative time span in seconds. It will be at most 15 minutes. 
- This is how we will calculate it:
  RefreshSessionDurationSeconds  = current time + grace period, if SPO auth token expires less than grace period.
  RefreshSessionDurationSeconds  = min(current token time + refresh interval, tokenExpirationTime), if SPO auth token expires more than grace period.
- SPO controls refresh interval and grace period. We plan to start with refresh interval 15 min and grace period 5 min. We should adjust them accordingly.

**Existing work**

**Describe alternatives you've considered**

**Additional context**
Design doc: https://microsoft-my.sharepoint-df.com/:fl:/p/garywilb/Ee3WV4s4yXRClSef99aBDasBsica00TwI2_7RxoGHxXlqQ?e=Nguda5
Security Review doc: https://microsoft.sharepoint-df.com/:li:/t/ODSPSecurityReviews/E9HmumkUFFVGuYrumN9n9K4B7ZTX0wlGVmtpP6kSB-tPfQ?e=TfimdJ

- The doc explains the reason why we want to remove CheckAccess and replace it by client make frequent JoinSession request. 

- The final option we chose is option 1.

**Comment by vladsud** [comment]
Based on my understanding, this should be a best effort for February, as issue 8654 has much higher priority (at least first part of it - TreesLatest workflow).
That said, this item does not feel like large one, and it has quite an impact on many things, including COGS on SPO side, and ability of summarizer to stay around longer on connection and not keep losing it (and thus summarizer moving around), which has impact in prod, but also in out scalability tests.

So, if we could fit it into Feb - great, otherwise it should be one of the main issues in March to work on.
