### ISSUE TITLE
read to write state transition need to be <1 second

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#8797]
It's been reported by partners that the user state transition from read to write mode can come with up to a 7 second delay. This was reported using Azure Fluid Relay where an op was not seen for 7 seconds while transitioning. I don't have further details of how this was measured.

There could be multiple factors to this including the need to get a new token, handshake with the server and establishing a new connection. 

## Key Result

- Read to write transition is <1 second

**Comment by kailui** [comment]
I am the partner who reported that 7-second latency of the first Fluid op.

In my scenario, I use Fluid + FRS to sync document model data between a browser and a service.
The flow is something like this:

1. Server creates a new empty Fluid container.
2. Server sends the Fluid document ID to the browser.
3. In parallel, server loads the Fluid container with document data.
4. Browser gets that data as one or more ops via the WebSocket.

In my local testing, it can take 2-8 seconds for the browser to get the first op message from the WebSocket after connecting to the container.

If I load the initial doc data into the Fluid container first before attaching it, that data will not be sent via the WebSocket. Instead, browser will load it directly at doc open time. That way, it takes about 600-800ms for the browser to get that data on app boot. The drawback of this approach, however, is that the server has to wait till attach has finished before it can send the Fluid document ID to the browser. That forces a sequential order of execution. The browser cannot establish the WebSocket connection earlier during boot. This impacts app boot time.

With further debugging, I noticed that when the app server set data into the DDS for the first time, the container disconnected and reconnected with reason of "switch to write". Initially the connection mode was "read". That reconnection is what caused the app server side of Fluid runtime to delay sending the initial ops by 5 seconds or more.

So as a workaround, if I pass in a "write-mode" IClient via the ILoaderProps when creating a Loader, the resulting container will be "write" and the 5-second op delay mentioned above will go away.
```
        return new Loader({
            urlResolver: this.urlResolver,
            documentServiceFactory: this.documentServiceFactory,
            codeLoader,
            logger: this.props.logger,
            options: {
                client: {
                    details: {
                        capabilities: { interactive: true },
                    },
                    mode: "write", // <-----
                    permission: [],
                    scopes: [],
                    user: { id: "" },
                }
            }
        });
```
Unfortunately that means I cannot just use the AzureClient as-is to connect to FRS because it doesn't expose the ILoaderProps. I have to write some of AzureClient's logic myself.

And after all, I do not think a "write-to-read" transition should cause op sending to be delayed by that much. In fact, this detail about "read mode" and "write mode" should be encapsulated from typical clients.
