### ISSUE TITLE
Potential eventual consistency issues with SharedDirectory subdirectory deletion/creation

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#8823]
This is very long thread, so I've summarized **proposed solutions** at the bottom of this post

## Design and implement events for the creation and deletion of subdirectories.

Also consider that the scenarios in which events are suppressed may be more complex than for key set/delete since the contained values of the subdirectory could end up different.  The logic is more complex than "last write wins", which is part of what #6069 needs to address.  One example:

1. ClientA - create subdir "foo"
2. ClientB - create subdir "foo"
3. ClientA - set key "foo/keyA"
5. ClientA - delete subdir "foo"
6. ClientA - create subdir "foo"
7. ClientA - set key "foo/keyB"
8. All of ClientA ops get sequenced
9. All of ClientB ops get sequenced

Expected eventually-consistent result is that both clients see subdirectory "foo" with a key "keyB".  ClientA's events seem fairly straightforward (probably just ignore the superfluous creation from B when it gets sequenced), but it's less obvious to me what events ClientB should see and in what order.

* **_Probably bad:  ClientB sees no events for ClientA's create/delete._**
ClientB would have no clue that "foo/keyA" is now gone.  This is the status quo given the currently LWW approach for subdirectories.
* **_Probably bad:  ClientB gets events from ClientA's create/delete but cannot distinguish them from the scenario where they have no outstanding create of their own._**
In this scenario ClientA's delete should only delete the ack'd contents of "foo" -- from ClientB's perspective "foo" should still exist locally (it is still awaiting its own create to be ack'd) and also any unacked contents ClientB may set (which will be sequenced after their own create).  Whereas if ClientB had no outstanding create of its own, ClientB would immediately see "foo" get deleted.  So, ClientB probably wants to know if "subDirectoryDeleted" actually deleted the subdirectory, vs. if it's actually still there due to a pending op.  Or at minimum, we'd need to specify that "subDirectoryDeleted" might not mean the subdirectory was actually deleted and that customers should inspect to see if its still there.

### Copied over #6069

Assume a subdirectory `/foo` and supposing two users do the following:

User1: Sets key `"bar"` to value `"baz"` inside subdirectory "/foo"
User2: Deletes subdirectory `/foo`
User2: Creates a new subdirectory `/foo`

// At this point, User1 sees 1 key in `/foo` and User2 sees 0 keys, which is OK since the messages have not been ordered/transmitted yet.

*Messages for the above are ordered and transmitted*

// At this point, User1 sees 0 keys in `/foo` and User2 sees 1 key, which is not OK.  Expected is that both see 0 keys.

The issue being that User2 doesn't realize that they saw the `"bar"` set before they saw the ack of their subdirectory delete, and so will happily apply the set operation to the new subdirectory they just created rather than tossing it out as applying to the already-deleted subdirectory.

Note that this could happen in other variations too:
1. Deeper subdirectory nesting, e.g. `/foo/bar/baz/woz` and User2 deletes/recreates the full chain of `bar/baz/woz` while User1 sets a key in `woz`.
2. Creation of subdirectories rather than key sets -- e.g. User1 is trying to create subdirectory `/foo/bar` while User2 is deleting/recreating `/foo`.

Discovered by code inspection while looking at #6015.

## Summary of proposed solutions

1. Make directory essentially a map, with no ability to observe sub-directory lifespan. They are created implicitly when any key is set under given path and removed when all keys under path are gone.
   - There will be no _create_ or _delete_ or _does-exist_ primitives for sub-directories (one can create in-memory objects for any sub-directory, but there are no ops for sub-directories, with exception of _clear_ operation), but there will be _clear_ primitive to remove all the keys under certain path (subdirectory).
   - In order to leverage correctly such primitive, we need to break key operations into "set" and "replace" (essentially LWW & FWW merge policies), to give ability for clients to change the keys only if (essentially) whole sub-directory is still there
   - OR we do not provide such primitive, but app can create _isActive_ key or equivalent to note if sub-directory is active (or should be considered deleted). That way, _clear_ and _key set_ resolve in abandoned key, but app can disregard it. Assumes some level of GC in future.
   - See [here](https://github.com/microsoft/FluidFramework/issues/8823#issuecomment-1027457885)
2. Leverage mostly LWW policies for all directory operations, including sub-directory creation (creation === delete & create, it always wipes out prior content). Simple, but has two bad side-effects:
    - some responsibility moves to clients RE correct usage. Clients need to create and initialize sub-directory in one batch (which is not a bad rule in either case)
   - A key change for non-existing directory (at the time op is sequenced) is dropped on the floor, thus breaking LWW promise.
   - Solution described in more details [here](https://github.com/microsoft/FluidFramework/issues/8823#issuecomment-1040749449)
3. Similar to above, but sub-directory creation / deletion follows FWW rule. We essentially give sub-directory objects identity (guid), and any un-mounted sub-directory objects (by deletion, including creation of new sub-directory object with same path) can still receive ops, but they do not impact directory anymore.
   - [Full description here](https://github.com/microsoft/FluidFramework/issues/8823#issuecomment-1026065494), with Daniel's [follow up](https://github.com/microsoft/FluidFramework/issues/8823#issuecomment-1026265233).

**Comment by vladsud** [comment]
> ClientA's events seem fairly straightforward (probably just ignore the superfluous creation from B when it gets sequenced)

I'm not sure on that. I.e. I'm not sure it's the conclusion I'd jump right away as I think creation (with semantics we have today) is the source of the problem.
For example, if creation op always wipes out content of existing sub-directory with same name AND every op (including creation) mentions identity of sub-directory instance (guid assigned at creation), then
- all ops for "another" instance of sub-directory with same name are easy to ignore (if latest state has different guid).
- creations are not coalesced, last one wins, another one loses, and all the ops for that loser will be ignored.

Basically, it's the same problem as assigning alias / name to root data store. Either need synchronization or overwrite semantics.

I think other solutions are possible here (with tracking more state for in-flight ops) to make it eventually consistent, but I'm not convinced it will result in something user wants. I.e., if clients operating on sub-directories likely expect certain structure (certain keys filled in on creation of sub-directory to be always there) and would be very surprised to find no such structure (and just a single key) if one client deleted sub-directory concurrently with another client changing single key in such sub-directory (latter ordered last). So, I think clients would prefer sub-directories to have identify that is defined not just by its name (but also includes guid assigned at creation).

I have not though about it, but maybe it's possible to support other types of creation disposition (see dwCreationDisposition in [CreateFile](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea)), it's just that CREATE_NEW type of creation disposition (what we have today) likely requires synchronization and different modes likely can't be used on same name / directory (i.e., it's impossible to describe how they compose). So maybe (in some distant future) we will decide to support different modes for directory as a whole (mode fixed at creation).

P.S.: It's interesting that win32's [CreateDirectoryEx](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createdirectoryexa) does not provide same abilities to RE controlling creation disposition modes.

+@nanorga +@jatgarg
Also +@DLehenbauer for thoughts on how other DDSs (Shared/Property Tree) approach same problem of sub-tree identity management

**Comment by jatgarg** [comment]
The CreateDirectoryEx, returns error code on creation of another directory with same name. So we can consider following the same structure or probably not if this does not serve the requirements of apps. 
I do the like the idea of introducing guid for subdirectories so that we can separate ops for those as in if User1 creates subdirectory foo and then user 2 creates another foo and then user 1 deletes foo that he created then after all the process we will still have foo that user2 created with a different guid. This does for other operations too. But  currently for ex. the getSubdirectory() takes name as input to return the corresponding subdirectory. But after allowing same name subdirectories with different guid, would we be passing guid along with name as input?

**Comment by nanorga** [comment]
For our usage, I don't see any issues with the "overwrite on create" proposal.

The most common scenario we have where something will be removed then re-added with the same key is undo and redo. My expectation is that the 'redo' operation will boil down to us re-adding each item in the subdirectory one-by-one, so starting from a 'blank' slate is perfectly fine.

I think solutions where we try to resolve conflicts by merging subdirectories together will be overly complex and prone to all kinds of problems.

Our directories behave like the C++ objects they represent. If we create/allocate a new object in C++, we proceed to set all its members. If a new one is created, the old one is freed and the new one takes over and all its members are again initialized.

**Comment by vladsud** [comment]
Thanks Nate! I'll point out that redo (in your example) will wipe out changes from other clients in between undo & redo (if they created same sub-directory). But I think it should not be resolve at that level.

If we go with "overwrite on create" proposal, then I see 3 options RE how it's implemented:
1. Can we leverage existing map / directory logic here somehow? Are there any other simpler ways of achieving same thing?
2. Each directory op has new "identity" property - uuid uniquely identifying instances of sub-directory, in addition to keeping path property. Summaries need to also store uuid of each sub-directory. Each client implements LWW by tracking local "lie" (uuid for create/delete operations) until its ops are acked, as well as current (acked) uuid for each sub-directory.
   - con: bigger op sizes
3. Same but remove path from op payload to reduce payload size.
   - pro: smaller payload sizes
   - con: need to track uuid -> path mapping on each client (as well as un-acked local changes) and rebuild mapping on load. But do not need to track per-client info, only acked state and local (this client) state. All ops for unknown uuids are ignored.
4. Each client tracks (path, seq#) -> uuid (changes on sub-directory create & delete), and (path, ref seq#, clientId) -> uuid (changes as client creates or deletes sub-directories, and when client's ref seq# moves forward) to be able to calculate uuid for each path + client combo at any moment in time. Same info is written to summary, of course. No changes in op payload size, as identity (uuid) can be recalculated on each client individually.
   - pro: exactly same op payload
   - con: much more complicated and error-prone code.

Note: Opened #8938 to consider using more compact version of uuid generation.

I'd go with # 2 initially (as it seems like the most trivial to implement), followed by # 3 (as a way to compress payload sizes).
I feel like # 4 is the ideal, but a bit too complicated solution. That said, if there is any way to reuse code and get # 4 out of existing building blocks, or produce common building blocks that can be reused later in other DDSs, I'd consider it.

Note that we also need for sub-directory to throw some error when in-memory objects are used after it was deleted.

**Comment by DLehenbauer** [comment]
Just FYI - Vlad's suggestions are progressing down the same evolution as SharedTree (ids on every mode, using id's exclusively in ops, compressing the ids, and then eventually switching to paths with sophisticated rebasing in order to partition edits without maintaining the id maps in memory.)

The other interesting point in the design space is the 'Git' like approach of implicitly creating/destroying directories based on if they contain items.  Concurrent insertion of different keys under the same new path will implicitly create identical directory structure and the keys at the leaves merge with LWW semantics.  If you desire 'id' semantics, you use compound paths like '/name/uuid/', which is a bit yucky, but also a familiar technique from file systems.

**Comment by vladsud** [comment]
I thought about implicit creation, but then directory becomes pretty much a map :)
We would still likely want to have "delete sub-directory" primitive, which would have pretty much same issues as today (what happens if sub-directory delete happens at the same time as another client changes a key?), resulting either in orphan keys, or a need for some kind of serialization on app side to avoid running into such cases. So, I'm not sure it's great solution.

Possible solution in this space - separate existing "set of modify key" primitive into three primitives - "create or overwrite key", "modify if exists key" and "delete key" primitives (later can potentially be merged with second one). That way we can give developers more control to create content in one go (using first primitive), and then leverage second primitive to keep making changes to keys until sub-directory is deleted. It assumes that new keys are not added after initial creation.

**Comment by vladsud** [comment]
@nanorga, please glance at my last reply RE potential alternative.
I think we still prefer to overwrite on create for sub-directories, but worth considering alternatives before committing.

@ChumpChief - would be great to hear your thoughts on proposed direction.

**Comment by vladsud** [comment]
Given amount of content in this issue, I'll repropose it to track eventual consistency issue, not events.

**Comment by DLehenbauer** [comment]
@vladsud - Distinguishing 'set' (update or insert) from 'replace' (if unchanged) is good.  Share.js and others make the same distinction.

I'd suggest the verb 'clear()' instead of 'deleteSubDirectory()', where removing all keys implicitly removes the directory.  As you say, clear() would cause a subsequent 'replace()' to fail, while 'set' would implicitly re-create the directory by repopulating it.

I agree with #8969, where you state that the directory events should be a reflection of local state changes.

**Comment by vladsud** [comment]
I have some second thoughts here. Mostly due to two things:
- main [solution](https://github.com/microsoft/FluidFramework/issues/8823#issuecomment-1026065494)  proposed earlier is complicated and hard to explain.
- It uses a combination of LWW (last writer wins) and FWW (first-writer-wins) for different kinds of interactions, which is not consistent (LWW for keys, and FWW for nodes).
   - Sidenote: I do not think we ever examined LWW rule across framework and if FWW (in case of conflict, i.e. client not observing other changes) is a better overall strategy, as it gives the looser obvious point to recover (re-merge). And we (today) use combination of LWW & FWW across repo, which is obvious inconsistent, and likely will likely result in very interesting bugs.

Here is one other possible solution in this space:
1. We use LWW rule across the board, including creation / deletion of sub-directories.
   - One important exception: an op that sets the key in sub-directory that does not exist (at the time when op is sequenced) results dropping this op on the floor.
2. Create sub-directory overwrites previous content of sub-directory (exposed as delete + create events, if sub-directory already existed).
3. We issue disposed events for sub-directories and abandon this instance (in-memory), and if sub-directory is recreated, it's a new im-memory object.

This is much simpler implementation, but it pushes some responsibility to users. I.e. I'd expect creation and initial population of sub-directory to happen in one batch, to ensure that all that activity is handled together (goes through and overwrites whatever content was there, no partial execution).

1b & 3 can be modified to add strict LWW, and thus implicit directory creation on any key change. But this makes it really hard to leverage directories and keep app level constraints (sub-directory either does not exists, or fully initialized and its content makes sense from app perspective), and likely requires "set" and "replace" semantics for key changes as mentioned in earlier comment.

**Comment by vladsud** [comment]
Put summary of discussions in first description for easier navigation

**Comment by anthony-murphy** [comment]
so i've briefly skimmed this. My 2cents are that directory should be a simple dds, and basically a map but with a slightly nicer api that lets you get partitions (directories). Thes partitions(directories) can be passed around, and to consumers it just looks like they have a map. To me this is option 1, directories implicitly exist if they have keys, and do not if they do not have keys. The api can still support getting or holding am empty directory, but it is just an in-memory construct. 


I don't understand the need to separate "set" and "replace", this seems like unnecessary complexity. If we absolutely need the ability to make a directory empty rather than clear, i'd consider something like #8690 (obliterate).  Obliterate would operate on operations it hasn't seen. Basically, all map operations with a ref seq below the sequence number of the obliterate op would be ignored.

**Comment by vladsud** [comment]
Thanks Tony! I've updated description in original post with a bit more cases based on our offline discussion.
_obliterate_ and _replace_ are very similar in nature as they essentially provide FWW resolution. The shape might be different - it can CAS (compare-and-swap), limited CAS (replace if undefined), or something similar. The only difference I see is how such primitive interacts with LWW operations (set). While it's important, I'd think that most users would need to use either LWW or FWW resolution for a key (and not mix them, other than maybe initialization if it does not matter there), and thus I find it less interesting (when making decisions on which way to go). That said, I find CAS kind of primitives easier to reason (and how they interact with LWW operations), as that's how shared memory works in multi-threaded world, and thus there is a lot of experience / research to tap here.

**Comment by anthony-murphy** [comment]
The first above scenario seems to assume that directories are real things that can be created and removed, but i'm not sure we need that. If we say they are just virtual then a and b both get a local instance of virtual directory foo (no ops). it is empty. a sets some keys, maybe sets and delete keys, b sees whatever keys still exist. If it was useful there could be events that say directory foo has keys, and directory foo does not have keys at any particular time based on the local state, b is still allowed to have a local instance whether is has keys or not. Then the problem becomes what operations can be done on keys, rather than what operations can be done on directories. This seems like a simpler model to me.

**Comment by anthony-murphy** [comment]
so looking at the directory code. it looks like it has existing ops for directory operations. it also looks like the real issue is the second scenario. I think this can be pretty easily fixed my appropriately managing sequence numbers. Basically, on create the dir gets a seq, and only sets after that seq apply, those below that are just dropped on the floor. you can also allow coalescing creates.

Are we trying to redesign it, or just fix it?

**Comment by vladsud** [comment]
Just fix it :) And yes, I'm gravitating toward # 1 (virtual directories).
I believe your last post is describing solution # 2 or # 3. I.e., depending on how overlapping creates, create + delete compose (LWW or FWW), it's hard to say what exactly you mean. sets are easier, as it's somewhat expected that if two clients concurrently created and populated sub-direction in one batch, then only one set of changes will survive (not merge of those changes).

**Comment by anthony-murphy** [comment]
if i were just going to fix it i'd do something like this (super hacky and untested proof of concept):
https://github.com/microsoft/FluidFramework/compare/main...anthony-murphy:dir-fix

basically, dirs need a create seq and only actions above the create seq or by the create client are allowed to go through. it's very similar how we coalesce deletes in merge tree, only this coalesces inserts. there would need to be a bunch of work to handle detach and emit the appropriate events on the appropriate clients. I need to think more, but i think we really only need to track the sequence client meta data for create. once the dirs create seq drops below the msn, we can throw that data away.

**Comment by jatgarg** [comment]
@anthony-murphy "basically, dirs need a create seq and only actions above the create seq or by the create client are allowed to go through. it's very similar how we coalesce deletes in merge tree, only this coalesces inserts."
Does this mean that creating a sub directory which already exists would be a noop and then any modifications by any client on that subdirectory would merge the changes(i.e. work on same subdirectory)? So I am assuming it will be called as FWW for creation of subdirecotry?

**Comment by jatgarg** [comment]
https://dev.azure.com/fluidframework/internal/_workitems/edit/512
