### ISSUE TITLE
Documentation for building complex application with azure-client

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#8849]
[Edited on April 15th]

This work tracks 200 & 300 level tutorials/classes on ff.com 

To summarize current thoughts here (and collect some feedback from the team):

### Goals ###

As stated above, create a set of examples that allows developers to understand concepts that will allow them to build complex applications with Fluid. 

### Assumptions ###

Our documents/examples should reflect the assumed persona associated with first-time usage:

FF will likely be used to extend some existing app with an add-on feature/experience.
FF will likely be used for transient data while the source of truth will be somewhere else.
FF will likely deal with smaller data sizes, while needs will be around fast, high-frequency collaboration.

### Concrete Reference Example ###

As we develop documents/examples it would be nice to be clear what areas/topics are more important than others and is there any ordering pattern we can observe. Then, instead of creating multiple disconnected examples, we could progressively bring one example use-case to completion, while demonstrating solution patterns for each topic as a separate step in that same example.

As we discuss various topics it may be helpful to keep in mind a concrete example scenario - just for reference purposes. An example could be an existing app, say, a trip planner, that developer wants to extend to offer users an ability to collaborate on a "todo" list related to each destination they may visit. The app may use FF to build a dynamic to-do list, but it already has its own representation (source of truth) of the trip plan and associated trip details.

### Format ###

We could potentially focus web docs on smaller concepts and code snippets, while keeping an example project as an overall reference on "how everything works together". We could progress the project through different branches (each branch ends up being a step) if we find good progression sequence.

### Constraints ###

At this point in time, we will only be looking at FF as a data layer, without unlocking more complex UI composition patterns. We will not be going into multiple data stores solutions, consumer/producer patterns, etc.

### Topics ###

Topics are listed in no particular order of relevancy, first goal here would be just to surface the most relevant ones.

- Demonstrate what it would take to replace a non-collaborative experience with a collaborative one. This may be less of a "concept" clarification. The goal here is to imply simplicity. In our example - what is minimal boilerplate code it would take to substitute existing functionality (say one user can edit a "todo" list) to "multiple users can collaborate" to build the same todo list. 
- Demonstrate patterns that would play out with other JS libs dealing with data (Immer/Redux, Apollo/GraphQL). The focus would be on a select few, and we can expand the matrix further. The idea would be to showcase how FF can coexist with other data libs while dealing with more complex data structures (we have some examples on immer). Our basic examples mix data & views and imply complex boilerplate code. We need to demonstrate simplicity here, and patterns suitable for integrating with solutions users are familiar with.
- Demonstrate ability to transition from "source of truth" data to FF data, and vice versa - in real-time and explicit import/export. Demonstrate ability to "reduce" data out of both sources.
- Demonstrate the ability for views to consume data in a generic way, without concerns about what the source is.
- Demonstrate suitable data patterns for "collaboration", while structuring FF data in a way that allows users to interact without stepping on each other's actions.
- Demonstrate suitable patterns for container creations and data correlation. Developers will often correlate container IDs to some IDs represented in the "source of truth". Who does creation, when, how do other clients know about it, id mapping etc?
Demonstrate cohesive representation of system's "health", ability to detect errors and recover from them. Now we have multiple states connected/disconnected, saved/dirty, we need to understand if the matrix is simple to interpret, errors are clear etc while investigating "what can go wrong" scenarios.
- Demonstrate ability to measure and monitor system performance (to be expanded. Not sure what examples would be suitable here). Demonstrate general observability of the system.
- Demonstrate patterns around authorization/authentication (to be expanded).
- Demonstrate ability to leverage audience data, correlate IDs with "source of truth", and assign and utilize permissions.
- Demonstrate the capability of various DDSes, while exploring production-grade (100% correctness) solutions. Here we probably need to map each DDS to a strong use case.
- Demonstrate testability of the system. What would unit-test or e2e now look like now that you have FF as part of your system
- Demonstrate patterns around offline work

What other topics make sense for our persona? What would give them confidence to adopt FF for existing application ?
Do we tackle large data now ?
Is Undo/redo a must ?
NodeJS FF patterns?

**Comment by ssimic2** [comment]
Some thoughts/desires after going through the first set tutorials/examples/doc:

As the next step, the desire was to understand how to incorporate FF into an existing app, in some segmented feature, without needing to rely on FF for long term data persistence. Basically, I was looking for simpler scenarios (dealing with data only), that carry less risks, and do not assume FF owning the data in the long term (thus avoiding compatibility considerations). Example would be an app that involves some sort of short-term group interaction, like MyList, where the collaboration experience could be contained to the list item being edited. Once user leaves this collaboration experience, parent app would need to digest FF data without needing to further rely on it. Similar points for rehydration.

High level take aways (learning lessons) I would look for:

	1. How would I structure larger, more complex data? Say the list item has photo, title, category, owner. Say audience can react or drop comments on each item. What do we need to consider from collaboration perspective when organizing data (ex: authors should not step on each other while editing)? What do we need to consider (in terms of initialization) if we can potentially have a large list of items? Organization decisions here, obviously may create impedance against existing data views.

	2. Since FF is probably not meant to be full state management lib for apps, what patterns do we want to promote around integration points with other state management libs (Redux/Immer, Recoil, Apollo/graphql). IHow can we reduce boilerplate around data binding for more complex data then here: https://github.com/microsoft/FluidExamples/blob/main/react-starter-template/src/utils/hooks/useGetStore.ts ? I'd like to walk away from here understanding how I can move/bind data between FF and state management libs, synthesize/derive information on state changes, and abstract async behavior while doing that. 

	3. Get clear understanding on permissions/auth cycle for my audience (existing set of users), especially around granting various permissions during runtime. Let's say I want to invite specific users to edit the list.

	4. Tools around Data observability. Ability to debug state, trace state changes, server connectivity, persistence etc. Something for example Redux DevTools partially offers.

5. General topics around managing, validating and deploying changes.
	
The goal here would be to have more clear foundation around data layer. There are additional (data-layer related) points that will be relevant once we get to more complex examples around reusable components/UI (composability and customization).

**Comment by ssimic2** [comment]
To summarize current thoughts here (and collect some feedback from the team):

### Goals ###

As stated above, create a set of examples that allows developers to understand concepts that will allow them to build complex applications with Fluid. 

### Assumptions ###

Our documents/examples should reflect the assumed persona associated with first-time usage:

FF will likely be used to extend some existing app with an add-on feature/experience.
FF will likely be used for transient data while the source of truth will be somewhere else.
FF will likely deal with smaller data sizes, while needs will be around fast, high-frequency collaboration.

### Concrete Reference Example ###

As we develop documents/examples it would be nice to be clear what areas/topics are more important than others and is there any ordering pattern we can observe. Then, instead of creating multiple disconnected examples, we could progressively bring one example use-case to completion, while demonstrating solution patterns for each topic as a separate step in that same example.

As we discuss various topics it may be helpful to keep in mind a concrete example scenario - just for reference purposes. An example could be an existing app, say, a trip planner, that developer wants to extend to offer users an ability to collaborate on a "todo" list related to each destination they may visit. The app may use FF to build a dynamic to-do list, but it already has its own representation (source of truth) of the trip plan and associated trip details.

### Format ###

We could potentially focus web docs on smaller concepts and code snippets, while keeping an example project as an overall reference on "how everything works together". We could progress the project through different branches (each branch ends up being a step) if we find good progression sequence.

### Constraints ###

At this point in time, we will only be looking at FF as a data layer, without unlocking more complex UI composition patterns. We will not be going into multiple data stores solutions, consumer/producer patterns, etc.

### Topics ###

Topics are listed in no particular order of relevancy, first goal here would be just to surface the most relevant ones.

- Demonstrate what it would take to replace a non-collaborative experience with a collaborative one. The goal here is to imply simplicity. In our example - what is minimal boilerplate code it would take to substitute existing functionality (say one user can edit a "todo" list) to "multiple users can collaborate" to build the same todo list.
- Demonstrate patterns that would play out with other JS libs dealing with data (Immer/Redux, Apollo/GraphQL). The focus would be on a select few, and we can expand the matrix further. The idea would be to showcase how FF can coexist with other data libs while dealing with more complex data structures (we have some examples on immer). Our basic examples mix data & views and imply complex boilerplate code. We need to demonstrate simplicity here, and patterns suitable for integrating with solutions users are familiar with.
- Demonstrate ability to transition from "source of truth" data to FF data, and vice versa - in real-time and explicit import/export. Demonstrate ability to "reduce" data out of both sources.
- Demonstrate the ability for views to consume data in a generic way, without concerns about what the source is.
- Demonstrate suitable data patterns for "collaboration", while structuring FF data in a way that allows users to interact without stepping on each other's actions.
- Demonstrate suitable patterns for container creations and data correlation. Developers will often correlate container IDs to some IDs represented in the "source of truth". Who does creation, when, how do other clients know about it, id mapping etc?
Demonstrate cohesive representation of system's "health", ability to detect errors and recover from them. Now we have multiple states connected/disconnected, saved/dirty, we need to understand if the matrix is simple to interpret, errors are clear etc while investigating "what can go wrong" scenarios.
- Demonstrate ability to measure and monitor system performance (to be expanded. Not sure what examples would be suitable here). Demonstrate general observability of the system.
- Demonstrate patterns around authorization/authentication (to be expanded).
- Demonstrate ability to leverage audience data, correlate IDs with "source of truth", and assign and utilize permissions.
- Demonstrate the capability of various DDSes, while exploring production-grade (100% correctness) solutions. Here we probably need to map each DDS to a strong use case.
- Demonstrate testability of the system. What would unit-test or e2e now look like now that you have FF as part of your system
- Demonstrate patterns around offline work

What other topics make sense for our persona? What would give them confidence to adopt FF for existing application ?
Do we tackle large data now ?
Is Undo/redo a must ?
