### ISSUE TITLE
Routerlicious driver support for long polling fallback

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#8856]
Currently the Routerlicious driver only supports websockets as the protocol. This work tracks supporting long polling in addition to websockets for creating/maintaining a server connection.

This ask is specifically coming from Azure Fluid Relay customers.

## Issues
- [ ] ...

**Comment by tanviraumi** [comment]
In progress now (#8820 )

**Comment by znewton** [comment]
Summary of findings and progress made in #8820:
- Socket.io can be configured to use websockets by default, and long-polling when WebSockets are not available in the current context using the option `transports: ["websockets", "polling"]`
    - Note: this is only relevant for IE9, which is not supported by FluidFramework, so it will not be used
- We can tie into the socket.io client's `connect_error` event to switch over to long-polling (with WebSocket allowed as an upgrade) specifically when a WebSocket transport layer error is detected.
    - Another neat benefit is that this will establish a polling connection, and then try to upgrade to WebSockets again in the case that the connection failure was transient
- By additionally listening to socket.io client's `reconnect_attempt` events, we can accurately determine when failing over to polling did not solve the issue and the container should be closed.
- By working with @vladsud we have made the new failover behavior optionally usable by any driver (disabled by default).
- Lastly, I have opened #8968 to track the addition of telemetry to this new failover flow. I think the telemetry will be more useful for ODSP than Azure Fluid Relay since AFR does not collect any client telemetry at this moment.

**Comment by vladsud** [comment]
Thanks for the update - looks great!

I'd hope you collect some telemetry in this space from FRS side, including - how many clients leverage this option, and how expensive it is to service.

Do you have any thoughts on perceived user experience when using long polling? I.e., maybe we will learn that it's not really great for fluid workloads? And if so, at least we want to expose this info somehow to clients (hosts), such that they can assess situation (for some workloads it will make sense to surface it to user / tenant admins)
