### ISSUE TITLE
Ability for the server to disconnect a specific client

### ISSUE THREAD

**Issue by GaryWilber** [microsoft/FluidFramework#9046]
The odsp driver supports multiplexing multiple document connections over a single websocket. So a webpage could connect to multiple ODSP files and end up with just 1 websocket. 
The server tracks each client separately. If one client has their permission revoked or downgraded, we need to remove that client from the session / websocket.

Today when this happens, the server will send a `server_disconnect` message with an `AccessChanged` error code and disconnect the entire websocket. This means a single client having their permission revoked causes all their clients to have to reconnect.

We should improve this flow by having the ability for the server to disconnect a specific client instead of the entire websocket.

Preferred proposal:
- Server sends a `disconnect_document` message to the websocket. That message will include the client id being disconnected and an error object that includes an error code / message (I think `IOdspSocketError` object would work)
This `disconnect_document` event would be nice because it fits with how things work today. Clients have the ability to tell the server that they want to disconnect a specific client by sending a `disconnect_document` message with a specific client id. So having the same ability for the server to do this too will make that event isomorphic. 

Other options:
- Server can send the client a `nack` for the specific client id - This may work, but normally nacks are sent in response to something the client just did. So sending an "out of band" nack for a permissions revocation is odd.

Tagging @vladsud @anthony-murphy for vis

**Comment by vladsud** [comment]
Most of the nacks are gone from our workflows (for example, client itself detects it needs "read" -> "write" upgrade and does it itself, instead of relying on a nack).
The only remining are 10K ops, that I think should result in container critical error.
So, I'd prefer not to use nacks for that (and in future treat nacks as critical errors).

How often that condition happens? If it's rare, is it worth fixing?
In other places I believe we use a field that can container either docId or clientId to communicate if message is for whole doc or particular client. Is it worth considering here?
Otherwise disconnect_document is fine.

**Comment by vladsud** [comment]
@GaryWilber, let's use https://dev.azure.com/fluidframework/internal/_queries/edit/878/?triage=true for tracking if there is any continuation, but is this still useful thing to do?
